CREATE function Sp_Acc_Get_SummaryAC(@DocRef Int,@DocType INT)  
Returns  nvarchar(50)  
As  
Begin  
Declare @RETAILINVOICE INT
Declare @RETAILINVOICEAMENDMENT INT
Declare @RETAILINVOICECANCELLATION INT

Declare @INVOICE INT  
Declare @INVOICEAMENDMENT INT  
Declare @INVOICECANCELLATION INT  

Declare @SALESRETURN INT  
Declare @SALESRETURNCANCELLATION int  
Declare @SALESRETURNAMENDMENT INT  

Declare @BILL INT  
Declare @BILLAMENDMENT INT  
Declare @BILLCANCELLATION INT  

Declare @PURCHASERETURN INT
Declare @PURCHASERETURNAMENDMENT int  
Declare @PURCHASERETURNCANCELLATION INT

Declare @STOCKTRANSFERIN int  
Declare @STOCKTRANSFERINCANCELLATION int  
Declare @STOCKTRANSFERINAMENDMENT int  

Declare @STOCKTRANSFEROUT int  
Declare @STOCKTRANSFEROUTCANCELLATION int  
Declare @STOCKTRANSFEROUTAMENDMENT int  

Declare @GRN int  
Declare @GRNCANCELLATION int  
Declare @GRNAMENDMENT int  

Declare @SERVICE_INVOICE INT
Declare @SERVICE_INVOICE_CANCEL INT

Declare @Status INT
Declare @AccountID Int
  
Set @RETAILINVOICE = 1
Set @RETAILINVOICEAMENDMENT = 2
Set @RETAILINVOICECANCELLATION =3

Set @INVOICE =4
Set @INVOICEAMENDMENT = 5
Set @INVOICECANCELLATION = 6

Set @SALESRETURN = 7  
Set @SALESRETURNCANCELLATION = 40  
Set @SALESRETURNAMENDMENT =72  

Set @BILL = 8
Set @BILLAMENDMENT = 9
Set @BILLCANCELLATION = 10

Set @PURCHASERETURN = 11
Set @PURCHASERETURNAMENDMENT =73
Set @PURCHASERETURNCANCELLATION = 12

Set @STOCKTRANSFERIN = 54  
Set @STOCKTRANSFERINCANCELLATION =67  
Set @STOCKTRANSFERINAMENDMENT =69  

Set @STOCKTRANSFEROUT = 55  
Set @STOCKTRANSFEROUTCANCELLATION =68  
Set @STOCKTRANSFEROUTAMENDMENT =70  

Set @GRN =41  
Set @GRNCANCELLATION =42  
Set @GRNAMENDMENT = 66  

Set @SERVICE_INVOICE = 88
Set @SERVICE_INVOICE_CANCEL = 89

If @DocType=@RETAILINVOICE or @DocType=@RETAILINVOICEAMENDMENT or @DocType=@RETAILINVOICECANCELLATION
Begin   
	set @AccountId = 5     
End  
Else If @DocType=@INVOICE or @DocType=@INVOICEAMENDMENT or @DocType=@INVOICECANCELLATION
Begin
	set @AccountId = 5
End  
Else if @DocType=@SALESRETURN or @DocType=@SALESRETURNCANCELLATION or @DocType=@SALESRETURNAMENDMENT
Begin  
 	Select @Status = Status from InvoiceAbstract where InvoiceID=@DocRef  
 	If (isnull(@status,0) & 32)<>0  
  		Set @AccountId = 32 
 	Else  
  		Set @AccountId = 30
End
Else If @DocType=@BILL or @DocType=@BILLAMENDMENT or @DocType=@BILLCANCELLATION
Begin
 	Set @AccountId = 6
End
Else if @DocType=@PURCHASERETURN  or @DocType=@PURCHASERETURNAMENDMENT or @DocType=@PURCHASERETURNCANCELLATION
Begin  
 	Set @AccountId = 31
End  
Else if @DocType=@STOCKTRANSFERIN  or @DocType=@STOCKTRANSFERINCANCELLATION or @DocType=@STOCKTRANSFERINAMENDMENT  
Begin  
 	Set @AccountId = 36
End   
Else if @DocType=@STOCKTRANSFEROUT   or @DocType=@STOCKTRANSFEROUTCANCELLATION or @DocType=@STOCKTRANSFEROUTAMENDMENT  
Begin  
 	Set @AccountId = 37
End
Else if @DocType=@GRN  or @DocType=@GRNCANCELLATION  or @DocType=@GRNAMENDMENT  
Begin
 	Set @AccountId = 34
End  
Else if @DocType = @SERVICE_INVOICE  or @DocType = @SERVICE_INVOICE_CANCEL  
Begin  
 	Set @AccountId = 109
End  

return @AccountID

End


