CREATE function sp_acc_GetNarration(@DocRef INT,@DocType INT)
Returns  nvarchar(2000)
As
Begin
DECLARE @RETAILINVOICE INT
DECLARE @RETAILINVOICEAMENDMENT INT
DECLARE @RETAILINVOICECANCELLATION INT
DECLARE @INVOICE INT
DECLARE @INVOICEAMENDMENT INT
DECLARE @INVOICECANCELLATION INT
DECLARE @SALESRETURN INT
DECLARE @BILL INT
DECLARE @BILLAMENDMENT INT
DECLARE @BILLCANCELLATION INT
DECLARE @PURCHASERETURN INT
DECLARE @PURCHASERETURNCANCELLATION INT
DECLARE @COLLECTIONS INT
DECLARE @DEPOSITS INT
DECLARE @BOUNCECHEQUE INT
DECLARE @REPOFBOUNCECHEQUE INT
DECLARE @PAYMENTS INT
DECLARE @PAYMENTCANCELLATION INT
DECLARE @AUTOENTRY INT
DECLARE @DEBITNOTE INT
DECLARE @CREDITNOTE INT
DECLARE @CLAIMSTOVENDOR INT
DECLARE @CLAIMSSETTLEMENT INT
DECLARE @CLAIMSCANCELLATION INT
DECLARE @COLLECTIONCANCELLATION INT
DECLARE @MANUALJOURNAL INT
DECLARE @ARV_AMENDMENT INT
DECLARE @APV_AMENDMENT INT
DECLARE @MANUALJOURNALINVOICE INT
DECLARE @MANUALJOURNALSALESRETURN INT
DECLARE @MANUALJOURNALBILL INT
DECLARE @MANUALJOURNALPURCHASERETURN INT
DECLARE @MANUALJOURNALCOLLECTIONS INT
DECLARE @MANUALJOURNALPAYMENTS INT
DECLARE @MANUALJOURNALDEBITNOTE INT
DECLARE @MANUALJOURNALCREDITNOTE INT
DECLARE @MANUALJOURNALOLDREF INT
DECLARE @CONTRAENTRYCANCELLATION INT
DECLARE @MANUALJOURNALAPV INT
DECLARE @MANUALJOURNALARV INT
DECLARE @MANUALJOURNALOTHERPAYMENTS INT
DECLARE @MANUALJOURNALOTHERRECEIPTS INT
DECLARE @MANUALJOURNALOTHERDEBITNOTE INT
DECLARE @MANUALJOURNALOTHERCREDITNOTE INT
DECLARE @SALESRETURNCANCELLATION INT
DECLARE @DISPATCH INT
DECLARE @DISPATCHCANCELLATION INT
DECLARE @APV INT
DECLARE @APVCANCELLATION INT
DECLARE @ARV INT
DECLARE @ARVCANCELLATION INT
DECLARE @STOCKTRANSFERIN INT
DECLARE @STOCKTRANSFEROUT INT
DECLARE @PETTYCASH INT
DECLARE @PETTYCASHCANCELLATION INT
DECLARE @PETTYCASHAMENDMENT INT
DECLARE @GRN INT
DECLARE @GRNCANCELLATION INT
DECLARE @DEBITNOTECANCELLATION INT
DECLARE @CREDITNOTECANCELLATION INT
DECLARE @DEBITNOTEAMENDMENT INT
DECLARE @CREDITNOTEAMENDMENT INT
DECLARE @STOCKTRANSFERINCANCELLATION INT
DECLARE @STOCKTRANSFEROUTCANCELLATION INT
DECLARE @STOCKTRANSFERINAMENDMENT INT
DECLARE @STOCKTRANSFEROUTAMENDMENT INT
DECLARE @DISPATCHAMENDMENT INT
DECLARE @SALESRETURNAMENDMENT INT
DECLARE @GRNAMENDMENT INT
DECLARE @PURCHASERETURNAMENDMENT INT
DECLARE @INTERNALCONTRA INT
DECLARE @INTERNALCONTRACANCELLATION INT
DECLARE @COLLECTIONAMENDMENT INT
DECLARE @PAYMENT_AMENDMENT INT
DECLARE @MANUALJOURNAL_NEWREFERENCE INT
DECLARE @MANUALJOURNALCLAIMS INT

Declare @SERVICE_INWARD Int
Declare @SERVICE_OUTWARD Int
Declare @SERVICE_INWARD_CANCEL Int
Declare @SERVICE_OUTWARD_CANCEL Int
Declare @DAMAGE_INVOICE Int

DECLARE @DocumentNumber INT
DECLARE @DocumentDesc nVarChar(50)

SET @RETAILINVOICE = 1
SET @RETAILINVOICEAMENDMENT = 2
SET @RETAILINVOICECANCELLATION = 3
SET @INVOICE = 4
SET @INVOICEAMENDMENT = 5
SET @INVOICECANCELLATION = 6
SET @SALESRETURN = 7
SET @BILL = 8
SET @BILLAMENDMENT = 9
SET @BILLCANCELLATION = 10
SET @PURCHASERETURN = 11
SET @PURCHASERETURNCANCELLATION = 12
SET @COLLECTIONS = 13
SET @DEPOSITS = 14
SET @BOUNCECHEQUE = 15
SET @REPOFBOUNCECHEQUE = 16
SET @PAYMENTS = 17
SET @PAYMENTCANCELLATION = 18
SET @AUTOENTRY = 19
SET @DEBITNOTE = 20
SET @CREDITNOTE = 21
SET @CLAIMSTOVENDOR = 22
SET @CLAIMSSETTLEMENT = 23
SET @CLAIMSCANCELLATION = 24
SET @COLLECTIONCANCELLATION = 25
SET @MANUALJOURNAL = 26
SET @MANUALJOURNALINVOICE =28
SET @MANUALJOURNALSALESRETURN =29
SET @MANUALJOURNALBILL = 30
SET @MANUALJOURNALPURCHASERETURN = 31
SET @MANUALJOURNALCOLLECTIONS = 32
SET @MANUALJOURNALPAYMENTS = 33
SET @MANUALJOURNALDEBITNOTE = 34
SET @MANUALJOURNALCREDITNOTE = 35
SET @MANUALJOURNALOLDREF = 37
SET @CONTRAENTRYCANCELLATION = 38
SET @SALESRETURNCANCELLATION = 40
SET @DISPATCH = 44
SET @DISPATCHCANCELLATION = 45
SET @APV = 46
SET @APVCANCELLATION = 47
SET @ARV = 48
SET @ARVCANCELLATION = 49
SET @PETTYCASH = 52
SET @PETTYCASHCANCELLATION = 53
SET @PETTYCASHAMENDMENT = 94
SET @STOCKTRANSFERIN = 54
SET @STOCKTRANSFEROUT = 55
SET @GRN = 41
SET @GRNCANCELLATION = 42
SET @MANUALJOURNALAPV = 60
SET @MANUALJOURNALARV = 61
SET @MANUALJOURNALOTHERPAYMENTS = 62
SET @MANUALJOURNALOTHERRECEIPTS = 63
SET @DEBITNOTECANCELLATION = 64
SET @CREDITNOTECANCELLATION = 65
SET @GRNAMENDMENT = 66
SET @STOCKTRANSFERINCANCELLATION = 67
SET @STOCKTRANSFEROUTCANCELLATION = 68
SET @STOCKTRANSFERINAMENDMENT = 69
SET @STOCKTRANSFEROUTAMENDMENT = 70
SET @DISPATCHAMENDMENT = 71
SET @SALESRETURNAMENDMENT = 72
SET @PURCHASERETURNAMENDMENT = 73
SET @INTERNALCONTRA = 74
SET @INTERNALCONTRACANCELLATION = 75
SET @COLLECTIONAMENDMENT=77
SET @PAYMENT_AMENDMENT = 78
SET @MANUALJOURNALOTHERDEBITNOTE = 79
SET @MANUALJOURNALOTHERCREDITNOTE = 80
SET @MANUALJOURNAL_NEWREFERENCE = 81
SET @MANUALJOURNALCLAIMS = 82
SET @ARV_AMENDMENT = 83
SET @APV_AMENDMENT = 84
SET @CREDITNOTEAMENDMENT = 90
SET @DEBITNOTEAMENDMENT = 91

Set @SERVICE_INWARD = 151
Set @SERVICE_OUTWARD = 153
Set @SERVICE_INWARD_CANCEL  = 152
Set @SERVICE_OUTWARD_CANCEL  = 154
Set @DAMAGE_INVOICE = 155

DECLARE @ReturnValue nVarchar(2000)

If @DocType = @APV Or @DocType = @APVCANCELLATION  Or @DocType = @APV_AMENDMENT Or @DocType = @MANUALJOURNALAPV
Begin
Select @ReturnValue = IsNull(APVRemarks, N'') From APVAbstract Where DocumentID = @DocRef
End
Else If @DocType = @ARV Or @DocType = @ARVCANCELLATION  Or @DocType = @ARV_AMENDMENT Or @DocType = @MANUALJOURNALARV
Begin
Select @ReturnValue = Cast(IsNull(ARVRemarks, '') as nvarchar) From ARVAbstract Where DocumentID = @DocRef
End
Else If @DocType = @COLLECTIONS Or @DocType = @COLLECTIONCANCELLATION  Or @DocType = @COLLECTIONAMENDMENT Or @DocType = @BOUNCECHEQUE Or @DocType = @MANUALJOURNALOTHERRECEIPTS
Begin
Select @ReturnValue = IsNull(Narration, N'') From Collections Where DocumentID = @DocRef
End
Else If @DocType = @PAYMENTS Or @DocType = @PAYMENTCANCELLATION  Or @DocType = @PAYMENT_AMENDMENT Or @DocType = @AUTOENTRY Or @DocType = @PETTYCASH  Or @DocType = @PETTYCASHCANCELLATION Or @DocType = @MANUALJOURNALOTHERPAYMENTS or @DocType = @PETTYCASHAMENDMENT
Begin
Select @ReturnValue = IsNull(Narration, N'') From Payments Where DocumentID = @DocRef
End
Else If @DocType = @DEPOSITS Or @DocType = @CONTRAENTRYCANCELLATION  Or @DocType = @REPOFBOUNCECHEQUE
Begin
Select @ReturnValue = IsNull(Narration, N'') From Deposits Where DepositID = @DocRef
End
Else If @DocType = @INTERNALCONTRA Or @DocType = @INTERNALCONTRACANCELLATION
Begin
Select @ReturnValue = IsNull(Remarks, N'') From ContraAbstract Where ContraID = @DocRef
End
Else If @DocType = @MANUALJOURNAL Or @DocType = @MANUALJOURNALOLDREF
Begin
Select Top 1 @ReturnValue = cast(IsNull(Remarks,'') as nvarchar) from GeneralJournal Where DocumentType = @DocType And DocumentNumber = @DocRef
End
Else If @DocType = @MANUALJOURNAL_NEWREFERENCE
Begin
Select Top 1 @ReturnValue = Cast(IsNull(Remarks,'') as nvarchar) from GeneralJournal Where DocumentType = @MANUALJOURNAL And DocumentNumber = (Select DocumentID from ManualJournal Where NewRefID = @DocRef)
End
Else If @DocType = @DebitNote or @DocType = @DEBITNOTEAMENDMENT
Begin
Select @ReturnValue = IsNull(Memo, N'') From Debitnote Where DebitId = @DocRef
End
Else If @DocType = @DEBITNOTECANCELLATION
Begin
Select @ReturnValue = IsNull(Cancel_Memo, N'') From Debitnote Where DebitId = @DocRef
End
Else If @DocType = @CreditNote or @DocType = @CREDITNOTEAMENDMENT
Begin
Select @ReturnValue = IsNull(Memo, N'') From Creditnote Where CreditId = @DocRef
End
Else If @DocType = @CREDITNOTECANCELLATION
Begin
Select @ReturnValue = IsNull(Cancel_Memo, N'') From Creditnote Where CreditId = @DocRef
End
Else If @DocType = @SERVICE_INWARD  Or @DocType = @SERVICE_INWARD_CANCEL
Begin
Select @ReturnValue = IsNull(ReferenceDescription, N'') From ServiceAbstract Where InvoiceID = @DocRef and ServiceType = 'Inward'
End
Else If @DocType = @SERVICE_OUTWARD  Or @DocType = @SERVICE_OUTWARD_CANCEL
Begin
Select @ReturnValue = IsNull(ReferenceDescription, N'') From ServiceAbstract Where InvoiceID = @DocRef and ServiceType = 'Outward'
End
Else If @DocType = @DAMAGE_INVOICE
Begin
Select @ReturnValue = ISNULL(Description,'') From DandDInvAbstract Where DandDInvID = @DocRef
End
Else
Begin
Select @ReturnValue = N''
End
Return @ReturnValue
End

