CREATE FUNCTION StripTimeFromDate(@INPUTDATE datetime)
RETURNS DATETIME
AS
BEGIN
DECLARE @RETURNDATE DATETIME
DECLARE @MILLISECONDS INT
DECLARE @SECONDS INT
DECLARE @MINUTES INT
DECLARE @HOURS INT

SET @MILLISECONDS = DATEPART(ms, @INPUTDATE)
SET @SECONDS = DATEPART(ss, @INPUTDATE)
SET @MINUTES = DATEPART(mi, @INPUTDATE)
SET @HOURS = DATEPART(hh, @INPUTDATE)
SET @RETURNDATE = DATEADD(ms, 0 - @MILLISECONDS, @INPUTDATE)
SET @RETURNDATE = DATEADD(ss, 0 - @SECONDS, @RETURNDATE)
SET @RETURNDATE = DATEADD(mi, 0 - @MINUTES, @RETURNDATE)
RETURN DATEADD(hh, 0 - @HOURS, @RETURNDATE)
END
