IF EXISTS(SELECT Top 1 1 FROM sys.objects WHERE Name = N'TransactionByDay')
BEGIN
	DROP TABLE [TransactionByDay]
END
GO
CREATE TABLE [dbo].[TransactionByDay](
	[TransactionId] INT IDENTITY(1,1),
	[TransactionDate] [datetime] NULL,
	[Product_Code] [nvarchar](255) NULL,
	[CategoryGroup] [nvarchar](255) NULL,		
	[Category] [nvarchar](255) NULL,
	[ItemFamily] [nvarchar](255) NULL,
	[ItemSubFamily] [nvarchar](255) NULL,
	[ItemGroup] [nvarchar](255) NULL,			
	[Batch_Code] [nvarchar](255) NULL,
	[Batch_Number] [nvarchar](255) NULL,
	[Expairy] [datetime] NULL,
	[UOMQty] [decimal](18, 6) NULL, 
	[IsDamage] [Int] NULL, 
	[DamagesReason] [nvarchar](255) NULL,
	[ReceivedAgeing] [int] NULL,
	[Opening] [decimal](18, 6) NULL,
	[Opening_Rate] [decimal](18, 6) NULL,
	[Opening_Value] [decimal](18, 6) NULL,
	[Purchase] [decimal](18, 6) NULL,
	[Purchase_Rate] [decimal](18, 6) NULL,
	[Purchase_Value] [decimal](18, 6) NULL,
	[Purchase_Discount] [decimal](18, 6) NULL,
	[Purchase_DiscPerUnit] [decimal](18, 6) NULL,
	[Purchase_DISCTYPE] [decimal](18, 6) NULL,
	[Purchase_InvDiscPerc] [decimal](18, 6) NULL,
	[Purchase_InvDiscAmtPerUnit] [decimal](18, 6) NULL,
	[Purchase_InvDiscAmount] [decimal](18, 6) NULL,
	[Purchase_OtherDiscPerc] [decimal](18, 6) NULL,
	[Purchase_OtherDiscAmtPerUnit] [decimal](18, 6) NULL,
	[Purchase_OtherDiscAmount] [decimal](18, 6) NULL,
	[TransferIn] [decimal](18, 6) NULL,
	[TransferIn_Rate] [decimal](18, 6) NULL,
	[TransferIn_Value] [decimal](18, 6) NULL,
	[SaleReturn] [decimal](18, 6) NULL,
	[SaleReturn_Rate] [decimal](18, 6) NULL,
	[SaleReturn_PurchaseValue] [decimal](18, 6) NULL,
	[SaleReturn_Value] [decimal](18, 6) NULL,
	[Sales] [decimal](18, 6) NULL,
	[Sales_Rate] [decimal](18, 6) NULL,
	[Sales_PurchaseValue] [decimal](18, 6) NULL,
	[Sales_Value] [decimal](18, 6) NULL,
	[PruchaseReturn] [decimal](18, 6) NULL,
	[PruchaseReturn_Rate] [decimal](18, 6) NULL,
	[PruchaseReturn_Value] [decimal](18, 6) NULL,
	[TransferOut] [decimal](18, 6) NULL,
	[TransferOut_Rate] [decimal](18, 6) NULL,
	[TransferOut_Value] [decimal](18, 6) NULL,
	[Damage_Destroy] [decimal](18, 6) NULL,
	[Damage_Destroy_Rate] [decimal](18, 6) NULL,
	[Damage_Destroy_Value] [decimal](18, 6) NULL,
	[Closing] [decimal](18, 6) NULL,
	[Closing_Rate] [decimal](18, 6) NULL,
	[Closing_Value] [decimal](18, 6) NULL
) ON [PRIMARY]
GO