Create Procedure mERP_SP_insert_RecdSKUPortfolio(
	@EFFECTIVEFROMDATE Datetime,
	@CUSTOMERID nvarchar(15),
	@PRODUCTPRIORITY int,
	@PRODUCTCODE nvarchar(255),
	@PRODUCTLEVEL int,
	@ACTIVE int,
	@DocumentID nvarchar(255))  
As  
Begin  
	SET DATEFORMAT DMY
	insert into Recd_SKUPortfolio (EFFECTIVEFROMDATE,CUSTOMERID,PRODUCTPRIORITY,PRODUCTCODE,PRODUCTLEVEL,ACTIVE,status,DocumentID)
	Values (@EFFECTIVEFROMDATE,@CUSTOMERID,@PRODUCTPRIORITY,@PRODUCTCODE,@PRODUCTLEVEL,@ACTIVE,0,@DocumentID)
End  
