CREATE PROCEDURE SP_ACC_PRN_CUS_APVDETAIL(@APVID INTEGER)  
AS  
  
DECLARE @RECORD_SEP  nVARCHAR(10)  
DECLARE @COLUMN_SEP  nVARCHAR(10)  
  
DECLARE @DOCUMENTID  INT  
DECLARE @TYPE    INT  
DECLARE @ACCOUNTNAME NVARCHAR(255)  
DECLARE @AMOUNT   DECIMAL(18,6)  
DECLARE @PARTICULARS NVARCHAR(4000)  
DECLARE @ARVTYPE  NVARCHAR(50)  
DECLARE @ROW_DATA  NVARCHAR(255)  
DECLARE @COLUMN_DATA NVARCHAR(255)  
  
DECLARE @PARTICULAR1 NVARCHAR(4000)    
DECLARE @PARTICULAR2 NVARCHAR(4000)    
DECLARE @PARTICULAR3 NVARCHAR(4000)    
DECLARE @PARTICULAR4 NVARCHAR(4000)    
  
DECLARE @ROWWISEDATA  NVARCHAR(4000)    
DECLARE @COLWISEDATA  NVARCHAR(4000)    
  
SET @RECORD_SEP = CHAR(2)  
SET @COLUMN_SEP = CHAR(1)  
  
  
CREATE TABLE #SPLITROW     
(    
 ROWNUM INT IDENTITY(1,1),    
 ROWDATA NVARCHAR(4000)    
)    
    
CREATE TABLE #SPLITCOLUMN    
(    
 ROWNUM INT IDENTITY(1,1),    
 COLUMNDATA NVARCHAR(4000)    
)    
  
  
-- -- -- SELECT @PREFIX =PREFIX FROM VOUCHERPREFIX  
-- -- -- WHERE TRANID ='ACCOUNTS PAYABLE VOUCHER'  
CREATE TABLE #TEMPAPVDETAILS  
(  
 ROWNUM    INT IDENTITY(1,1),  
 TYPE    NVARCHAR(50),  
 ACCOUNTNAME  NVARCHAR(255),  
 PARTICULAR1  NVARCHAR(255),  
 PARTICULAR2  NVARCHAR(255),  
 PARTICULAR3  NVARCHAR(255),  
 PARTICULAR4  NVARCHAR(255),  
 AMOUNT   DECIMAL(18,6)  
)  
  
--DOCUMENTID  
DECLARE APV CURSOR FOR  
SELECT  DOCUMENTID ,TYPE,   
DBO.GETACCOUNTNAME(ISNULL(ACCOUNTID,0)),AMOUNT,PARTICULAR FROM   
APVDETAIL WHERE [APVDETAIL].[DOCUMENTID] = @APVID  
  
OPEN APV  
  
FETCH FROM APV INTO @DOCUMENTID,@TYPE,@ACCOUNTNAME,@AMOUNT,@PARTICULARS   
WHILE @@FETCH_STATUS = 0  
 BEGIN  
  
  IF @TYPE = 0  
   BEGIN  
    SET @ARVTYPE = dbo.LookupDictionaryItem('Item',Default)  
   END  
  ELSE IF @TYPE = 1   
   BEGIN  
    SET @ARVTYPE = dbo.LookupDictionaryItem('Others',Default)  
   END  
  ELSE IF @TYPE = 2   
   BEGIN  
    SET @ARVTYPE = dbo.LookupDictionaryItem('Asset',Default)  
   END  
  
  INSERT INTO #TEMPAPVDETAILS (TYPE ,ACCOUNTNAME,PARTICULAR2,AMOUNT)  
  VALUES(@ARVTYPE,@ACCOUNTNAME,dbo.LookupDictionaryItem('<Detail>',Default),@AMOUNT)  
    
     /* FIRST SPLIT THE RECORDS ROW WISE */    
     TRUNCATE TABLE #SPLITROW    
     INSERT INTO #SPLITROW    
     EXEC SP_ACC_SQLSPLIT @PARTICULARS,@RECORD_SEP    
     
     
     /* AFTER SPLITTING INTO SEPARATE RECORDS , SPLIT IT INTO COLUM WISE */    
     DECLARE CURSORROWDATA CURSOR FOR    
     SELECT ROWDATA FROM #SPLITROW ORDER BY ROWNUM    
  
     OPEN CURSORROWDATA     
       FETCH FROM CURSORROWDATA INTO @ROWWISEDATA    
           
       WHILE @@FETCH_STATUS = 0    
         BEGIN    
          /* FIRST TRUNCATE THE TABLE EVERY TIME , TO AVOID APPENDING */    
          TRUNCATE TABLE #SPLITCOLUMN    
          INSERT INTO #SPLITCOLUMN    
          EXEC SP_ACC_SQLSPLIT @ROWWISEDATA,@COLUMN_SEP    
             
          /* INSERT INTO MAIN TABLE */    
          /* BEFORE SPLITTING THE DETAILS , INSERT THE MAIN ROW */    
          /* FOR DETAILS PART , BASIS THE ARV TYPE , DIFFERENT COLUMNS    
           HAS TO BE INSERTED */    
    SET @PARTICULAR1 = ''  
    SET @PARTICULAR2 = ''  
    SET @PARTICULAR3 = ''  
    SET @PARTICULAR4 = ''  
  
    IF @TYPE = 0   
     BEGIN    
      SELECT @PARTICULAR1 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 1    
      SELECT @PARTICULAR2 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 2    
      SELECT @PARTICULAR3 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 3  
      SELECT @PARTICULAR4 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 4    
     END    
    ELSE IF @TYPE = 1 --ASSET    
     BEGIN    
      SELECT @PARTICULAR1 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 1  
      SELECT @PARTICULAR2 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 2    
     END    
    ELSE IF @TYPE = 2   
     BEGIN    
      SELECT @PARTICULAR1 = COLUMNDATA FROM #SPLITCOLUMN     
      WHERE ROWNUM = 1  
      SELECT @PARTICULAR2 = COLUMNDATA FROM #SPLITCOLUMN 
      WHERE ROWNUM = 2    
     END    
    INSERT INTO #TEMPAPVDETAILS (PARTICULAR1,PARTICULAR2,PARTICULAR3,PARTICULAR4)  
    VALUES(@PARTICULAR1,@PARTICULAR2,@PARTICULAR3,@PARTICULAR4)  
    FETCH NEXT FROM CURSORROWDATA INTO @ROWWISEDATA     
   END  
      CLOSE CURSORROWDATA    
      DEALLOCATE CURSORROWDATA    
  FETCH NEXT FROM APV INTO @DOCUMENTID,@TYPE,@ACCOUNTNAME,@AMOUNT,@PARTICULARS   
 END  
 CLOSE APV  
 DEALLOCATE APV  
SELECT   
"APV Type" = isnull(type,N''),  
"Account" = isnull(Accountname,N''),  
"Particular1" = isnull(particular1,N''),  
"Particular2" = isnull(particular2,N''),  
"Particular3" = isnull(particular3,N''),  
"Particular4" = isnull(particular4,N''),  
"Amount" = amount  
FROM #TEMPAPVDETAILS  
DROP TABLE #TEMPAPVDETAILS  



