CREATE PROCedure SP_ACC_PRN_FARATIOSDRILLDOWNRECORDS
(  
 	@FROMDATE DATETIME,  
	@TODATE   DATETIME,  
 	@RATIOID  NVARCHAR(50)
)  
AS  
/* 
For Help pls refer Procedure "SP_ACC_RPT_RATIOSDRILLDOWN" 
*/

	Declare @Info NVarchar(4000),@State int
	set @Info = null
	Set @state = 0


	SET DATEFORMAT DMY
 	DECLARE @TOTAL 			DECIMAL(18,6)
	DECLARE @COLORBLUE		INT
	DECLARE @VALUEOFGROUP1		DECIMAL(18,6)
	DECLARE @VALUEOFGROUP2		DECIMAL(18,6)
	DECLARE @GROSSPROFIT		DECIMAL(18,6)
	DECLARE @NETPROFIT		DECIMAL(18,6)
	DECLARE @GROSSLOSS		DECIMAL(18,6)
	DECLARE @NETLOSS		DECIMAL(18,6)
	DECLARE @NETSALES		DECIMAL(18,6)
	DECLARE @PERCENTAGE		NVARCHAR(250)
	DECLARE @GROSSPROFITROWNO	INT
	DECLARE @OPERATING_COST		DECIMAL(18,6)
	DECLARE @WORKINGCAPITAL 	DECIMAL(18,6)

	SET @COLORBLUE = 	1 -- FOR TOTAL'S ETC -- WILL BE DISPLAYED IN BLUE IN FRONTEND

 	CREATE TABLE   #DRILLDOWNTABLE
		(
			ROWNUM 		INT IDENTITY(1,1),
			GROUPID 	INTEGER,
			GROUPNAME 	NVARCHAR(255),
			DEBIT 		DECIMAL(18,6),
			CREDIT 		DECIMAL(18,6),
			FROMDATE 	DATETIME,
			TODATE 		DATETIME,
			DOCREF 		INTEGER,
			DOCTYPE 	INTEGER,
			COLORINFO 	INTEGER,
			PERCENTAGE 	NVARCHAR(50),
		)          



 	CREATE TABLE   #TEMPREGISTER
		( 
			ROWNUM 		INT IDENTITY(1,1),
			GROUPID 	INTEGER,
			GROUPNAME 	NVARCHAR(255),
			DEBIT 		DECIMAL(18,6),
			CREDIT 		DECIMAL(18,6),
			FROMDATE 	DATETIME,
			TODATE 		DATETIME,
			DOCREF 		INTEGER,
			DOCTYPE 	INTEGER,
			COLORINFO 	INTEGER
		) 
         
 	TRUNCATE TABLE #TEMPREGISTER  
 	TRUNCATE TABLE #DRILLDOWNTABLE  

	IF ISNUMERIC(@RATIOID) = 0 
		BEGIN
			SET @RATIOID = 0
		END

-- -- -- -- 	IF @groupid <> 0 or @mode = 0
-- -- -- --  		BEGIN  
-- -- -- -- 			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,@GROUPID,@DOCREF,@DOCTYPE,@MODE,@Info,@State
-- -- -- --   			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
-- -- -- -- 				DOCTYPE ,COLORINFO ,PERCENTAGE)
-- -- -- -- 				SELECT GROUPID ,GROUPNAME ,CAST(ISNULL(DEBIT,0) AS INTEGER),CAST(ISNULL(CREDIT,0) AS INTEGER) ,FROMDATE ,TODATE ,DOCREF ,
-- -- -- -- 				DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
-- -- -- -- 			IF @MODE = 3 
-- -- -- -- 				BEGIN
-- -- -- -- 					SELECT 'Account/Group'= GROUPNAME,DEBIT-CREDIT FROM #DRILLDOWNTABLE  
-- -- -- -- 				END
-- -- -- -- 			GOTO SKIPIMMEDIATELY
-- -- -- --  		END  
	IF @RATIOID = 1 /* CURRENT RATIO */  
		BEGIN  
 			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Current Assets + Loans & Advances',Default) ,@COLORBLUE)
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
  			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL

			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
  			TRUNCATE TABLE #TEMPREGISTER  
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Current Liabilities & Provisions',Default) ,@COLORBLUE)
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,
				DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2 = @TOTAL

			SELECT 'Account/Group'= GROUPNAME,
			Case 
				when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Current Assets + Loans & Advances',Default) ,dbo.LookupDictionaryItem('Current Liabilities & Provisions',Default) ,N'') then ''
				Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
			End
			FROM #DRILLDOWNTABLE  
			where ltrim(rtrim(GroupName)) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) ) ORDER BY ROWNUM
		END  
	ELSE IF @RATIOID = 2 /* QUICK RATIO */  
 		BEGIN  
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Quick Assets',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
			DELETE FROM #TEMPREGISTER WHERE GROUPID IN (0 ,21)  
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			SELECT @TOTAL = DEBIT - CREDIT  FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL

				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((DEBIT * 100) / ABS(@TOTAL),2)
					WHERE GROUPID <> 0 AND DEBIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((CREDIT * 100) / ABS(@TOTAL) * -1 ,2)
					WHERE GROUPID <> 0 AND CREDIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL					
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			TRUNCATE TABLE #TEMPREGISTER  	
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Current Liabilities',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			SELECT @TOTAL = DEBIT - CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2	= @TOTAL
			SELECT 'Account/Group'= GROUPNAME,
			Case 
				when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Quick Assets',Default)  , dbo.LookupDictionaryItem('Current Liabilities',Default) ,N'') then ''
				Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
			End
			FROM #DRILLDOWNTABLE 
			where ltrim(rtrim(GroupName)) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) )
			ORDER BY ROWNUM
		END  
	ELSE IF @RATIOID = 3
		BEGIN
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookupDictionaryItem('Borrowings Short Term / Long Term ',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,6,0,0,3,@Info,@State
			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,3,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			SELECT @TOTAL = DEBIT - CREDIT  FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			TRUNCATE TABLE #TEMPREGISTER  	
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Capital Accounts',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,1,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			SELECT @TOTAL = DEBIT - CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2	= @TOTAL
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			SELECT 'Account/Group'= GROUPNAME,
			Case 
				when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Borrowings Short Term / Long Term ',Default)  , dbo.LookupDictionaryItem('Capital Accounts',Default) ,N'') then ''
				Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
			End
			FROM #DRILLDOWNTABLE  where ltrim(rtrim(GroupName)) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) )
			ORDER BY ROWNUM
		END
	ELSE IF @RATIOID = 4 OR @RATIOID = 5 OR @RATIOID = 6 
		BEGIN
		 	CREATE TABLE   #DRILLDOWNTABLETEMP
				(
					ROWNUM 		INT IDENTITY(1,1),
					GROUPNAME 	NVARCHAR(255),
					DEBIT 		NVARCHAR(100),
					CREDIT 		NVARCHAR(100),
					dummy1		Nvarchar(50),
					GROUPID 	INTEGER,
					FROMDATE 	DATETIME,
					TODATE 		DATETIME,
					DOCREF 		INTEGER,
					DOCTYPE 	INTEGER,
					COLORINFO1 	INTEGER,
					DUMMY2	 	Nvarchar(50),
					COLORINFO2	INTEGER
				)
			INSERT INTO #DRILLDOWNTABLETEMP (GROUPNAME,DEBIT,CREDIT,dummy1,GROUPID,FROMDATE,
				TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMMY2,COLORINFO2)
			EXECUTE SP_ACC_RPT_TRADINGAC @FROMDATE,@TODATE,'3'
			SET @NETPROFIT = 0
			INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME) VALUES(' ')
			/* THIS BLOCK CALCULATES THE RATIO TO DISPLAY AT THE END */
			UPDATE #DRILLDOWNTABLETEMP SET DEBIT = 0 WHERE DEBIT IS NULL AND GROUPID >= 1
			UPDATE #DRILLDOWNTABLETEMP SET CREDIT = 0 WHERE CREDIT IS NULL AND GROUPID >= 1
				IF @RATIOID = 4 -- ITS A GROSS LOSS/ PROFIT RATIO SO GET THE GROSS LOSS / PROFIT
					BEGIN
						SELECT @GROSSPROFITROWNO = ROWNUM FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('P & L Account',Default) )
						DELETE FROM #DRILLDOWNTABLETEMP WHERE ROWNUM >= @GROSSPROFITROWNO - 1
						SET @GROSSPROFIT = 0
						SET @GROSSLOSS	 = 0
						SELECT @GROSSPROFIT = cast(DEBIT as DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('Gross Profit',Default) )
						SELECT @GROSSLOSS   = cast(credit as DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('Gross Loss',Default) )
						SELECT @NETSALES	= CASE WHEN ISNULL(DEBIT,0) = 0 THEN CREDIT ELSE DEBIT END FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = dbo.LookupDictionaryItem('Sales Account',Default) 
						IF @GROSSPROFIT > 0 
							SELECT @PERCENTAGE 	= ROUND(((@GROSSPROFIT / @NETSALES ) * 100 ),2)
						ELSE

							SELECT @PERCENTAGE 	= ROUND(((@GROSSLOSS / @NETSALES ) * 100 * -1),2)
						INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,COLORINFO2) VALUES(NULL,1)
						INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookupDictionaryItem('Ratio',Default) ,@PERCENTAGE,@COLORBLUE,-1)

		 				SELECT 'Account/Group'= GROUPNAME, 
						Case 
							when ltrim(rtrim(GroupName)) in (dbo.LookupDictionaryItem('Trading Account',Default) ,N'') then ''
							Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
						End
						FROM #DRILLDOWNTABLETEMP where ltrim(rtrim(GroupName)) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) ) 
					END
				ELSE IF @RATIOID = 5   -- ITS A NET LOSS/ PROFIT RATIO SO GET THE GROSS LOSS / PROFIT
					BEGIN
						SET @NETPROFIT 	= 0
						SET @NETLOSS 	= 0
 						SELECT @NETPROFIT 	= CAST(DEBIT AS DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('Net Profit',Default) )
						--SELECT @NETLOSS     = DEBIT FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (N'Net Loss')
						SELECT @NETLOSS     = CAST(credit AS DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('Net Loss',Default) )
						--SELECT @NETSALES	= DEBIT FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = N'Sales Account'
						SELECT @NETSALES	= CASE WHEN ISNULL(DEBIT,0) = 0 THEN CREDIT ELSE DEBIT END FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = dbo.LookupDictionaryItem('Sales Account',Default) 
						IF @NETPROFIT > 0 
							SELECT @PERCENTAGE 	= CAST(ROUND(((@NETPROFIT / @NETSALES ) * 100 ),2) AS NCHAR)
						ELSE
							SELECT @PERCENTAGE 	= CAST(ROUND(((@NETLOSS / @NETSALES ) * 100 * -1),2) AS NCHAR)
						INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookupDictionaryItem('Ratio',Default) ,@PERCENTAGE ,@COLORBLUE,-1)

		 				SELECT 'Account/Group'= GROUPNAME, 
						Case 
							when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Trading Account',Default) ,dbo.LookupDictionaryItem('P & L Account',Default) ,N'') then N''
							Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
						End
						FROM #DRILLDOWNTABLETEMP where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default)  )  order by Rownum
					END
				ELSE IF @RATIOID = 6   -- OPERATING COST RATIO NET SALES - NET PROFIT / NET SALES 8 100
					BEGIN
						SELECT @NETLOSS 	= CAST(CREDIT AS DECIMAL(18,6)) * -1 FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('Net Loss',Default) )
						SELECT @NETPROFIT 	= ABS(CAST(DEBIT AS DECIMAL(18,6))) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookupDictionaryItem('Net Profit',Default) )
						SELECT @NETSALES	= CASE WHEN ISNULL(DEBIT,0) = 0 THEN CAST(CREDIT AS DECIMAL(18,6))ELSE CAST(DEBIT AS DECIMAL(18,6)) END FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = dbo.LookupDictionaryItem('Sales Account',Default) 
						IF @NETLOSS <> 0 
							BEGIN
								INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookupDictionaryItem('Ratio',Default) ,0 ,@COLORBLUE,-1)
				 				SELECT 'Account/Group'= GROUPNAME, 
								Case 
									when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Trading Account',Default) ,dbo.LookupDictionaryItem('P & L Account',Default) ,N'') then ''
									Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
								End
								FROM #DRILLDOWNTABLETEMP where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) ) 
							END
						ELSE IF @NETPROFIT <> 0 
							BEGIN
								SELECT @PERCENTAGE 	= CAST(ROUND(((@NETSALES - @NETPROFIT / @NETSALES ) * 100 ),2) AS NCHAR)
								INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookupDictionaryItem('Ratio',Default) ,@PERCENTAGE ,@COLORBLUE,-1)
				 				SELECT 'Account/Group'= GROUPNAME, 
								Case 
									when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Trading Account',Default) ,dbo.LookupDictionaryItem('P & L Account',Default) ,N'') then ''
									Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
								End
								FROM #DRILLDOWNTABLETEMP where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) ) 
							END
						ELSE
							BEGIN
								INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookupDictionaryItem('Ratio',Default) ,0 ,@COLORBLUE,-1)
				 				SELECT 'Account/Group'= GROUPNAME, 
								Case 
									when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Trading Account',Default) ,dbo.LookupDictionaryItem('P & L Account',Default) ,N'') then ''
									Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
								End
								FROM #DRILLDOWNTABLETEMP where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) ) 
							END  
					END
			DROP TABLE #DRILLDOWNTABLETEMP
		End
	ELSE IF @RATIOID = 7 
		BEGIN
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookupDictionaryItem('Sundry Debtors',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,22,0,0,3,@Info,@State

  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			
			SET @VALUEOFGROUP1	= @TOTAL
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(NULL)
			TRUNCATE TABLE #TEMPREGISTER 
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookupDictionaryItem('Sales',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,28,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0 AND ROWNUM  = (SELECT MAX(ROWNUM) FROM #TEMPREGISTER)
			
			SET @VALUEOFGROUP2	= @TOTAL
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(NULL)		
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,PERCENTAGE,COLORINFO,GROUPID ) VALUES(dbo.LookupDictionaryItem('Ratio',Default) ,@PERCENTAGE ,@COLORBLUE,-1)			

			SELECT 'Account/Group'= GROUPNAME,
			Case 
				when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Sundry Debtors',Default) ,dbo.LookupDictionaryItem('Sales',Default) ,N'') and isnull(Groupid,0) = 0 then ''
				Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
			End
			FROM #DRILLDOWNTABLE where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) )
		END
	ELSE IF @RATIOID = 8 --WORKING CAPITAL TURN OVER NET SALES / WORKING CAPITAL TURNOVER
		BEGIN
			TRUNCATE TABLE #TEMPREGISTER 
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookupDictionaryItem('Sales',Default) ,@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,28,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0 AND ROWNUM  = (SELECT MAX(ROWNUM) FROM #TEMPREGISTER)
			SET @NETSALES = @TOTAL
			TRUNCATE TABLE #TEMPREGISTER
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(NULL)
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Working Capital',Default) ,1)
 			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Current Assets + Loans & Advances',Default) ,@COLORBLUE)
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
  			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL

			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
  			TRUNCATE TABLE #TEMPREGISTER  
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookupDictionaryItem('Current Liabilities & Provisions',Default) ,@COLORBLUE)
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,
				DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP2 = @TOTAL

			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			SET @WORKINGCAPITAL = @VALUEOFGROUP1 - @VALUEOFGROUP2
			IF @WORKINGCAPITAL <= 0 OR @NETSALES <= 0
				BEGIN
					SET @PERCENTAGE = 0
				END
			ELSE
				BEGIN
					SET @PERCENTAGE = ROUND(@NETSALES / @WORKINGCAPITAL,2)
				END

			INSERT INTO #DRILLDOWNTABLE(GROUPNAME)VALUES(NULL)

			SELECT 'Account/Group'= GROUPNAME,
			Case 
				when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Working Capital',Default) ,dbo.LookupDictionaryItem('Current Assets + Loans & Advances',Default) ,dbo.LookupDictionaryItem('Current Liabilities & Provisions',Default) ,dbo.LookupDictionaryItem('Sales',Default) ,N'') and isnull(Groupid,0) = 0 then ''
				Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
			End
			FROM #DRILLDOWNTABLE where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) )
		END
	ELSE IF @RATIOID = 9 -- RETURN ON INVESTMENT (NET PROFIT / CAPITAL * 100)
		BEGIN
		 	CREATE TABLE   #DRILLDOWNTABLETEMP1
				(
					ROWNUM 		INT IDENTITY(1,1),
					GROUPNAME 	NVARCHAR(255),
					DEBIT 		NVARCHAR(100),
					CREDIT 		NVARCHAR(100),
					dummy1		Nvarchar(50),
					GROUPID 	INTEGER,
					FROMDATE 	DATETIME,
					TODATE 		DATETIME,
					DOCREF 		INTEGER,
					DOCTYPE 	INTEGER,
					COLORINFO1 	INTEGER,
					DUMMY2	 	Nvarchar(50),
					COLORINFO2	INTEGER
				)
			INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME,DEBIT,CREDIT,dummy1,GROUPID,FROMDATE,
				TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMMY2,COLORINFO2)
			EXECUTE SP_ACC_RPT_TRADINGAC @FROMDATE,@TODATE,'3'
			SET @NETPROFIT = 0
			SELECT @NETPROFIT = ISNULL(DEBIT,0) FROM #DRILLDOWNTABLETEMP1 WHERE GROUPNAME  = dbo.LookupDictionaryItem('Net Profit',Default) 

			INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME) VALUES(NULL)
			INSERT INTO #DRILLDOWNTABLETEMP1(GROUPNAME,COLORINFO2) VALUES(dbo.LookupDictionaryItem('Capital Accounts',Default) ,@COLORBLUE)
	
			TRUNCATE TABLE #TEMPREGISTER
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,1,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO2 ,DUMMY2)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM

			SELECT @TOTAL = DEBIT - CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2	= @TOTAL

			INSERT INTO #DRILLDOWNTABLETEMP1(GROUPNAME) VALUES(' ')  
			
			UPDATE #DRILLDOWNTABLETEMP1 SET DEBIT = 0 WHERE DEBIT IS NULL AND GROUPID >= 1
			UPDATE #DRILLDOWNTABLETEMP1 SET CREDIT = 0 WHERE CREDIT IS NULL AND GROUPID >= 1

			SELECT 'Account/Group'= GROUPNAME, 
			Case 
				when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Trading Account',Default) ,dbo.LookupDictionaryItem('P & L Account',Default) ,dbo.LookupDictionaryItem('Capital Accounts',Default) ,N'') then ''
				Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
			End
		    FROM #DRILLDOWNTABLETEMP1 where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) )
			DROP TABLE #DRILLDOWNTABLETEMP1
		END		
	ELSE IF @RATIOID = 10 --RETURN ON WORKING CAPITAL -> PROFIT / WORKING CAPITAL * 100
		BEGIN
		 	CREATE TABLE   #DRILLDOWNTABLETEMP2
				(
					ROWNUM 		INT IDENTITY(1,1),
					GROUPNAME 	NVARCHAR(255),
					DEBIT 		NVARCHAR(100),
					CREDIT 		NVARCHAR(100),
					dummy1		Nvarchar(50),
					GROUPID 	INTEGER,
					FROMDATE 	DATETIME,
					TODATE 		DATETIME,
					DOCREF 		INTEGER,
					DOCTYPE 	INTEGER,
					COLORINFO1 	INTEGER,
					DUMMY2	 	Nvarchar(50),
					COLORINFO2	INTEGER
				)
			INSERT INTO #DRILLDOWNTABLETEMP2 (GROUPNAME,DEBIT,CREDIT,dummy1,GROUPID,FROMDATE,
				TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMMY2,COLORINFO2)
			EXECUTE SP_ACC_RPT_TRADINGAC @FROMDATE,@TODATE,'3'
			SET @NETPROFIT = 0
			SELECT @NETPROFIT = ISNULL(DEBIT,0) FROM #DRILLDOWNTABLETEMP2 WHERE GROUPNAME  = dbo.LookupDictionaryItem('Net Profit',Default) 
			UPDATE #DRILLDOWNTABLETEMP2 SET DEBIT = 0 WHERE DEBIT IS NULL AND GROUPID >= 1
			UPDATE #DRILLDOWNTABLETEMP2 SET CREDIT = 0 WHERE CREDIT IS NULL AND GROUPID >= 1

			TRUNCATE TABLE #TEMPREGISTER
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME) VALUES(NULL)
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,COLORINFO2) VALUES(dbo.LookupDictionaryItem('Working Capital',Default) ,1)
 			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,COLORINFO2) VALUES(dbo.LookupDictionaryItem('Current Assets + Loans & Advances',Default) ,@COLORBLUE)

  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State

  			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLETEMP2 (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO2 ,DUMMY1)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL

			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME) VALUES(' ')  
  			TRUNCATE TABLE #TEMPREGISTER  
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,COLORINFO2) VALUES(dbo.LookupDictionaryItem('Current Liabilities & Provisions',Default) ,@COLORBLUE)

  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLETEMP2 (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO2 ,DUMMY1)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,
				DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM

			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP2 = @TOTAL

			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME) VALUES(' ')  

			SET @WORKINGCAPITAL = @VALUEOFGROUP1 - @VALUEOFGROUP2
				
			IF @WORKINGCAPITAL <= 0 OR @NETPROFIT = 0
				BEGIN
					SET @PERCENTAGE = 0
				END
			ELSE
				BEGIN
					SET @PERCENTAGE = ROUND(@NETPROFIT / @WORKINGCAPITAL * 100,2)
				END
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME)VALUES(NULL)

			SELECT 'Account/Group'= GROUPNAME, 				
				Case 
					when ltrim(rtrim(isnull(GroupName,N''))) in (dbo.LookupDictionaryItem('Trading Account',Default) ,dbo.LookupDictionaryItem('P & L Account',Default) ,dbo.LookupDictionaryItem('Working Capital',Default) ,dbo.LookupDictionaryItem('Current Assets + Loans & Advances',Default) ,dbo.LookupDictionaryItem('Current Liabilities & Provisions',Default) ,N'') then ''
					Else cast(cast(isnull(DEBIT,0) as DECIMAL(18,6)) - cast(isnull(CREDIT,0) as DECIMAL(18,6)) as Nvarchar(100))
				End
			    FROM #DRILLDOWNTABLETEMP2 where ltrim(rtrim(isnull(GroupName,N''))) not in ( dbo.LookupDictionaryItem('Ratio',Default) ,dbo.LookupDictionaryItem('Total',Default) )
		END

/*
DROP THE TEMP TABLES AS NO LONGER REQUIRED
*/
SKIPIMMEDIATELY:


DROP TABLE #TEMPREGISTER  
DROP TABLE #DRILLDOWNTABLE    



