
CREATE PROCEDURE sp_add_thickclient(@CLIENT_NAME nvarchar(50),
					   @CLIENT_DESCRIPTION nvarchar(255))
AS
INSERT INTO ClientInformation VALUES(@CLIENT_NAME, @CLIENT_DESCRIPTION)
SELECT @@IDENTITY
