CREATE procedure sp_acc_prn_cus_contraentrydetail(@depositid int)
as
DECLARE @DENOMINATIONS AS NVARCHAR(250)

CREATE TABLE #TEMP
(
	ROWNUM		INT IDENTITY(1,1),
	PARTICULARS	DECIMAL(18,6)
)
CREATE TABLE #DENOMINATIONS
(
	ROWNUM			INT IDENTITY(1,1),
	PARTICULARS 	NVARCHAR(50),
	QUANTITY		DECIMAL(18,6),
	TOTAL			DECIMAL(18,6)
)


/* INSERT ALL POSSIBLE DENAMONIATIONS */
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('1000')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('500')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('100')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('50')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('20')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('10')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('5')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('2')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('1')
INSERT INTO #DENOMINATIONS(PARTICULARS)
VALUES('Coins')

DECLARE DENOMINATIONS  CURSOR FOR
select Denominations from deposits where DepositID =@depositid 

OPEN DENOMINATIONS

FETCH FROM DENOMINATIONS INTO @DENOMINATIONS

WHILE @@FETCH_STATUS = 0 
	BEGIN
		INSERT INTO #TEMP
		EXEC SP_ACC_SQLSPLIT @DENOMINATIONS ,N'|'

		UPDATE #TEMP 
		SET PARTICULARS = NULL WHERE PARTICULARS = 0

		--SELECT *,CAST(PARTICULARS AS DECIMAL(18,6)) FROM #TEMP


		UPDATE A
		SET A.QUANTITY = ABS(ISNULL(B.PARTICULARS,0))
		FROM
		#DENOMINATIONS A,#TEMP B
		WHERE A.ROWNUM = B.ROWNUM

		UPDATE #DENOMINATIONS
		SET TOTAL = CAST(PARTICULARS AS NUMERIC) * QUANTITY
		WHERE PARTICULARS <> N'Coins'

		--SELECT * FROM #DENOMINATIONS

		UPDATE #DENOMINATIONS
		SET TOTAL = QUANTITY
		WHERE PARTICULARS = N'Coins'

		--SELECT * FROM #DENOMINATIONS
		SELECT 
		"Denomination" = PARTICULARS, 
		"Count" = 
			CASE
				WHEN QUANTITY = 0 THEN NULL ELSE QUANTITY
			END,
		"Amount" = 
			CASE
				WHEN TOTAL = 0 THEN NULL ELSE TOTAL
			END
		FROM #DENOMINATIONS

-- -- -- 		SELECT '1000', PARTICULARS , 1000 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 1
-- -- -- --		UNION
-- -- -- 		SELECT '500', PARTICULARS , 500 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 2
-- -- -- --		UNION
-- -- -- 		SELECT '100', PARTICULARS , 100 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 3
-- -- -- --		UNION
-- -- -- 		SELECT '50', PARTICULARS , 50 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 4
-- -- -- --		UNION
-- -- -- 		SELECT '20', PARTICULARS , 20 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 5
-- -- -- --		UNION
-- -- -- 		SELECT '10', PARTICULARS , 10 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 6
-- -- -- --		UNION
-- -- -- 		SELECT '5', PARTICULARS , 5 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 7
-- -- -- --		UNION
-- -- -- 		SELECT '2', PARTICULARS , 2 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 8
-- -- -- --		UNION
-- -- -- 		SELECT '1', PARTICULARS , 1 * ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 9
-- -- -- --		UNION
-- -- -- 		SELECT 'Coins', PARTICULARS , ISNULL(ABS(PARTICULARS),0)
-- -- -- 		FROM #TEMP WHERE ROWNUM = 10
		FETCH FROM DENOMINATIONS INTO @DENOMINATIONS
	END
CLOSE DENOMINATIONS
DEALLOCATE DENOMINATIONS



