CREATE PROCEDURE sp_acc_Save_Setup_Bunge      
	(@COMPANYID NVARCHAR (50),          
	@COMPANYNAME NVARCHAR (255),             
	@BILLINGADDRESS NVARCHAR (255),          
	@SHIPPINGADDRESS NVARCHAR (255),          
	@TELEPHONE NVARCHAR (50),          
	@FISCALYEAR INT,          
	@VOUCHERSTART INT,          
	@STREGN nvarchar(50),          
	@STLABEL nvarchar(50),          
	@CTREGN nvarchar(50),          
	@CTLABEL nvarchar(50),          
	@DL20 nvarchar(50),          
	@DL21 nvarchar(50),          
	@ORGANISATIONTYPE INT = NULL,          
	@NUMBEROFPARTNERS INT = NULL,          
	@DRAWINGACCOUNTFLAG INT = NULL,          
	@AUTHORISATIONCAPITAL DECIMAL(18,6) = NULL,          
	@REGISTRATIONDATE DATETIME = NULL,          
	@BUSINESSCOMDATE DATETIME = NULL,          
	@TINNUMBER nvarchar(20) = N'',          
	@SALESPORTAL nvarchar(100) = N'',          
	@LOCALIZEDNAME nVarchar(255) = N'',          
	@InstallationType Int =0,          
	@CompanyId_FXS nVarchar(2000) = N'',      
	@STATEINFO Int = 0)          
AS          
IF EXISTS (SELECT TOP 1 RegisteredOwner FROM Setup WHERE RegisteredOwner = @CompanyID)          
BEGIN          
EXEC sp_acc_update_setup_Bunge       
	@COMPANYID,          
	@COMPANYNAME,             
	@BILLINGADDRESS,          
	@SHIPPINGADDRESS,          
	@TELEPHONE,          
	@FISCALYEAR,          
	@VOUCHERSTART,          
	@STREGN,          
	@STLABEL,          
	@CTREGN,          
	@CTLABEL,          
	@DL20,          
	@DL21,          
	@ORGANISATIONTYPE,          
	@NUMBEROFPARTNERS,          
	@DRAWINGACCOUNTFLAG,          
	@AUTHORISATIONCAPITAL,          
	@REGISTRATIONDATE,          
	@BUSINESSCOMDATE,          
	@TINNUMBER,          
	@SALESPORTAL,          
	@LOCALIZEDNAME,          
	@InstallationType,          
	@CompanyId_FXS,      
	@STATEINFO          
END          
ELSE          
BEGIN          
EXEC sp_acc_insert_Setup_Bunge       
	@COMPANYID,          
	@COMPANYNAME,             
	@BILLINGADDRESS,          
	@SHIPPINGADDRESS,          
	@TELEPHONE,          
	@FISCALYEAR,          
	@VOUCHERSTART,          
	@STREGN,          
	@STLABEL,          
	@CTREGN,          
	@CTLABEL,          
	@DL20,          
	@DL21,          
	@ORGANISATIONTYPE,          
	@NUMBEROFPARTNERS,          
	@DRAWINGACCOUNTFLAG,          
	@AUTHORISATIONCAPITAL,          
	@REGISTRATIONDATE,          
	@BUSINESSCOMDATE,          
	@TINNUMBER,          
	@SALESPORTAL,          
	@LOCALIZEDNAME,          
	@InstallationType,          
	@CompanyId_FXS,      
	@STATEINFO          
END          
