CREATE Procedure SP_ACC_RPT_RATIOSDRILLDOWN  
(  
 	@FROMDATE DATETIME,  
	@TODATE   DATETIME,  
 	@RATIOID  nvarchar(50),  
	@DOCREF   INT,
	@DOCTYPE  INT,
	@MODE	  INT,
 	@GROUPID  INT = 0, --OPTIONAL
	@Info     nvarchar(4000)=Null,
	@State    Int=0,
	@Hide0BalAC Int =0
)  
AS  
	/*
		DECLARE NECESSARY VARIABLE
	*/
	SET DATEFORMAT DMY
 	DECLARE @TOTAL 			DECIMAL(18,6)
	DECLARE @COLORBLUE		INT
	DECLARE @VALUEOFGROUP1		DECIMAL(18,6)
	DECLARE @VALUEOFGROUP2		DECIMAL(18,6)
	DECLARE @GROSSPROFIT		DECIMAL(18,6)
	DECLARE @NETPROFIT		DECIMAL(18,6)
	DECLARE @GROSSLOSS		DECIMAL(18,6)
	DECLARE @NETLOSS		DECIMAL(18,6)
	DECLARE @NETSALES		DECIMAL(18,6)
	DECLARE @PERCENTAGE		nvarchar(250)
	DECLARE @GROSSPROFITROWNO	INT
	DECLARE @OPERATING_COST		DECIMAL(18,6)
	DECLARE @WORKINGCAPITAL 	DECIMAL(18,6)

	/*
		ASSIGN VALUES FOR THE ABOVE DECLARED VARIABLES [ IF NECESSARY ]
		NOTE : IF TRADING AND P&L A/C IS INVOLVED , THERE WILL DIFFERENT TEMP TABLES
			CREATED , COZ ITS NOT ALLOWING TO USE THE SAME NAME EVEN THOUGH ITS INSIDE 
			THE IF CONDITION
	*/

	SET @COLORBLUE = 	1 -- FOR TOTAL'S ETC -- WILL BE DISPLAYED IN BLUE IN FRONTEND

 	CREATE TABLE   #DRILLDOWNTABLE
		(
			ROWNUM 		INT IDENTITY(1,1),
			GROUPID 	INTEGER,
			GROUPNAME 	nvarchar(255),
			DEBIT 		DECIMAL(18,6),
			CREDIT 		DECIMAL(18,6),
			FROMDATE 	DATETIME,
			TODATE 		DATETIME,
			DOCREF 		INTEGER,
			DOCTYPE 	INTEGER,
			COLORINFO 	INTEGER,
			PERCENTAGE 	nvarchar(50),
		)          



 	CREATE TABLE   #TEMPREGISTER
		( 
			ROWNUM 		INT IDENTITY(1,1),
			GROUPID 	INTEGER,
			GROUPNAME 	nvarchar(255),
			DEBIT 		DECIMAL(18,6),
			CREDIT 		DECIMAL(18,6),
			FROMDATE 	DATETIME,
			TODATE 		DATETIME,
			DOCREF 		INTEGER,
			DOCTYPE 	INTEGER,
			COLORINFO 	INTEGER
		) 
         
 	TRUNCATE TABLE #TEMPREGISTER  
 	TRUNCATE TABLE #DRILLDOWNTABLE  

	IF ISNUMERIC(@RATIOID) = 0 
		BEGIN
			SET @RATIOID = 0
		END

--	IF @RATIOID = 0  
	IF @groupid <> 0 or @mode = 0
 		BEGIN  
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,@GROUPID,@DOCREF,@DOCTYPE,@MODE,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,CAST(ISNULL(DEBIT,0) AS INTEGER),CAST(ISNULL(CREDIT,0) AS INTEGER) ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
			/*
			IF @MODE = 3 -> ACCOUNTGROUP THEN RUN THE SQL ELSE THE PROCEDURE INTURN RETURNS
			A RESULT SET WHICH CAN BE USED TO DISPLAY
			*/
			IF @MODE = 3 
				BEGIN
				  If @Hide0BalAC = 0
				  Begin
					SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT,'', 
						'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						@FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				  End
				  Else
				  Begin
					SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT,'', 
						'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						@FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
					where ((Isnull(Debit,0) + Isnull(Credit,0)) > 0 or isnull(colorinfo,0) in (1,3))
				  End
				END
			GOTO SKIPIMMEDIATELY
 		END  
	IF @RATIOID = 1 /* CURRENT RATIO */  
		BEGIN  
			 /*
			  INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER
			 */
 			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Current Assets + Loans & Advances',Default),@COLORBLUE)
			 /*  
			  CURRENT RATIO ==> CURRENT ASSETS + LOANS & ADVANCES : CURRENTLIABILITIES + PROVISIONS  
			  ALL PARENTIDS ARE HARDCODED AS ITS KNOWN  
			 */  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
			 /*
			  IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
			 */
  			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
  			--INSERT INTO #TEMPREGISTER(GROUPNAME,COLORINFO) VALUES('Loans & Advances',@COLORBLUE)  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
			 /*
			  CALCULATE NET ASSETS AND INSERT A DUMMY ROW WITH THE COLORINFO
			 */
			 /*
			  CALCULATE % OF CURRENT ASSETS TO TOTAL
			 */
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL
			IF @VALUEOFGROUP1 < 0 --PUT THE DETAIL IN DEBIT SIDE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END
			ELSE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END

				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = CAST(ROUND((DEBIT * 100) / ABS(@TOTAL),2) AS nchar)
					WHERE GROUPID <> 0 AND DEBIT <> 0
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = CAST(ROUND(((CREDIT * 100) / ABS(@TOTAL) * -1),2) AS nchar)
					WHERE GROUPID <> 0 AND CREDIT <> 0
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL
			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			/*   
			TRUNCATE THE #TEMPREGISTER TABLE TO INSERT VALUES OF ANOTHER RATIOS  
			*/  
  			TRUNCATE TABLE #TEMPREGISTER  
			/*
			INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER OF NEXT RATIO
			*/
  			--INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES('CURRENT LIABILITIES',@COLORBLUE)
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Current Liabilities & Provisions',Default),@COLORBLUE)

		   	/*
		    IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
		   	*/
  			--DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
		   	/*
			INSERT A DUMMY ROW TO DIFFERENTIATE
		   	*/
  			--INSERT INTO #TEMPREGISTER(GROUPNAME) VALUES(NULL)  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,
				DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
		   	/*
		    CALCULATE NET ASSETS AND INSERT A DUMMY ROW WITH COLORINFO
		   	*/
			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2 = @TOTAL
			IF @VALUEOFGROUP2 < 0 --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),ABS(DEBIT-CREDIT),@COLORBLUE 
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO +VE TO AVOID RATIO COMING IN -VE
					*/
					SET @VALUEOFGROUP2 	= ABS(@TOTAL)
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),DEBIT-CREDIT,@COLORBLUE 
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS > 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO -VE TO AVOID RATIO COMING IN +VE
					*/
					SET @VALUEOFGROUP2 = @TOTAL * -1
				END

				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = CAST(ROUND((DEBIT * 100) / ABS(@TOTAL) * -1,2) AS nchar)
					WHERE GROUPID <> 0 AND DEBIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = CAST(ROUND(((CREDIT * 100) / ABS(@TOTAL) ),2) AS nchar)
					WHERE GROUPID <> 0 AND CREDIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL
			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
		   	/*
			CALCULATE THE RATIO WITH THE VALUES STORED IN 
			@VALUEOFGROUP1 AND @VALUEOFGROUP2
		   	*/
--			'Ratio Value' = SUBSTRING(CAST(ROUND(@VALUEOFGROUP1 / @VALUEOFGROUP2,2) AS nchar),1,PATINDEX('%.%',CAST(ROUND(@VALUEOFGROUP1 / @VALUEOFGROUP2,2) AS nchar)) + 2 )+ ' : 1','-1',@COLORBLUE
			IF @VALUEOFGROUP2 <= 0 
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE,GROUPID,COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default),'-1',@COLORBLUE
				END
			ELSE IF @VALUEOFGROUP1 <= 0
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE,GROUPID,COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default),'-1',@COLORBLUE
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE,GROUPID,COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = SUBSTRING(CAST(@VALUEOFGROUP1 / @VALUEOFGROUP2 AS nchar),1,PATINDEX(N'%.%',CAST(@VALUEOFGROUP1 / @VALUEOFGROUP2 AS nchar)) + 2 )+ N' : 1','-1',@COLORBLUE
				END

			/*
			SELECT THE DETAILS FROM DRILL DWON TABLE TO DISPLAY IN FRONT END
			*/
			--UPDATE #DRILLDOWNTABLE 
		  If @Hide0BalAC = 0
		  Begin
			SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT,
				'Percent(%)' = 
				CASE WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))= 0 		THEN  '0'
					 WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))<> 0 	THEN  SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 )
					 WHEN (LTRIM(RTRIM(GROUPID)) IS NULL ) OR GROUPID = 0 THEN ' '
					 ELSE PERCENTAGE END,
				'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				@FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
  			ORDER BY ROWNUM
		  End
		  Else
		  Begin
			SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT,
				'Percent(%)' = 
				CASE WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))= 0 		THEN  '0'
					 WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))<> 0 	THEN  SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 )
					 WHEN (LTRIM(RTRIM(GROUPID)) IS NULL ) OR GROUPID = 0 THEN ' '
					 ELSE PERCENTAGE END,
				'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				@FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
			Where ((Isnull(Debit,0) + Isnull(Credit,0)) > 0 or isnull(colorinfo,0) in (1,3))
  			ORDER BY ROWNUM
		  End
		END  
	ELSE IF @RATIOID = 2 /* QUICK RATIO */  
 		BEGIN  
			 /*
			  INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER
			 */
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Quick Assets',Default),@COLORBLUE)
	
			/*  
			QUICK RATIO ==> CURRENT ASSETS - CLOSING STOCK : CURRENTLIABILITIES + PROVISIONS  
			ALL PARENTIDS ARE HARDCODED AS THE ITS KNOWN  
			*/  
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
			/*
			IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
			IF GROUPID = 21 THEN ITS CLOSING STOCK WHICH IS NOT TO BE INCLUDED IN THIS
			*/
			DELETE FROM #TEMPREGISTER WHERE GROUPID IN (0 ,21)  
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			
			/*
			CALCULATE NET ASSETS AND INSERT A DUMMY ROW
			*/
			SELECT @TOTAL = DEBIT - CREDIT  FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL
			IF @VALUEOFGROUP1 < 0 --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),ABS(DEBIT-CREDIT) ,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END

			/*

			CALCULATE % OF CURRENT ASSETS TO TOTAL
			*/

				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((DEBIT * 100) / ABS(@TOTAL),2)
					WHERE GROUPID <> 0 AND DEBIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((CREDIT * 100) / ABS(@TOTAL) * -1 ,2)
					WHERE GROUPID <> 0 AND CREDIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL					
			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
	
			/*   
			TRUNCATE THE #TEMPREGISTER TABLE TO INSERT VALUES OF ANOTHER RATIOS  
			*/  
			TRUNCATE TABLE #TEMPREGISTER  	
			/*
			INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER OF NEXT RATIO
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Current Liabilities',Default),@COLORBLUE)
	
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			/*
			INSERT THE NET LIABILITIES FROM #TEMPREGISTER
			*/
			SELECT @TOTAL = DEBIT - CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2	= @TOTAL
			IF @VALUEOFGROUP2 < 0  --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO +VE TO AVOID RATIO COMING IN -VE
					*/
					SET @VALUEOFGROUP2 	= ABS(@TOTAL)
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO -VE TO AVOID RATIO COMING IN +VE
					*/
					SET @VALUEOFGROUP2 	= @TOTAL * -1
				END
			/*
			CALCULATE % OF CURRENT LIABILITIES TO TOTAL
			*/
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((DEBIT * 100) / ABS(@TOTAL) * -1,2)
					WHERE GROUPID <> 0 AND DEBIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((CREDIT * 100) / ABS(@TOTAL) ,2)
					WHERE GROUPID <> 0 AND CREDIT <> 0 AND 
					GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL
			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			IF @VALUEOFGROUP2 <= 0 
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE ,GROUPID , COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default),'-1',@COLORBLUE
				END
			ELSE IF @VALUEOFGROUP1 <= 0 
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE ,GROUPID , COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default),'-1',@COLORBLUE
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE ,GROUPID , COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = SUBSTRING(CAST(@VALUEOFGROUP1 / @VALUEOFGROUP2 AS nchar),1,PATINDEX(N'%.%',CAST(@VALUEOFGROUP1 / @VALUEOFGROUP2 AS nchar)) + 2 )+ N' : 1','-1',@COLORBLUE
				END	

			If @Hide0BalAC = 0
		  	Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT, 
					'Percent(%)' = 
					CASE WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))= 0 	THEN  '0'
						 WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))<> 0 	THEN  SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 )
						 WHEN (LTRIM(RTRIM(GROUPID)) IS NULL ) OR GROUPID = 0 THEN ' '
						 ELSE PERCENTAGE END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				ORDER BY ROWNUM
			End
			Else
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT, 
					'Percent(%)' = 
					CASE WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))= 0 	THEN  '0'
						 WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))<> 0 	THEN  SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 )
						 WHEN (LTRIM(RTRIM(GROUPID)) IS NULL ) OR GROUPID = 0 THEN ' '
						 ELSE PERCENTAGE END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				Where ((Isnull(Debit,0) + Isnull(Credit,0)) > 0 or isnull(colorinfo,0) in (1,3))
				ORDER BY ROWNUM
			End
		END  
	ELSE IF @RATIOID = 3
		BEGIN
			 /*
			  INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER
			 */
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookUpDictionaryItem('Borrowings Short Term / Long Term ',Default),@COLORBLUE)
			/*  
			DEBT EQUITY RATIO ==> SHORT TERM BORROWINGS + LOANS : CAPITAL ACCOUNTS
			ALL PARENTIDS ARE HARDCODED AS THE ITS KNOWN  
			*/  
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,6,0,0,3,@Info,@State
			/*
			IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
			*/
			--INSERT INTO #TEMPREGISTER(GROUPNAME,COLORINFO) VALUES('Loans (Long Term Liabilities)',@COLORBLUE)  
			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,3,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
	
			/*
			CALCULATE NET DEBT AND INSERT A DUMMY ROW
			*/
			SELECT @TOTAL = DEBIT - CREDIT  FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL
			IF @VALUEOFGROUP1 < 0 --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Debt',Default),ABS(DEBIT-CREDIT) ,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Debt',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END

			/*

			CALCULATE % OF CURRENT ASSETS TO TOTAL
			*/
			IF @TOTAL <> 0
				BEGIN
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((DEBIT * 100) / ABS(@TOTAL),2)
						WHERE GROUPID <> 0 AND DEBIT <> 0 AND 
						GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((CREDIT * 100) / ABS(@TOTAL) * -1,2)
						WHERE GROUPID <> 0 AND CREDIT <> 0 AND 
						GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL					
				END
			ELSE
				BEGIN
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0
				END
			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  

			/*   
			TRUNCATE THE #TEMPREGISTER TABLE TO INSERT VALUES OF ANOTHER RATIOS  
			*/  
			TRUNCATE TABLE #TEMPREGISTER  	
			/*
			INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER OF NEXT RATIO
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Capital Accounts',Default),@COLORBLUE)
	
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,1,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			/*
			INSERT THE NET Capital Accounts FROM #TEMPREGISTER
			*/
			SELECT @TOTAL = DEBIT - CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2	= @TOTAL
			IF @VALUEOFGROUP2 < 0  --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Capital Accounts',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CAPITAL ACCOUNTS IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO +VE TO AVOID RATIO COMING IN -VE
					*/
					SET @VALUEOFGROUP2 	= ABS(@TOTAL)
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Capital Accounts',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CAPITAL ACCOUNTS IS > 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO -VE TO AVOID RATIO COMING IN +VE
					*/
					SET @VALUEOFGROUP2 	= @TOTAL
				END

			/*
			CALCULATE % OF CURRENT LIABILITIES TO TOTAL
			*/
			IF @VALUEOFGROUP2 <> 0 
				BEGIN
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((DEBIT * 100) / ABS(@TOTAL) * -1,2)
						WHERE GROUPID <> 0 AND DEBIT <> 0 AND 
						GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = ROUND((CREDIT * 100) / ABS(@TOTAL) ,2)
						WHERE GROUPID <> 0 AND CREDIT <> 0 AND 
						GROUPID IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE LTRIM(RTRIM(PERCENTAGE)) = N'' OR PERCENTAGE IS NULL
				END
			ELSE
				BEGIN
					UPDATE #DRILLDOWNTABLE SET PERCENTAGE = 0 WHERE GROUPID 
					IN (SELECT DISTINCT GROUPID FROM #TEMPREGISTER)
				END

			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			/*
			IF VALUE OF ANY GROUP = 0 THEN RATIO = 0
			*/
			IF @VALUEOFGROUP2 <= 0 
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE ,GROUPID , COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default) ,'-1',@COLORBLUE
				END
			ELSE IF @VALUEOFGROUP1 <= 0
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE ,GROUPID , COLORINFO)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default) ,'-1',@COLORBLUE
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE (GROUPNAME , PERCENTAGE ,GROUPID , COLORINFO)				
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = SUBSTRING(CAST(@VALUEOFGROUP1 / @VALUEOFGROUP2 AS nchar),1,PATINDEX(N'%.%',CAST(@VALUEOFGROUP1 / @VALUEOFGROUP2 AS nchar)) + 2 )+ N' : 1','-1',@COLORBLUE
				END
			If @Hide0BalAC = 0
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT, 
					'Percent(%)' = 
					CASE WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))= 0 	THEN  '0'
						 WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))<> 0 	THEN  SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 )
						 WHEN (LTRIM(RTRIM(GROUPID)) IS NULL ) OR GROUPID = 0 THEN ' '
						 ELSE PERCENTAGE END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				ORDER BY ROWNUM
			End
			Else
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,'Credit'=CREDIT, 
					'Percent(%)' = 
					CASE WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))= 0 	THEN  '0'
						 WHEN GROUPID > 0 AND CAST(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 ) AS DECIMAL(18,6))<> 0 	THEN  SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',CAST(ROUND(CAST(PERCENTAGE AS DECIMAL(18,6)),2) AS nchar)) + 2 )
						 WHEN (LTRIM(RTRIM(GROUPID)) IS NULL ) OR GROUPID = 0 THEN ' '
						 ELSE PERCENTAGE END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				Where ((Isnull(Debit,0) + Isnull(Credit,0)) > 0 or isnull(colorinfo,0) in (1,3))
				ORDER BY ROWNUM
			End
		END
	ELSE IF @RATIOID = 4 OR @RATIOID = 5 OR @RATIOID = 6 
		BEGIN
			
			/*
				THIS ALSO REQUIRES A TEMP TABLE TO BE CREATED WITH 11 FIELDS EXCLUDING THE AUTO 
				INCREMENT FIELD.
				SO DROP THE TEMP TABLE WHICH IS CREATED IN THE BEGINING AND CREATE ANOTHER 
				TEMP TABLE WITH 12 FIELDS (11 + IDENTITY FIELDS)
				IF ITS CONSUMING TIME , PLS CHANGE THE LOGIC WHICH FITS FOR ALL RATIOS
			*/			
		 	CREATE TABLE   #DRILLDOWNTABLETEMP
				(
					ROWNUM 		INT IDENTITY(1,1),
					GROUPNAME 	nvarchar(255),
					DEBIT 		nvarchar(100),
					CREDIT 		nvarchar(100),
					dummy1		nvarchar(50),
					GROUPID 	INTEGER,
					FROMDATE 	DATETIME,
					TODATE 		DATETIME,
					DOCREF 		INTEGER,
					DOCTYPE 	INTEGER,
					COLORINFO1 	INTEGER,
					DUMMY2	 	nvarchar(50),
					COLORINFO2	INTEGER
				)
			INSERT INTO #DRILLDOWNTABLETEMP (GROUPNAME,DEBIT,CREDIT,dummy1,GROUPID,FROMDATE,
				TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMMY2,COLORINFO2)
			EXECUTE SP_ACC_RPT_TRADINGAC @FROMDATE,@TODATE,'3'
			SET @NETPROFIT = 0
			/*
				FIELD MAPPINGS :
					DUMMY1 GOES INTO CREDIT,
					DUMMY2 GOES INTO DUMMY1,
					AND REST AS IT IS			
					(ROUPNAME,AMOUNT,DUMMY1,ACCOUNTID,FROMDATE,TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMM2,COLORINFO2)
			*/
			/*
				INSERT INTO TEMP TABLE
			*/

			/*
			INSERT A DUMMY ROW WITH ONLY GROUP NAME AS RATIO
			*/
			INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME) VALUES(' ')
			/* THIS BLOCK CALCULATES THE RATIO TO DISPLAY AT THE END */
			UPDATE #DRILLDOWNTABLETEMP SET DEBIT = 0 WHERE DEBIT IS NULL AND GROUPID >= 1
			UPDATE #DRILLDOWNTABLETEMP SET CREDIT = 0 WHERE CREDIT IS NULL AND GROUPID >= 1
				IF @RATIOID = 4 -- ITS A GROSS LOSS/ PROFIT RATIO SO GET THE GROSS LOSS / PROFIT
					BEGIN
						/* DELETE THE ROWS WHOSE ROW NO IS GREATER THAN THE @GROSSPROFITROWNO 
						COZ IN GROSS PROFIT RATIO , ONLY TRADING A/C HAS TO BE SHOWN 
						*/
						SELECT @GROSSPROFITROWNO = ROWNUM FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('P & L Account',Default))
						DELETE FROM #DRILLDOWNTABLETEMP WHERE ROWNUM >= @GROSSPROFITROWNO - 1
						SET @GROSSPROFIT = 0
						SET @GROSSLOSS	 = 0
						SELECT @GROSSPROFIT = cast(DEBIT as DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Gross Profit',Default))
						SELECT @GROSSLOSS   = cast(credit as DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Gross Loss',Default))
						SELECT @NETSALES	= CASE WHEN ISNULL(DEBIT,0) = 0 THEN CREDIT ELSE DEBIT END FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) =dbo.LookupDictionaryItem('Sales Account',Default)
						IF @GROSSPROFIT > 0 
							SELECT @PERCENTAGE 	= ROUND(((@GROSSPROFIT / @NETSALES ) * 100 ),2)
						ELSE

							SELECT @PERCENTAGE 	= ROUND(((@GROSSLOSS / @NETSALES ) * 100 * -1),2)


						/* INSERT THE RATIO CALCULATED */
						INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,COLORINFO2) VALUES(NULL,1)
						INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookUpDictionaryItem('Ratio',Default),@PERCENTAGE,@COLORBLUE,-1)
						If @Hide0BalAC = 0
						Begin
			 				SELECT 'Account/Group'= GROUPNAME,
								'Debit'= DEBIT ,'Credit' = CREDIT,
								'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then RTRIM(SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2)) + N' %' else '' end,
				 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
						End
						Else
						Begin
			 				SELECT 'Account/Group'= GROUPNAME,
								'Debit'= DEBIT ,'Credit' = CREDIT,
								'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then RTRIM(SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2)) + N' %' else '' end,
				 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
							Where ((Isnull(Cast(Debit as decimal(18,6)),0) + Isnull(Cast(Credit as decimal(18,6)),0)) > 0 or isnull(colorinfo2,0) in (1,3))
						End
					END
				ELSE IF @RATIOID = 5   -- ITS A NET LOSS/ PROFIT RATIO SO GET THE GROSS LOSS / PROFIT
					BEGIN
						SET @NETPROFIT 	= 0
						SET @NETLOSS 	= 0
 						SELECT @NETPROFIT 	= CAST(DEBIT AS DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Net Profit',Default))
						--SELECT @NETLOSS     = DEBIT FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Net Loss',Default))
						SELECT @NETLOSS     = CAST(credit AS DECIMAL(18,6)) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Net Loss',Default))
						--SELECT @NETSALES	= DEBIT FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = 'Sales Account'
						SELECT @NETSALES	= CASE WHEN ISNULL(DEBIT,0) = 0 THEN CREDIT ELSE DEBIT END FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = dbo.LookupDictionaryItem('Sales Account',Default)
						IF @NETPROFIT > 0 
							SELECT @PERCENTAGE 	= CAST(ROUND(((@NETPROFIT / @NETSALES ) * 100 ),2) AS nchar)
						ELSE
							SELECT @PERCENTAGE 	= CAST(ROUND(((@NETLOSS / @NETSALES ) * 100 * -1),2) AS nchar)

						/* INSERT THE RATIO CALCULATED */
						INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookUpDictionaryItem('Ratio',Default),@PERCENTAGE ,@COLORBLUE,-1)
						If @Hide0BalAC = 0
						Begin
			 				SELECT 'Account/Group'= GROUPNAME,
								'Debit'= DEBIT ,'Credit' = CREDIT,
								'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then RTRIM(SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2)) + N' %' else '' end,
				 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
						End
						Else
						Begin
			 				SELECT 'Account/Group'= GROUPNAME,
								'Debit'= DEBIT ,'Credit' = CREDIT,
								'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then RTRIM(SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2)) + N' %' else '' end,
				 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
							Where ((Isnull(Cast(Debit as decimal(18,6)),0) + Isnull(Cast(Credit as decimal(18,6)),0)) > 0 or isnull(colorinfo1,0) in (1,3))
						End
					END
				ELSE IF @RATIOID = 6   -- OPERATING COST RATIO NET SALES - NET PROFIT / NET SALES 8 100
					BEGIN
						/* IF ITS NET LOSS THEN THE RATIO HAS TO NOT COMPUTABLE*/
						SELECT @NETLOSS 	= CAST(CREDIT AS DECIMAL(18,6)) * -1 FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Net Loss',Default))
						SELECT @NETPROFIT 	= ABS(CAST(DEBIT AS DECIMAL(18,6))) FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) IN (dbo.LookUpDictionaryItem('Net Profit',Default))
						SELECT @NETSALES	= CASE WHEN ISNULL(DEBIT,0) = 0 THEN CAST(CREDIT AS DECIMAL(18,6))ELSE CAST(DEBIT AS DECIMAL(18,6)) END FROM #DRILLDOWNTABLETEMP WHERE LTRIM(RTRIM(GROUPNAME)) = dbo.LookupDictionaryItem('Sales Account',Default)
						IF @NETLOSS <> 0 
							BEGIN
								/* % HAS TO BE Not Calculatable */
								INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookUpDictionaryItem('Ratio',Default),0 ,@COLORBLUE,-1)
								If @Hide0BalAC = 0
  								Begin
						 			SELECT 'Account/Group'= GROUPNAME,
										'Debit'= DEBIT ,'Credit' = CREDIT,
										'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then dbo.LookupDictionaryItem('Not Calculatable',Default) else '' end,
						 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
								End
								Else
								Begin
						 			SELECT 'Account/Group'= GROUPNAME,
										'Debit'= DEBIT ,'Credit' = CREDIT,
										'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then dbo.LookupDictionaryItem('Not Calculatable',Default) else '' end,
						 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
									Where ((Isnull(Cast(Debit as decimal(18,6)),0) + Isnull(Cast(Credit as decimal(18,6)),0)) > 0 or isnull(colorinfo2,0) in (1,3))
								End
							END
						ELSE IF @NETPROFIT <> 0 
							BEGIN
								SELECT @PERCENTAGE 	= CAST(ROUND(((@NETSALES - @NETPROFIT / @NETSALES ) * 100 ),2) AS nchar)
								INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookUpDictionaryItem('Ratio',Default),@PERCENTAGE ,@COLORBLUE,-1)
								If @Hide0BalAC = 0
  								Begin
						 			SELECT 'Account/Group'= GROUPNAME,
										'Debit'= DEBIT ,'Credit' = CREDIT,
										'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then RTRIM(SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2)) + N' %'  else '' end,
						 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
								End
								Else
								Begin
						 			SELECT 'Account/Group'= GROUPNAME,
										'Debit'= DEBIT ,'Credit' = CREDIT,
										'Percent(%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then RTRIM(SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2)) + N' %'  else '' end,
						 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
									Where ((Isnull(Cast(Debit as decimal(18,6)),0) + Isnull(Cast(Credit as decimal(18,6)),0)) > 0 or isnull(colorinfo2,0) in (1,3))
								End
							END
						ELSE
							BEGIN
								/* % HAS TO BE Not Calculatable */
								INSERT INTO #DRILLDOWNTABLETEMP(GROUPNAME,DUMMY1,COLORINFO2,GROUPID ) VALUES(dbo.LookUpDictionaryItem('Ratio',Default),0 ,@COLORBLUE,-1)
								If @Hide0BalAC = 0
								Begin
						 			SELECT 'Account/Group'= GROUPNAME,
										'Debit'= DEBIT ,'Credit' = CREDIT,
										'Percent{%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then dbo.LookupDictionaryItem('Not Calculatable',Default) else '' end,
						 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
								End
								Else
								Begin
						 			SELECT 'Account/Group'= GROUPNAME,
										'Debit'= DEBIT ,'Credit' = CREDIT,
										'Percent{%)' = CASE when groupname = dbo.LookUpDictionaryItem('Ratio',Default) then dbo.LookupDictionaryItem('Not Calculatable',Default) else '' end,
						 				 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
						 			     @FROMDATE,@TODATE,DOCREF,DOCTYPE,colorinfo1,colorinfo2 FROM #DRILLDOWNTABLETEMP
									Where ((Isnull(Cast(Debit as decimal(18,6)),0) + Isnull(Cast(Credit as decimal(18,6)),0)) > 0 or isnull(colorinfo2,0) in (1,3))
								End
							END  
					END
			DROP TABLE #DRILLDOWNTABLETEMP
		END
	ELSE IF @RATIOID = 7 
		BEGIN
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookUpDictionaryItem('Sundry Debtors',Default),@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,22,0,0,3,@Info,@State

  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			
			SET @VALUEOFGROUP1	= @TOTAL
			IF @VALUEOFGROUP1 < 0 --PUT THE DETAIL IN DEBIT SIDE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sundry Debtors',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END
			ELSE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sundry Debtors',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END
			/*INSERT A DUMMY ROW*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(NULL)
			/* INSERT THE DETAILS OF SALES ACCOUNT */
			TRUNCATE TABLE #TEMPREGISTER 
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookUpDictionaryItem('Sales',Default),@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,28,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0 AND ROWNUM  = (SELECT MAX(ROWNUM) FROM #TEMPREGISTER)
			
			SET @VALUEOFGROUP2	= @TOTAL
			IF @VALUEOFGROUP2 < 0 --PUT THE DETAIL IN DEBIT SIDE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sales',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0 AND ROWNUM  = (SELECT MAX(ROWNUM) FROM #TEMPREGISTER)
						SELECT @PERCENTAGE 	= CAST(ROUND(((@VALUEOFGROUP1 / ABS(@VALUEOFGROUP2) ) * DATEDIFF(DD,@FROMDATE,@TODATE) ),2) AS nchar)
				END
			ELSE IF @VALUEOFGROUP2 = 0 OR @VALUEOFGROUP1 = 0 
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sales',Default),0,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
						SET @PERCENTAGE 	= 0
				END
			ELSE 
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sales',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
						IF @VALUEOFGROUP1 < 0 
							SET @PERCENTAGE = 0 
						ELSE
							SELECT @PERCENTAGE 	= CAST(ROUND(((@VALUEOFGROUP1 / @VALUEOFGROUP2 ) * DATEDIFF(DD,@FROMDATE,@TODATE) ),2) AS nchar)

				END
			/* INSERT THE RATIO CALCULATED AND A DUMMY ROW*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(NULL)		
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,PERCENTAGE,COLORINFO,GROUPID ) VALUES(dbo.LookUpDictionaryItem('Ratio',Default),@PERCENTAGE ,@COLORBLUE,-1)			

			If @Hide0BalAC = 0
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,
					'Credit'=CREDIT,
						'Percent(%)'=
						CASE 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) <= 0 AND LTRIM(RTRIM(PERCENTAGE)) <> N'' THEN dbo.LookupDictionaryItem('Not Calculatable',Default) 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) > 0 THEN RTRIM(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',PERCENTAGE)+2)) + N' %'
						END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
			End
			Else
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,
					'Credit'=CREDIT,
						'Percent(%)'=
						CASE 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) <= 0 AND LTRIM(RTRIM(PERCENTAGE)) <> N'' THEN dbo.LookupDictionaryItem('Not Calculatable',Default) 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) > 0 THEN RTRIM(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',PERCENTAGE)+2)) + N' %'
						END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				Where ((Isnull(Debit,0) + Isnull(Credit,0)) > 0 or isnull(colorinfo,0) in (1,3))
			End
		END
	ELSE IF @RATIOID = 8 --WORKING CAPITAL TURN OVER NET SALES / WORKING CAPITAL TURNOVER
		BEGIN
			/* INSERT SALES DETAILS */
			TRUNCATE TABLE #TEMPREGISTER 
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) 
				VALUES(dbo.LookUpDictionaryItem('Sales',Default),@COLORBLUE)
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,28,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0 AND ROWNUM  = (SELECT MAX(ROWNUM) FROM #TEMPREGISTER)
			SET @NETSALES = @TOTAL
			IF @NETSALES < 0 --PUT THE DETAIL IN DEBIT SIDE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sales',Default),ABS(@NETSALES),@COLORBLUE
					SET @NETSALES = @NETSALES * -1
				END  
			ELSE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Sales',Default),@NETSALES,@COLORBLUE
				END
		     /* INSERT THE CURRENT ASSETS AND CURRENT LIABILITIES GROUP */
			 /*
			 INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER
			 */
			TRUNCATE TABLE #TEMPREGISTER
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(NULL)
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Working Capital',Default),1)
 			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Current Assets + Loans & Advances',Default),@COLORBLUE)
			 /*  
			  CURRENT RATIO ==> CURRENT ASSETS + LOANS & ADVANCES : CURRENTLIABILITIES + PROVISIONS  
			  ALL PARENTIDS ARE HARDCODED AS ITS KNOWN  
			 */  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
			 /*
			  IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
			 */
  			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
			 /*
			  CALCULATE NET ASSETS AND INSERT A DUMMY ROW WITH THE COLORINFO
			 */
			 /*
			  CALCULATE % OF CURRENT ASSETS TO TOTAL
			 */
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL
			IF @VALUEOFGROUP1 < 0 --PUT THE DETAIL IN DEBIT SIDE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END  
			ELSE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
			  			SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END

			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
			/*   
			TRUNCATE THE #TEMPREGISTER TABLE TO INSERT VALUES OF ANOTHER RATIOS  
			*/  
  			TRUNCATE TABLE #TEMPREGISTER  
			/*
			INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER OF NEXT RATIO
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('Current Liabilities & Provisions',Default),@COLORBLUE)

		   	/*
		    IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
		   	*/
  			--DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
		   	/*
			INSERT A DUMMY ROW TO DIFFERENTIATE
		   	*/
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLE (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO ,PERCENTAGE)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,
				DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
		   	/*
		    CALCULATE NET ASSETS AND INSERT A DUMMY ROW WITH COLORINFO
		   	*/
			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP2 = @TOTAL
			IF @VALUEOFGROUP2 < 0 --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,CREDIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),ABS(DEBIT-CREDIT),@COLORBLUE 
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO +VE TO AVOID RATIO COMING IN -VE
					*/
					SET @VALUEOFGROUP2 	= ABS(@TOTAL)
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),DEBIT-CREDIT,@COLORBLUE 
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS > 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO -VE TO AVOID RATIO COMING IN +VE
					*/
					SET @VALUEOFGROUP2 = @TOTAL * -1
				END

			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME) VALUES(' ')  
		   	/*
			CALCULATE THE RATIO WITH THE VALUES STORED IN 
			@VALUEOFGROUP1 AND @VALUEOFGROUP2
		   	*/
			SET @WORKINGCAPITAL = @VALUEOFGROUP1 - @VALUEOFGROUP2
			IF @WORKINGCAPITAL <= 0 OR @NETSALES <= 0
				BEGIN
					SET @PERCENTAGE = 0
				END
			ELSE
				BEGIN
					SET @PERCENTAGE = ROUND(@NETSALES / @WORKINGCAPITAL,2)
				END

			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,DEBIT,COLORINFO)
			VALUES(dbo.LookUpDictionaryItem('Net Working Capital',Default),@WORKINGCAPITAL,1)

			/*insert DUMMY ROW */
			INSERT INTO #DRILLDOWNTABLE(GROUPNAME)VALUES(NULL)

			INSERT INTO #DRILLDOWNTABLE(GROUPNAME,PERCENTAGE,COLORINFO,GROUPID) 
			VALUES(dbo.LookUpDictionaryItem('Ratio',Default),@PERCENTAGE,1,-1)

			If @Hide0BalAC = 0
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,
					'Credit'=CREDIT ,
					'Percent(%)'=
						CASE 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) <= 0 AND LTRIM(RTRIM(PERCENTAGE)) <> N'' THEN dbo.LookupDictionaryItem('Not Calculatable',Default) 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) > 0 THEN RTRIM(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',PERCENTAGE)+2)) + N' : 1'
							ELSE ''
						END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
					 @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
			End
			Else
			Begin
				SELECT 'Account/Group'= GROUPNAME,'Debit'=DEBIT,
					'Credit'=CREDIT ,
					'Percent(%)'=
						CASE 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) <= 0 AND LTRIM(RTRIM(PERCENTAGE)) <> N'' THEN dbo.LookupDictionaryItem('Not Calculatable',Default) 
							WHEN GROUPNAME = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(PERCENTAGE AS DECIMAL(18,6)) > 0 THEN RTRIM(SUBSTRING(PERCENTAGE,1,PATINDEX(N'%.%',PERCENTAGE)+2)) + N' : 1'
							ELSE ''
						END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
					 @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO,COLORINFO FROM #DRILLDOWNTABLE  
				Where ((Isnull(Debit,0) + Isnull(Credit,0)) > 0 or isnull(colorinfo,0) in (1,3))
			End
		END
	ELSE IF @RATIOID = 9 -- RETURN ON INVESTMENT (NET PROFIT / CAPITAL * 100)
		BEGIN
		 	CREATE TABLE   #DRILLDOWNTABLETEMP1
				(
					ROWNUM 		INT IDENTITY(1,1),
					GROUPNAME 	nvarchar(255),
					DEBIT 		nvarchar(100),
					CREDIT 		nvarchar(100),
					dummy1		nvarchar(50),
					GROUPID 	INTEGER,
					FROMDATE 	DATETIME,
					TODATE 		DATETIME,
					DOCREF 		INTEGER,
					DOCTYPE 	INTEGER,
					COLORINFO1 	INTEGER,
					DUMMY2	 	nvarchar(50),
					COLORINFO2	INTEGER
				)
			INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME,DEBIT,CREDIT,dummy1,GROUPID,FROMDATE,
				TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMMY2,COLORINFO2)
			EXECUTE SP_ACC_RPT_TRADINGAC @FROMDATE,@TODATE,'3'
			SET @NETPROFIT = 0
			SELECT @NETPROFIT = ISNULL(DEBIT,0) FROM #DRILLDOWNTABLETEMP1 WHERE GROUPNAME  = dbo.LookUpDictionaryItem('Net Profit',Default)

			/*INSERT A DUMMY ROW*/
			INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME) VALUES(NULL)
			INSERT INTO #DRILLDOWNTABLETEMP1(GROUPNAME,COLORINFO2) VALUES(dbo.LookUpDictionaryItem('Capital Accounts',Default),@COLORBLUE)
	
			/* insert CAPITAL ACCOUNTS */
			TRUNCATE TABLE #TEMPREGISTER
			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,1,0,0,3,@Info,@State
			INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO2 ,DUMMY2)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,
				TODATE ,DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER  ORDER BY ROWNUM
			/*

			INSERT THE NET Capital Accounts FROM #TEMPREGISTER
			*/
			SELECT @TOTAL = DEBIT - CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
				SET @VALUEOFGROUP2	= @TOTAL
			IF @VALUEOFGROUP2 < 0  --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP1(GROUPNAME,CREDIT,COLORINFO2) 
						SELECT dbo.LookUpDictionaryItem('Net Capital Accounts',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CAPITAL ACCOUNTS IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO +VE TO AVOID RATIO COMING IN -VE
					*/
					SET @VALUEOFGROUP2 	= ABS(@TOTAL)
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP1(GROUPNAME,DEBIT,COLORINFO2) 
						SELECT dbo.LookUpDictionaryItem('Net Capital Accounts',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CAPITAL ACCOUNTS IS > 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO -VE TO AVOID RATIO COMING IN +VE
					*/
					SET @VALUEOFGROUP2 	= @TOTAL
				END

			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLETEMP1(GROUPNAME) VALUES(' ')  
			/*
			IF VALUE OF ANY GROUP = 0 THEN RATIO = 0
			*/
			
			UPDATE #DRILLDOWNTABLETEMP1 SET DEBIT = 0 WHERE DEBIT IS NULL AND GROUPID >= 1
			UPDATE #DRILLDOWNTABLETEMP1 SET CREDIT = 0 WHERE CREDIT IS NULL AND GROUPID >= 1

			IF @VALUEOFGROUP2 <= 0 
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME , DUMMY1 ,GROUPID , COLORINFO2)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default) ,'-1',@COLORBLUE
				END
			ELSE IF @NETPROFIT <= 0
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME , DUMMY1 ,GROUPID , COLORINFO2)
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 'Ratio Value' = dbo.LookUpDictionaryItem('Not Calculatable',Default) ,'-1',@COLORBLUE
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP1 (GROUPNAME , DUMMY1 ,GROUPID , COLORINFO2)				
					SELECT dbo.LookUpDictionaryItem('Ratio ',Default), 
					'Ratio Value' = SUBSTRING(CAST((@NETPROFIT / @VALUEOFGROUP2 * 100) AS nchar),1,PATINDEX(N'%.%',CAST(@NETPROFIT / @VALUEOFGROUP2 AS nchar)) + 2 )+ N' %','-1',@COLORBLUE
				END
			If @Hide0BalAC = 0
			Begin
				SELECT 'Account/Group'= GROUPNAME,
					'Debit'=DEBIT,'Credit'=CREDIT, 
					 'Percent(%)'= CASE WHEN LTRIM(RTRIM(GROUPNAME)) = dbo.LookUpDictionaryItem('Ratio',Default) THEN DUMMY1 ELSE '' END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO2,COLORINFO2 FROM #DRILLDOWNTABLETEMP1  
			End
			Else
			Begin
				SELECT 'Account/Group'= GROUPNAME,
					'Debit'=DEBIT,'Credit'=CREDIT, 
					 'Percent(%)'= CASE WHEN LTRIM(RTRIM(GROUPNAME)) = dbo.LookUpDictionaryItem('Ratio',Default) THEN DUMMY1 ELSE '' END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO2,COLORINFO2 FROM #DRILLDOWNTABLETEMP1  
				Where ((Isnull(Cast(Debit as Decimal(18,6)),0) + Isnull(Cast(Credit as Decimal(18,6)),0)) > 0 or isnull(colorinfo2,0) in (1,3))
			End
			DROP TABLE #DRILLDOWNTABLETEMP1
		END		
	ELSE IF @RATIOID = 10 --RETURN ON WORKING CAPITAL -> PROFIT / WORKING CAPITAL * 100
		BEGIN
			/*INSERT TADING A/C DETAILS */
		 	CREATE TABLE   #DRILLDOWNTABLETEMP2
				(
					ROWNUM 		INT IDENTITY(1,1),
					GROUPNAME 	nvarchar(255),
					DEBIT 		nvarchar(100),
					CREDIT 		nvarchar(100),
					dummy1		nvarchar(50),
					GROUPID 	INTEGER,
					FROMDATE 	DATETIME,
					TODATE 		DATETIME,
					DOCREF 		INTEGER,
					DOCTYPE 	INTEGER,
					COLORINFO1 	INTEGER,
					DUMMY2	 	nvarchar(50),
					COLORINFO2	INTEGER
				)
			INSERT INTO #DRILLDOWNTABLETEMP2 (GROUPNAME,DEBIT,CREDIT,dummy1,GROUPID,FROMDATE,
				TODATE,DOCREF,DOCTYPE,COLORINFO1,DUMMY2,COLORINFO2)
			EXECUTE SP_ACC_RPT_TRADINGAC @FROMDATE,@TODATE,'3'
			SET @NETPROFIT = 0
			SELECT @NETPROFIT = ISNULL(DEBIT,0) FROM #DRILLDOWNTABLETEMP2 WHERE GROUPNAME  = dbo.LookUpDictionaryItem('Net Profit',Default)
			UPDATE #DRILLDOWNTABLETEMP2 SET DEBIT = 0 WHERE DEBIT IS NULL AND GROUPID >= 1
			UPDATE #DRILLDOWNTABLETEMP2 SET CREDIT = 0 WHERE CREDIT IS NULL AND GROUPID >= 1

			/* INSERT WORKING CAPITAL DETAILS */
			TRUNCATE TABLE #TEMPREGISTER
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME) VALUES(NULL)
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,COLORINFO2) VALUES(dbo.LookUpDictionaryItem('Working Capital',Default),1)
 			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,COLORINFO2) VALUES(dbo.LookUpDictionaryItem('Current Assets + Loans & Advances',Default),@COLORBLUE)
			 /*  
			  CURRENT RATIO ==> CURRENT ASSETS + LOANS & ADVANCES : CURRENTLIABILITIES + PROVISIONS  
			  ALL PARENTIDS ARE HARDCODED AS ITS KNOWN  
			 */  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,17,0,0,3,@Info,@State
			 /*
			  IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
			 */
  			DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,16,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLETEMP2 (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO2 ,DUMMY1)
			SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				   DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
			 /*
			  CALCULATE NET ASSETS AND INSERT A DUMMY ROW WITH THE COLORINFO
			 */
			 /*
			  CALCULATE % OF CURRENT ASSETS TO TOTAL
			 */
  			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP1	= @TOTAL
			IF @VALUEOFGROUP1 < 0 --PUT THE DETAIL IN DEBIT SIDE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,CREDIT,COLORINFO2) 
			  			SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),ABS(DEBIT-CREDIT),@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END  
			ELSE
				BEGIN
		  			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,DEBIT,COLORINFO2) 
			  			SELECT dbo.LookUpDictionaryItem('Net Current Assets',Default),DEBIT-CREDIT,@COLORBLUE
						FROM #TEMPREGISTER WHERE GROUPID = 0
				END

			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME) VALUES(' ')  
			/*   
			TRUNCATE THE #TEMPREGISTER TABLE TO INSERT VALUES OF ANOTHER RATIOS  
			*/  
  			TRUNCATE TABLE #TEMPREGISTER  
			/*
			INSERT A BLANK ROW WITH ONLY GROUPNAME -> THIS IS FOR SPECIFYING HEADER OF NEXT RATIO
			*/
  			--INSERT INTO #DRILLDOWNTABLE(GROUPNAME,COLORINFO) VALUES(dbo.LookUpDictionaryItem('CURRENT LIABILITIES',Default),@COLORBLUE)
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,COLORINFO2) VALUES(dbo.LookUpDictionaryItem('Current Liabilities & Provisions',Default),@COLORBLUE)

  			--EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,56,0,0,3  
		   	/*
		    IF GROUPID = 0 THEN ITS TOTAL , SO DELETE IT
		   	*/
  			--DELETE FROM #TEMPREGISTER WHERE GROUPID = 0  
		   	/*
			INSERT A DUMMY ROW TO DIFFERENTIATE
		   	*/
  			--INSERT INTO #TEMPREGISTER(GROUPNAME) VALUES(NULL)  
  			EXEC SP_ACC_RPT_CALCULATEALLRATIOSDETAILS @FROMDATE,@TODATE,8,0,0,3,@Info,@State
  			INSERT INTO #DRILLDOWNTABLETEMP2 (GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,DOCREF ,
				DOCTYPE ,COLORINFO2 ,DUMMY1)
				SELECT GROUPID ,GROUPNAME ,DEBIT ,CREDIT ,FROMDATE ,TODATE ,
				DOCREF ,DOCTYPE ,COLORINFO ,'' FROM #TEMPREGISTER ORDER BY ROWNUM
		   	/*
		    CALCULATE NET ASSETS AND INSERT A DUMMY ROW WITH COLORINFO
		   	*/
			SELECT @TOTAL = DEBIT-CREDIT FROM #TEMPREGISTER WHERE GROUPID = 0
			SET @VALUEOFGROUP2 = @TOTAL
			IF @VALUEOFGROUP2 < 0 --PUT IT IN CREDIT SIDE
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,CREDIT,COLORINFO2) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),ABS(DEBIT-CREDIT),@COLORBLUE 
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS < 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO +VE TO AVOID RATIO COMING IN -VE
					*/
					SET @VALUEOFGROUP2 	= ABS(@TOTAL)
				END
			ELSE
				BEGIN
					INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,DEBIT,COLORINFO2) 
						SELECT dbo.LookUpDictionaryItem('Net Current Liabilities',Default),DEBIT-CREDIT,@COLORBLUE 
						FROM #TEMPREGISTER WHERE GROUPID = 0
					/*
					IF VALUE OF NET CURRENT LIABILITIES IS > 0 (DEFAULT IS < 0) THEN CHANGE IT
					TO -VE TO AVOID RATIO COMING IN +VE
					*/
					SET @VALUEOFGROUP2 = @TOTAL * -1
				END

			/*
			 INSERT A DUMMY ROW IN DRILL DOWN TO DIFFERENTIATE RATIO GROUPS			
			*/
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME) VALUES(' ')  
		   	/*
			CALCULATE THE RATIO WITH THE VALUES STORED IN 
			@VALUEOFGROUP1 AND @VALUEOFGROUP2
		   	*/

			SET @WORKINGCAPITAL = @VALUEOFGROUP1 - @VALUEOFGROUP2
				
			IF @WORKINGCAPITAL <= 0 OR @NETPROFIT = 0
				BEGIN
					SET @PERCENTAGE = 0
				END
			ELSE
				BEGIN
					SET @PERCENTAGE = ROUND(@NETPROFIT / @WORKINGCAPITAL * 100,2)
				END
			
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,DEBIT,COLORINFO2)
			VALUES(dbo.LookUpDictionaryItem('Net Working Capital',Default),@WORKINGCAPITAL,1)

			/*insert DUMMY ROW */
			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME)VALUES(NULL)

			INSERT INTO #DRILLDOWNTABLETEMP2(GROUPNAME,DUMMY1,COLORINFO2,GROUPID) 
			VALUES(dbo.LookUpDictionaryItem('Ratio',Default),@PERCENTAGE,1,-1)

			If @Hide0BalAC = 0
			Begin
				SELECT 'Account/Group'= GROUPNAME,
					'Debit'=DEBIT,'Credit'=CREDIT, 
					'Percent(%)'=
					 CASE 
						WHEN LTRIM(RTRIM(GROUPNAME)) = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(DUMMY1 AS DECIMAL(18,6)) > 0  THEN SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2) + N' %'
						WHEN LTRIM(RTRIM(GROUPNAME)) = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(DUMMY1 AS DECIMAL(18,6)) <= 0 THEN dbo.LookupDictionaryItem('Not Calculatable',Default)
					 	else ''
					 END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO2,COLORINFO2 FROM #DRILLDOWNTABLETEMP2
			End
			Else
			Begin
				SELECT 'Account/Group'= GROUPNAME,
					'Debit'=DEBIT,'Credit'=CREDIT, 
					'Percent(%)'=
					 CASE 
						WHEN LTRIM(RTRIM(GROUPNAME)) = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(DUMMY1 AS DECIMAL(18,6)) > 0  THEN SUBSTRING(DUMMY1,1,PATINDEX(N'%.%',DUMMY1)+2) + N' %'
						WHEN LTRIM(RTRIM(GROUPNAME)) = dbo.LookUpDictionaryItem('Ratio',Default) AND CAST(DUMMY1 AS DECIMAL(18,6)) <= 0 THEN dbo.LookupDictionaryItem('Not Calculatable',Default)
					 	else ''
					 END,
					 'Accountid/Groupid'= CASE WHEN GROUPID = 0 THEN '' ELSE GROUPID END,
				     @FROMDATE,@TODATE,DOCREF,DOCTYPE,COLORINFO2,COLORINFO2 FROM #DRILLDOWNTABLETEMP2
				Where ((Isnull(Cast(Debit as Decimal(18,6)),0) + Isnull(Cast(Credit  as Decimal(18,6)),0)) > 0 or isnull(colorinfo2,0) in (1,3))
			End
		END

/*
DROP THE TEMP TABLES AS NO LONGER REQUIRED
*/
SKIPIMMEDIATELY:


DROP TABLE #TEMPREGISTER  
DROP TABLE #DRILLDOWNTABLE    


