CREATE Procedure Sp_Acc_Insert_Setup_Bunge    
	(@COMPANYID NVARCHAR (50),        
	@COMPANYNAME NVARCHAR (255),           
	@BILLINGADDRESS NVARCHAR (255),        
	@SHIPPINGADDRESS NVARCHAR (255),        
	@TELEPHONE NVARCHAR (50),        
	@FISCALYEAR INT,        
	@VOUCHERSTART INT,        
	@STREGN nVarchar(50),        
	@STLABEL nVarchar(50),        
	@CTREGN nVarchar(50),        
	@CTLABEL nVarchar(50),        
	@DL20 nVarchar(50),        
	@DL21 nVarchar(50),        
	@ORGANISATIONTYPE INT = NULL,        
	@NUMBEROFPARTNERS INT = NULL,        
	@DRAWINGACCOUNTFLAG INT = NULL,        
	@AUTHORISATIONCAPITAL DECIMAL(18,6) = NULL,        
	@REGISTRATIONDATE DATETIME = NULL,        
	@BUSINESSCOMDATE DATETIME = NULL,        
	@TINNUMBER nVarchar(20) = N'',        
	@SALESPORTAL nVarchar(100) = N'',        
	@LOCALIZEDNAME nVarchar(255) = N'',        
	@InstallationType Int = 0,        
	@CompanyId_FXS nVarchar(2000) = N'',    
	@STATEINFO Int = 0)        
AS         
If @ORGANISATIONTYPE <= 2        
Begin        
INSERT INTO [Setup]        
	(RegisteredOwner,        
	OrganisationTitle,        
	BillingAddress,        
	ShippingAddress,        
	Telephone,        
	FiscalYear,        
	VoucherStart,        
	STRegn,        
	STLabel,        
	CTRegn,        
	CTLabel,        
	DL20,        
	DL21,        
	OrganisationType,        
	NumberofPartners,        
	DrawingAccountFlag,        
	TIN_Number,        
	SalesPortalIP,        
	LocalizedName,        
	InstallationType,        
	CugForumCode,    
	StateInfo)        
Values        
	(@COMPANYID,        
	@CompanyNAME,        
	@BILLINGADDRESS,        
	@SHIPPINGADDRESS,        
	@TELEPHONE,        
	@FISCALYEAR,        
	@VOUCHERSTART,        
	@STREGN,        
	@STLABEL,        
	@CTREGN,        
	@CTLABEL,        
	@DL20,        
	@DL21,              
	@ORGANISATIONTYPE,        
	@NUMBEROFPARTNERS,        
	@DRAWINGACCOUNTFLAG,        
	@TINNUMBER,        
	@SALESPORTAL,        
	@LOCALIZEDNAME,        
	@InstallationType,        
	@CompanyId_FXS,    
	@STATEINFO)        
End        
Else If @ORGANISATIONTYPE = 3        
Begin        
INSERT INTO [Setup]        
	(RegisteredOwner,        
	OrganisationTitle,        
	BillingAddress,        
	ShippingAddress,        
	Telephone,        
	FiscalYear,        
	VoucherStart,        
	STRegn,        
	STLabel,        
	CTRegn,        
	CTLabel,        
	DL20,        
	DL21,        
	OrganisationType,        
	AuthorisationCapital,        
	RegistrationDate,        
	TIN_Number,        
	SalesPortalIP,        
	LocalizedName,        
	InstallationType,        
	CugForumCode,    
	StateInfo)        
Values        
	(@COMPANYID,        
	@CompanyNAME,        
	@BILLINGADDRESS,        
	@SHIPPINGADDRESS,        
	@TELEPHONE,        
	@FISCALYEAR,        
	@VOUCHERSTART,        
	@STREGN,        
	@STLABEL,        
	@CTREGN,        
	@CTLABEL,        
	@DL20,        
	@DL21,              
	@ORGANISATIONTYPE,        
	@AUTHORISATIONCAPITAL,        
	@REGISTRATIONDATE,        
	@TINNUMBER,        
	@SALESPORTAL,        
	@LOCALIZEDNAME,        
	@InstallationType,        
	@CompanyId_FXS,    
	@STATEINFO)        
End        
Else If @ORGANISATIONTYPE = 4        
Begin        
	INSERT INTO [Setup]        
	(RegisteredOwner,        
	OrganisationTitle,        
	BillingAddress,        
	ShippingAddress,        
	Telephone,        
	FiscalYear,        
	VoucherStart,        
	STRegn,        
	STLabel,        
	CTRegn,        
	CTLabel,        
	DL20,        
	DL21,        
	OrganisationType,        
	AuthorisationCapital,        
	RegistrationDate,        
	BusinessCommencementDate,        
	TIN_Number,        
	SalesPortalIP,        
	LocalizedName,        
	InstallationType,        
	CugForumCode,    
	StateInfo)        
Values        
	(@COMPANYID,        
	@CompanyNAME,        
	@BILLINGADDRESS,        
	@SHIPPINGADDRESS,        
	@TELEPHONE,        
	@FISCALYEAR,        
	@VOUCHERSTART,        
	@STREGN,        
	@STLABEL,        
	@CTREGN,        
	@CTLABEL,        
	@DL20,        
	@DL21,              
	@ORGANISATIONTYPE,        
	@AUTHORISATIONCAPITAL,        
	@REGISTRATIONDATE,        
	@BUSINESSCOMDATE,        
	@TINNUMBER,        
	@SALESPORTAL,        
	@LOCALIZEDNAME,        
	@InstallationType,        
	@CompanyId_FXS,    
	@STATEINFO)        
End
