
CREATE PROCEDURE sp_compare_categories(@CATEGORY1 int, @CATEGORY2 int)
AS
DECLARE @TRACK_INVENTORY1 int
DECLARE @TRACK_INVENTORY2 int
DECLARE @PRICE_OPTION1 int
DECLARE @PRICE_OPTION2 int
SELECT @TRACK_INVENTORY1 = Track_Inventory, @PRICE_OPTION1 = Price_Option FROM ItemCategories WHERE CategoryID = @CATEGORY1
SELECT @TRACK_INVENTORY2 = Track_Inventory, @PRICE_OPTION2 = Price_Option FROM ItemCategories WHERE CategoryID = @CATEGORY2
IF @TRACK_INVENTORY1 = @TRACK_INVENTORY2 AND @PRICE_OPTION1 = @PRICE_OPTION2 SELECT 1 ELSE SELECT 0

