CREATE PROCEDURE sp_consolidate_invoice_detail(@InvoiceID INT, 
		@ProductCode NVARCHAR(15),
		@BatchCode INT,
		@BatchNumber nvarchar(128),
		@Quantity Decimal(18,6), 
		@SalePrice Decimal(18,6),
		@SaleTax Decimal(18,6),
		@DiscountPercentage Decimal(18,6),
		@DiscountValue Decimal(18,6), 
		@Amount Decimal(18,6),
		@PurchasePrice Decimal(18,6),
		@STPayable Decimal(18,6),
		@FlagWord int,
		@SaleID int,
		@PTR Decimal(18,6),
		@PTS Decimal(18,6),
		@MRP Decimal(18,6),
		@Tax_Description nvarchar(255),
		@CSTPayable Decimal(18,6),
		@TaxCode2 int,
		@TaxSuffered Decimal(18,6),
		@TaxSuffered2 Decimal(18,6),
		@Reason nvarchar(255))
AS
DECLARE @TAXID INT
DECLARE @REASONID INT
SET @TAXID = (SELECT Tax_Code FROM Tax WHERE Tax_Description = @Tax_Description)
SELECT @REASONID = MessageID FROM StockAdjustmentReason WHERE Message = @Reason
INSERT INTO 
InvoiceDetail  	(InvoiceID, 
		Product_Code, 
		Batch_Code, 
		Batch_Number,
		Quantity, 
		SalePrice,
		TaxCode,
		DiscountPercentage,
		DiscountValue,
		Amount,
		PurchasePrice,
		STPayable,
		FlagWord,
		SaleID,
		PTR,
		PTS,
		MRP,
		TaxID,
		CSTPayable,
		TaxCode2,
		TaxSuffered,
		TaxSuffered2,
		ReasonID)
VALUES		
		(@InvoiceID, 
		@ProductCode, 
		@BatchCode, 
		@BatchNumber,
		@Quantity, 
		@SalePrice,
		@SaleTax,
		@DiscountPercentage,
		@DiscountValue,
		@Amount,
		@PurchasePrice,
		@STPayable,
		@FlagWord,
		@SaleID,
		@PTR,
		@PTS,
		@MRP,
		@TAXID,
		@CSTPayable,
		@TaxCode2,
		@TaxSuffered,
		@TaxSuffered2,
		@REASONID)
