CREATE PROCEDURE sp_consolidate_bill_detail(@BILLID INT, 
		@ForumCode nvarchar(15),
		@Quantity Decimal(18,6), 
		@PurchasePrice Decimal(18,6), 
		@Amount Decimal(18,6),
		@TaxSuffered Decimal(18,6),
		@TaxAmount Decimal(18,6),
		@TaxCode int,
		@Discount Decimal(18,6),
		@Batch nvarchar(50),
		@Expiry datetime,
		@PKD datetime,
		@PTS Decimal(18,6),
		@PTR Decimal(18,6),
		@ECP Decimal(18,6))
AS
Declare @ProductCode nvarchar(20)
Select @ProductCode = Product_Code From Items Where Alias = @ForumCode
INSERT INTO 
BillDetail  	(BillID, 
		Product_Code, 
		Quantity, 
		PurchasePrice, 
		Amount,
		TaxSuffered,
		TaxAmount,
		TaxCode,
		Discount,
		Batch,
		Expiry,
		PKD,
		PTS,
		PTR,
		ECP)
VALUES		
		(@BILLID, 
		@ProductCode, 
		@Quantity, 
		@PurchasePrice, 
		@Amount,
		@TaxSuffered,
		@TaxAmount,
		@TaxCode,
		@Discount,
		@Batch,
		@Expiry,
		@PKD,
		@PTS,
		@PTR,
		@ECP)
