CREATE PROCEDURE SP_GET_RECCLAIMS      
AS      
SELECT       
CLR.CLAIMID, CLR.CLAIMDATE, CLR.Docserial,  CUS.COMPANY_NAME, CUS.CUSTOMERID, CLR.CLAIMVALUE ,GETDATE(), NULL, CLR.CLAIMID      
FROM claimsnotereceived CLR, CUSTOMER CUS       
WHERE CLR.CUSTOMERID = CUS.CUSTOMERID      
AND (IsNull(CLR.Status, 0) & 128) = 0      
ORDER BY CLR.CLAIMDATE      
  

