CREATE PROCEDURE sp_insert_item_ComboPack(@ITEM_CODE nvarchar(15),  
    @ITEM_NAME nvarchar(255),  
    @DESCRIPTION nvarchar(2000),  
    @CATEGORYID int,  
    @MANUFACTURERID nvarchar(15),  
    @BRANDID int,  
    @UOM int,  
    @PURCHASE_PRICE Decimal(18,6),  
    @SALE_PRICE Decimal(18,6),  
    @SALE_TAX Decimal(18,6),  
    @MRP Decimal(18,6),  
    @PREFERRED_VENDOR nvarchar(15),  
    @STOCK_NORM Decimal(18,6),  
    @MOQ Decimal(18,6),  
    @TRACK_BATCHES int,  
    @OPENING_STOCK Decimal(18,6),  
    @OPENING_STOCK_VALUE Decimal(18,6),  
    @SCHEMEID int,  
    @CONVERSION_FACTOR Decimal(18,6),  
    @CONVERSION_UNIT int,  
    @SALEID int,  
    @PURCHASED_AT int,  
    @COMPANY_PRICE Decimal(18,6),  
    @PTS Decimal(18,6),  
    @PTR Decimal(18,6),  
    @TAXSUFFERED Decimal(18,6),  
    @SOLDAS nvarchar(50),  
    @FORUMCODE nvarchar(20),  
    @REPORTINGUOM int,  
    @REPORTINGUNITS Decimal(18,6),  
    @TRACKPKD int,  
    @VIRTUAL_TRACK_BATCHES int,  
    @WAREHOUSEID nvarchar(20),  
    @ITEMCOMBO int,  
    @TRACKINVENTORYCOMBO int,
    @HYPERLINK nvarchar(256)= N'',
    @EXCISEDUTY int = 0,  
    @ADHOCAMOUNT Decimal(18,6) = 0,
    @Vat Int=0,
    @CollectTaxSuffered Int=0
)  
AS  
Update StockTransferOutDetailReceived Set Product_Code = @ITEM_CODE  
Where ForumCode = @FORUMCODE  
Update stock_request_detail_received Set Product_Code = @ITEM_CODE  
Where ForumCode = @FORUMCODE  
INSERT INTO Items(Product_Code,   
    ProductName,   
    Description,   
    CategoryID,  
    ManufacturerID,  
    BrandID,  
    UOM,  
    Purchase_Price,  
    Sale_Price,  
    Sale_Tax,  
    MRP,  
    Preferred_Vendor,  
    StockNorm,  
    MinOrderQty,  
    Track_Batches,  
    Opening_Stock,  
    Opening_Stock_Value,  
    SchemeID,  
    ConversionFactor,  
    ConversionUnit,   
    SaleID,  
    Purchased_At,  
    Company_Price,  
    PTS,  
    PTR,  
    ECP,  
    TaxSuffered,  
    SoldAs,  
    Alias,  
    ReportingUOM,  
    ReportingUnit,  
    TrackPKD,  
    Virtual_Track_Batches,  
    SupplyingBranch,  
    ModifiedDate,  
    ItemCombo,  
    TrackInventoryCombo,
    HYPERLINK,
    ExciseDuty,  
    AdhocAmount,
    Vat,
    CollectTaxSuffered
)  
VALUES (@ITEM_CODE,  
 @ITEM_NAME,  
 @DESCRIPTION,  
 @CATEGORYID,  
 @MANUFACTURERID,  
 @BRANDID,  
 @UOM,  
 @PURCHASE_PRICE,  
 @SALE_PRICE,  
 @SALE_TAX,  
 @MRP,  
 @PREFERRED_VENDOR,  
 @STOCK_NORM,  
 @MOQ,  
 @TRACK_BATCHES,  
 @OPENING_STOCK,  
 @OPENING_STOCK_VALUE,  
 @SCHEMEID,  
 @CONVERSION_FACTOR,  
 @CONVERSION_UNIT,  
 @SALEID,  
 @PURCHASED_AT,  
 @COMPANY_PRICE,  
 @PTS,  
 @PTR,  
 @SALE_PRICE,  
 @TAXSUFFERED,  
 @SOLDAS,  
 @FORUMCODE,  
 @REPORTINGUOM,  
 @REPORTINGUNITS,  
 @TRACKPKD,  
 @VIRTUAL_TRACK_BATCHES,  
 @WAREHOUSEID,  
 GetDate(),  
 @ITEMCOMBO,  
 @TRACKINVENTORYCOMBO,
 @HYPERLINK,
 @EXCISEDUTY,  
 @ADHOCAMOUNT,
 @Vat,
 @CollectTaxSuffered
)  






