
Create Procedure sp_Insert_ItemsReceivedDetail (@PartyID int,  
      @ForumCode Varchar(255),  
      @Product_Code Varchar(20),  
      @ProductName Varchar(255),  
      @Description Varchar(255),  
      @PurchasePrice Decimal(18,6),  
      @SalePrice Decimal(18,6),  
      @MRP Decimal(18,6),  
      @StockNorm Decimal(18,6),  
      @MOQ Decimal(18,6),  
      @TrackBatches Int,  
      @ConversionFactor Decimal(18,6),  
      @SaleID Int,  
      @StockistMargin Decimal(18,6),  
      @RetailerMargin Decimal(18,6),  
      @CompanyMargin Decimal(18,6),  
      @ReportingUnit Decimal(18,6),  
      @TrackPKD Int,  
      @VirtualTrackBatches Int,  
      @ManufacturerCode Varchar(255),  
      @ManufacturerName Varchar(255),  
      @BrandName Varchar(255),  
      @UOM Varchar(255),  
      @ConversionUnit Varchar(255),  
      @ReportingUOM Varchar(255),  
      @SoldAs Varchar(255),  
      @CategoryName Varchar(255),  
      @CategoryDesc Varchar(255),  
      @TrackInventory Int,  
      @PriceOption Int,  
      @STDesc Varchar(255),  
      @STLST Decimal(18,6),  
      @STCST Decimal(18,6),  
      @PTDesc Varchar(255),  
      @PTLST Decimal(18,6),  
      @PTCST Decimal(18,6),  
      @CategoryPropCount Int,  
      @ItemPropCount Int,  
      @CreationDate Datetime,   
      @ModifiedDate Datetime,  
      @Active Int,  
      @PTS Decimal(18,6),  
      @PTR Decimal(18,6),  
      @ECP Decimal(18,6),  
      @CompanyPrice Decimal(18,6),  
      @PurchasedAt Int,  
      @CatParent Varchar(255),  
      @HYPERLINK Varchar(256)='',  
      @VAT Int = 0,  
      @COLLECTTAXSUFFERED Int = 0,  
      @STLSTApplicableOn Int = 1,  
      @STLSTPartOff Decimal(18,6) = 100,  
      @STCSTApplicableOn Int = 1,  
      @STCSTPartOff Decimal(18,6) = 100,  
      @PTLSTApplicableOn Int = 1,  
      @PTLSTPartOff Decimal(18,6) = 100,  
      @PTCSTApplicableOn Int = 1,  
      @PTCSTPartOff Decimal(18,6) = 100,  
      @AdhocAmount Decimal(18,6) = 0,  
      @Taxinclusive int = 0,  
      @TaxinclusiveRate Decimal(18,6) = 0,
      @CaseUOM nvarchar(255) = '',
      @CaseConversion Decimal(18,6)= 0
      )  
  
As  
Insert into ItemsReceivedDetail (PartyID, ForumCode, Product_Code, ProductName,   
Description, PurchasePrice, SalePrice, MRP, StockNorm, MinOrderQty, Track_Batches,   
ConversionFactor, SaleID, StockistMargin, RetailerMargin, CompanyMargin, ReportingUnit,   
TrackPKD, Virtual_Track_Batches, ManufacturerCode, ManufacturerName, BrandName,   
UOM, ConversionUnit, ReportingUOM, SoldAs, CategoryName, CategoryDesc,   
TrackInventory, PriceOption, STDesc, STLST, STCST, PTDesc, PTLST, PTCST,   
CategoryPropCount, ItemPropCount, CreationDate, ModifiedDate, PTS, PTR, ECP,   
CompanyPrice, PurchasedAt, ParentCategory, Active, HYPERLINK, VAT, COLLECTTAXSUFFERED,  
STLSTApplicableOn, STLSTPartOff, STCSTApplicableOn, STCSTPartOff,   
PTLSTApplicableOn, PTLSTPartOff, PTCSTApplicableOn, PTCSTPartOff, AdhocAmount,  
Taxinclusive,TaxinclusiveRate, Case_UOM, Case_Conversion)  
Values  
(@PartyID, @ForumCode, @Product_Code, @ProductName, @Description, @PurchasePrice,  
@SalePrice, @MRP, @StockNorm, @MOQ, @TrackBatches,@ConversionFactor, @SaleID,  
@StockistMargin, @RetailerMargin, @CompanyMargin, @ReportingUnit, @TrackPKD,  
@VirtualTrackBatches, @ManufacturerCode, @ManufacturerName, @BrandName, @UOM,  
@ConversionUnit, @ReportingUOM, @SoldAs, @CategoryName, @CategoryDesc,  
@TrackInventory, @PriceOption, @STDesc, @STLST, @STCST, @PTDesc,  
@PTLST, @PTCST, @CategoryPropCount, @ItemPropCount, @CreationDate, @ModifiedDate, @PTS,   
@PTR, @ECP, @CompanyPrice, @PurchasedAt, @CatParent, @Active, @HYPERLINK, @VAT, @COLLECTTAXSUFFERED,  
@STLSTApplicableOn, @STLSTPartOff, @STCSTApplicableOn, @STCSTPartOff,   
@PTLSTApplicableOn, @PTLSTPartOff, @PTCSTApplicableOn, @PTCSTPartOff, @AdhocAmount,  
@Taxinclusive,@TaxinclusiveRate, @CaseUOM, @CaseConversion)  
Select @@Identity

