CREATE procedure sp_Insert_MissdItems_BillDetail(@Bill_ID int, @Product_Code as nvarchar(50),       
         @Qty Decimal(18,6),       
         @Price Decimal(18,6),       
         @Amount Decimal(18,6),       
         @BATCH_CODE nVarchar(255),      
         @TaxSuffered Decimal(18,6),       
         @TaxAmount Decimal(18,6),       
         @Taxcode int,       
         @DisPrice Decimal(18,6),      
         @Discount Decimal(18,6),      
         @Free Decimal(18,6),      
         @Batch nvarchar(255),      
         @Expiry datetime,      
         @PKD datetime,      
         @PTS Decimal(18,6),      
         @PTR Decimal(18,6),      
         @ECP Decimal(18,6),      
         @SpecialPrice Decimal(18,6),      
         @UOMID Int,      
         @UOMQty Decimal(18,6),      
         @UOMPrice Decimal(18,6),    
         @ComboId int=-123,  
         @ExciseDuty Decimal(18,6) = 0,  
     	 @PurchasePriceBeforeExciseAmount Decimal(18,6) = 0,  
         @ExciseID Int = 0,  
    	 @VAT int = 0,  
	     @Promotion int = 0,
	     @DiscPerUnit Decimal(18,6)=0,
	     @PFM  Decimal(18,6)=0,
	     @InvDiscPerc Decimal(18,6) = 0,
	     @InvDiscPerUnit Decimal(18,6) = 0,
	     @InvDiscAmt Decimal(18,6) = 0,
	     @OtherDiscPerc Decimal(18,6) = 0,
	     @OtherDiscPerUnit Decimal(18,6) = 0,
	     @OtherDiscAmt Decimal(18,6) = 0,
	     @DiscType Int = 0,
	     @NET_PTS Decimal(18,6) = 0,
	     @PTS_Margin Decimal(18,6) = 0
		,@MRPPerPack Decimal(18,6) = 0
		,@TOQ int=0
)      
as
Insert into BillDetail (BillID, Product_Code, Quantity, PurchasePrice,       
	 Amount, TaxSuffered, TaxAmount, TaxCode, Discount, Batch, Expiry, PKD, PTS, PTR, ECP,      
	 SpecialPrice, UOM, UOMQty, UOMPrice,ComboID, ExciseDuty,PurchasePriceBeforeExciseAmount,ExciseID,VAT,Promotion,DiscPerUnit,OrgPTS,
	 PFM, InvDiscPerc, InvDiscAmtPerUnit, InvDiscAmount, OtherDiscPerc, OtherDiscAmtPerUnit, OtherDiscAmount, DiscType, NetPTS, PTS_Margin, Missing, MRPPerPack,TOQ)      
	Values (@Bill_ID, @Product_Code, @Qty, @DisPrice, @Amount, @TaxSuffered, @TaxAmount,       
	 @TaxCode, @Discount, @Batch, @Expiry, @PKD, @PTS, @PTR, @ECP, @SpecialPrice, @UOMID,      
	 @UOMQty, @DisPrice,@ComboID, @ExciseDuty, @PurchasePriceBeforeExciseAmount, @ExciseID,@VAT,@Promotion,@DiscPerUnit,@Price,
     @PFM, @InvDiscPerc, @InvDiscPerUnit, @InvDiscAmt, @OtherDiscPerc, @OtherDiscPerUnit, @OtherDiscAmt, @DiscType, @NET_PTS, @PTS_Margin, 1, @MRPPerPack,@TOQ)
