
CREATE PROCEDURE sp_list_ClaimDocs(@VENDORID NVARCHAR(15), @FROMDATE DATETIME,
@TODATE DATETIME, @STATUS INT)

AS

SELECT ClaimID, ClaimDate FROM ClaimsNote
WHERE VendorID = @VENDORID 
AND Status & 32 = @STATUS
AND (ClaimDate BETWEEN @FROMDATE AND @TODATE)
ORDER BY ClaimDate


