
CREATE PROCEDURE sp_list_SClaimDocs(@VENDORID NVARCHAR(15), @FROMDATE DATETIME,
@TODATE DATETIME)

AS

SELECT ClaimID, ClaimDate FROM ClaimsNote
WHERE VendorID = @VENDORID 
AND Status & 32 = 1
AND (ClaimDate BETWEEN @FROMDATE AND @TODATE)
ORDER BY ClaimDate


