
CREATE PROCEDURE sp_update_Bank(@BANK_CODE NVARCHAR(50),
				@ACCOUNT_NUMBER NVARCHAR(50),
				@ACCOUNT_NAME NVARCHAR(50),
				@BRANCH_CODE NVARCHAR(50),
				@ACTIVE INTEGER)
AS
UPDATE Bank SET Active = @ACTIVE,
		BranchCode = @BRANCH_CODE,
		Account_Name = @ACCOUNT_NAME WHERE  BankCode = @BANK_CODE and Account_Number = @ACCOUNT_NUMBER
SELECT @@ROWCOUNT

