Create PROCEDURE [sp_update_Customer_Pidilite]                  
 (@CustomerID  [nvarchar](15),                  
  @Company_Name nvarchar(128),                  
  @ContactPerson [nvarchar](255),                  
  @CustomerCategory int,                  
  @BillingAddress [nvarchar](255),                  
  @ShippingAddress [nvarchar](255),                  
  @AreaID  [int],                  
  @CityID  [int],                  
  @StateID  [int],                  
  @CountryID  [int],                  
  @Phone  [nvarchar](50),                  
  @Email  [nvarchar](50),                  
  @Active  [int],                  
  @BeatID        [int],                  
  @Discount      Decimal(18,6),                  
  @DLNumber [nvarchar](50),                  
  @TNGSTNumber [nvarchar] (50),                  
  @CreditTerm int,                  
  @DLNumber21 [nvarchar] (50),                  
  @CSTNumber nvarchar(50),                  
  @CreditLimit Decimal(18,6),                  
  @AlternateCode nvarchar(20),                  
  @CreditRating nvarchar(50),                  
  @ChannelType int,                  
  @Locality int,                  
  @Payment_Mode int,        
  @AutoSC int =0,        
  @Password nvarchar(20)=N'',        
  @District int = 0,        
  @Town int = 0,        
  @AccountType int = 0,        
  @SequenceNo decimal(18,6)=0,        
  @TINNUMBER nvarchar(20) = N'',        
  @AlternateName nvarchar(250) = N'',        
  @TrackPoints decimal(18,6)=0,        
  @CollectedPoints decimal(18,6)=0,          
  @SubChannelID int=0,        
  @Potential nvarchar(100)=N'',        
  @MobileNumber nvarchar(50)=N'',        
  @Residence nvarchar(50)=N'',      
  @PinCode nvarchar(50)=N'',      
  @TradeCategoryID Int=Null,    
  @AddDiscInCollection Decimal(18,6) = 0)        
AS                       
if(@AutoSc=1)                 
begin          
 update auditmaster set customerID=@AlternateCode where customerID=(select alternatecode from customer where customerID=@CustomerID)                
 update itemclosingstock set customerID=@AlternateCode where customerID=(select alternatecode from customer where customerID=@CustomerID)                
 update sentinvoices set customerID=@AlternateCode where customerID=(select alternatecode from customer where customerID=@CustomerID)                 
end          
 UPDATE [Customer]                        
 SET          
 [Company_Name] = @Company_Name,                  
 [ContactPerson] = @ContactPerson,                  
 [CustomerCategory] = @CustomerCategory,                  
 [BillingAddress] = @BillingAddress,                  
 [ShippingAddress] = @ShippingAddress,                  
 [AreaID] = @AreaID,                  
 [CityID] = @CityID,                  
 [StateID] = @StateID,                  
 [CountryID] = @CountryID,                  
 [Phone] = @Phone,                  
 [Email] = @Email,                  
 [Active] = @Active,                  
 [Discount] = @Discount,                  
 [DLNumber] = @DLNumber,                  
 [TNGST] = @TNGSTNumber,                  
 [CreditTerm] = @CreditTerm,                  
 [DLNumber21] = @DLNumber21,                  
 [CST] = @CSTNumber,                  
 [CreditLimit] = @CreditLimit,                  
 [AlternateCode] = @AlternateCode,                  
 [CreditRating] = @CreditRating,                  
 [ChannelType] = @ChannelType,                  
 [Locality] = @Locality,                  
 [Payment_Mode] = @Payment_mode,        
 [Customer_Password] = @Password,        
 [District] = @District,        
 [TownClassify]= @Town,        
 [AccountType] = @AccountType,        
 [SequenceNo]=@SequenceNo,        
 [TIN_Number] = @TINNUMBER,        
 [Alternate_Name] = @AlternateName,        
 [TrackPoints]= @TrackPoints,        
 [CollectedPoints] = @CollectedPoints,        
 [SubChannelID] = @SubChannelID,     
 [Potential]=@Potential,        
 [MobileNumber] = @MobileNumber,        
 [Residence] = @Residence,      
 [PinCode] = @PinCode,      
 [TradeCategoryID] = @TradeCategoryID,    
 [AddCollDiscPercentage]=@AddDiscInCollection      
WHERE                   
 ( [CustomerID]  = @CustomerID)        
    
