CREATE PROCEDURE SPR_LIST_PURCHASE_TAX_SUMM_DETAIL
(@TAXID INTEGER,@FROMDATE DATETIME,@TODATE DATETIME)
AS

CREATE TABLE #PTAXSUBDET
(
TAXPERCENT Decimal(18,6),
TPAMT Decimal(18,6),----TOTAL PURCHASE AMOUNT
TPTAMT Decimal(18,6),---TOTAL PURCHASE TAX AMOUNT
TPRAMT Decimal(18,6),---TOTAL PURCHASE RETURN AMOUNT
TPRTAMT Decimal(18,6)---TOTAL PURCHASE RETURN TAX AMOUNT
)

INSERT INTO #PTAXSUBDET (TAXPERCENT,TPAMT,TPTAMT)

SELECT BILLDETAIL.TAXSUFFERED ,SUM(BILLDETAIL.AMOUNT)+ SUM(BILLDETAIL.TAXAMOUNT),SUM(BILLDETAIL.TAXAMOUNT)
		FROM BILLABSTRACT,VENDORS,BILLDETAIL
		WHERE (ISNULL(BILLABSTRACT.STATUS,0) & 128)=0
		AND BILLABSTRACT.VENDORID =VENDORS.VENDORID
		AND BILLDETAIL.BILLID = BILLABSTRACT.BILLID		
		AND VENDORS.LOCALITY=@TAXID
		AND BILLDATE BETWEEN @FROMDATE AND @TODATE
		GROUP BY BILLDETAIL.TAXSUFFERED

INSERT INTO #PTAXSUBDET (TAXPERCENT,TPRAMT,TPRTAMT)

SELECT ADJUSTMENTRETURNDETAIL.TAX, SUM(ADJUSTMENTRETURNDETAIL.TOTAL_VALUE),
	SUM(ADJUSTMENTRETURNDETAIL.TOTAL_VALUE - (ADJUSTMENTRETURNDETAIL.QUANTITY * ADJUSTMENTRETURNDETAIL.RATE)) FROM 
		ADJUSTMENTRETURNDETAIL, VOUCHERPREFIX BILLPREFIX,VOUCHERPREFIX ADJPREFIX,VENDORS,ADJUSTMENTRETURNABSTRACT
		 WHERE ADJUSTMENTRETURNDETAIL.ADJUSTMENTID=ADJUSTMENTRETURNABSTRACT.ADJUSTMENTID
			AND ADJUSTMENTDATE BETWEEN @FROMDATE AND @TODATE
		AND	ADJUSTMENTRETURNABSTRACT.VENDORID =VENDORS.VENDORID
		AND (ISNULL(ADJUSTMENTRETURNABSTRACT.STATUS,0)& 128)=0	
			AND BILLPREFIX.TRANID = 'BILL' AND
			ADJPREFIX.TRANID = 'STOCK ADJUSTMENT PURCHASE RETURN'		
		AND VENDORS.LOCALITY=@TAXID
		GROUP BY ADJUSTMENTRETURNDETAIL.TAX




SELECT "TaxPercent"= TAXPERCENT,"Tax Description"= TAXPERCENT, "Purchase Amt."=SUM(ISNULL(TPAMT,0)),"Tax Amt"=SUM(ISNULL(TPTAMT,0)), "Pur.Return Amt"=SUM(ISNULL(TPRAMT,0)),"Tax Amt."=SUM(ISNULL(TPRTAMT,0)),
"Net Purchase"=SUM(ISNULL(TPAMT,0))-SUM(ISNULL(TPRAMT,0)) ,
"Net Tax"=SUM(ISNULL(TPTAMT,0))- SUM(ISNULL(TPRTAMT,0)) FROM #PTAXSUBDET  GROUP BY TAXPERCENT


DROP TABLE #PTAXSUBDET








