CREATE PROCEDURE SPR_LIST_PURCHASE_TAX_SUMM
(@FROMDATE DATETIME,@TODATE DATETIME)    
AS    
CREATE TABLE #PTAXSUM    
(    
TAXID float, ---1 FOR LOCAL;2 FOR CENTRAL    
TPAMT Decimal(18,6),----TOTAL PURCHASE AMOUNT    
TPTAMT Decimal(18,6),---TOTAL PURCHASE TAX AMOUNT    
TPRAMT Decimal(18,6),---TOTAL PURCHASE RETURN AMOUNT    
TPRTAMT Decimal(18,6)---TOTAL PURCHASE RETURN TAX AMOUNT    
)    
INSERT INTO  #PTAXSUM (TAXID,TPAMT,TPTAMT)     
SELECT VENDORS.LOCALITY ,SUM(BILLDETAIL.AMOUNT)+ SUM (BILLDETAIL.TAXAMOUNT),SUM(BILLDETAIL.TAXAMOUNT)
		FROM BILLABSTRACT,VENDORS,BILLDETAIL
		WHERE (ISNULL(BILLABSTRACT.STATUS,0) & 128)=0
		AND BILLABSTRACT.VENDORID =VENDORS.VENDORID
		AND BILLDETAIL.BILLID = BILLABSTRACT.BILLID		
		AND BILLDATE BETWEEN @FROMDATE AND @TODATE
  GROUP BY VENDORS.LOCALITY    
    
    
INSERT INTO  #PTAXSUM (TAXID,TPRAMT,TPRTAMT)    
  SELECT VENDORS.LOCALITY, SUM(ADJUSTMENTRETURNDETAIL.TOTAL_VALUE),
	SUM(ADJUSTMENTRETURNDETAIL.TOTAL_VALUE - (ADJUSTMENTRETURNDETAIL.QUANTITY * ADJUSTMENTRETURNDETAIL.RATE)) FROM     
  ADJUSTMENTRETURNDETAIL, VOUCHERPREFIX BILLPREFIX,VOUCHERPREFIX ADJPREFIX,VENDORS,ADJUSTMENTRETURNABSTRACT    
   WHERE ADJUSTMENTRETURNDETAIL.ADJUSTMENTID=ADJUSTMENTRETURNABSTRACT.ADJUSTMENTID    
   AND ADJUSTMENTDATE BETWEEN @FROMDATE AND @TODATE  
   AND (ISNULL(ADJUSTMENTRETURNABSTRACT.STATUS,0)& 128)=0	
  AND ADJUSTMENTRETURNABSTRACT.VENDORID =VENDORS.VENDORID    
   AND BILLPREFIX.TRANID = 'BILL' AND    
   ADJPREFIX.TRANID = 'STOCK ADJUSTMENT PURCHASE RETURN'    
    
GROUP BY VENDORS.LOCALITY    
    
SELECT "Tax Type"= TAXID,"Tax Type"=CASE TAXID WHEN 1 THEN 'LOCAL' ELSE 'CENTRAL' END, "Purchase Amt."=SUM(ISNULL(TPAMT,0)),"Tax Amt"=SUM(ISNULL(TPTAMT,0)), "Pur.Return Amt"=SUM(ISNULL(TPRAMT,0)),"Tax Amt."=SUM(ISNULL(TPRTAMT,0)),  
"Net Purchase"=SUM(ISNULL(TPAMT,0))-SUM(ISNULL(TPRAMT,0)) ,  
"Net Tax"=SUM(ISNULL(TPTAMT,0))- SUM(ISNULL(TPRTAMT,0)) FROM #PTAXSUM  GROUP BY TAXID    
    
DROP TABLE #PTAXSUM







