IF EXISTS(SELECT Top 1 1 FROM sys.objects WHERE Name = N'spr_list_Invoicewise_Collections_ITC_Cash_Adv')
BEGIN
	DROP PROC [spr_list_Invoicewise_Collections_ITC_Cash_Adv]
END
GO
CREATE PROCEDURE [dbo].[spr_list_Invoicewise_Collections_ITC_Cash_Adv]  
(@FromDate datetime,@ToDate datetime)   As   Declare @CREDIT As NVarchar(50)   Declare @CASH As NVarchar(50)   Declare @CHEQUE As NVarchar(50)   Declare @DD As NVarchar(50)
Declare @CREDITCARD As NVarchar(50)   Declare @COUPON As NVarchar(50)   Declare @CREDITNOTE As NVarchar(50)   Declare @GIFTVOUCHER As NVarchar(50)   Declare @OTHERS As NVarchar(50)   Declare @INVOICE As NVarchar(50)   Declare @INVOICEAMENDMENT As NVarchar(50)   Declare @SalesReturn As NVarchar(50)   Declare @CreditNotes As NVarchar(50)   Declare @AdvanceCollection As NVarchar(50)   Declare @Invoices As NVarchar(50)   Declare @DebitNote As NVarchar(50)   Declare @RetailInvoice As NVarchar(50)   Declare @RetailInvoiceAmend As NVarchar(50)   Set @CREDIT = dbo.LookupDictionaryItem(N'Credit', Default)   Set @CASH = dbo.LookupDictionaryItem(N'Cash', Default)   Set @CHEQUE = dbo.LookupDictionaryItem(N'Cheque', Default)   Set @DD = dbo.LookupDictionaryItem(N'DD', Default)   Set @CREDITCARD = dbo.LookupDictionaryItem(N'Credit Card', Default)   Set @COUPON = dbo.LookupDictionaryItem(N'Coupon', Default)   Set @CREDITNOTE = dbo.LookupDictionaryItem(N'Credit Note', Default)   Set @GIFTVOUCHER = dbo.LookupDictionaryItem(N'Gift Voucher', Default)   Set @OTHERS = dbo.LookupDictionaryItem(N'Others', Default)   Set @INVOICE = dbo.LookupDictionaryItem(N'Invoice', Default)   Set @INVOICEAMENDMENT = dbo.LookupDictionaryItem(N'Invoice Amendment', Default)   Set @SalesReturn = dbo.LookupDictionaryItem(N'Sales Return', Default)   Set @CreditNotes = dbo.LookupDictionaryItem(N'Credit Note', Default)   Set @AdvanceCollection = dbo.LookupDictionaryItem(N'Collection Advance', Default)   Set @Invoices = dbo.LookupDictionaryItem(N'Invoices', Default)   Set @RetailInvoice = dbo.LookupDictionaryItem(N'Retail Invoice', Default)   Set @RetailInvoiceAmend = dbo.LookupDictionaryItem(N'Retail Invoice Sales Return', Default)   Set @DebitNote = dbo.LookupDictionaryItem(N'Debit Note', Default)   Select distinct COllections.SalesmanID, Salesman.Salesman_Name into #tempsal    from Collections ,Salesman   where COllections.SalesmanID = Salesman.SalesmanID   INSERT INTO #TEMPSAL    vALUES (0,'Others')   Select Collections.DocumentID,    "Collection ID" = Collections.FullDocID,    "Doc Ref"=Collections.DocReference,     "Collection Date" = Collections.DocumentDate,    "DOC ID" = dbo.lookupdictionaryitem('',Default),    "DOC Ref" =dbo.lookupdictionaryitem('',Default),   "DOC Date" = Collections.DocumentDate,     "Customer ID" = Collections.CustomerID,   "Company Name" = Customer.Company_Name,   "DocType"= dbo.lookupdictionaryitem('Collections Advance',Default),    "Salesman" = #tempsal.Salesman_name,    "Bill Value"=0,   "Bill Collection"=0,   "Bill Adjustment"=0,   "Advance Collection"=Collections.Balance,     --"Extra Charges"=0,   
"Discount Amount"=0,   "Bill Total Collection"=0,   "Payment Mode" = Case collections.PaymentMode         When 0 Then @CASH          When 1 Then @CHEQUE          When 2 Then @DD          When 3 Then @CREDITCARD          When 5 Then @COUPON           When 6 Then @CREDITNOTE      When 7 Then @GIFTVOUCHER      End   From Collections, Customer, #tempsal   where Collections.DocumentID not in  (Select Distinct(Collectionid)    From Collectiondetail  Where Collectionid in(Select DocumentID From Collections   Where Collections.DocumentDate between @FROMDATE And @TODATE And       (IsNull(Collections.Status,0) & 64) = 0 and     (IsNull(Collections.Status, 0) & 192) = 0 ))     and Collections.DocumentDate Between @FromDate And @ToDate And     Collections.CustomerID= Customer.CustomerID AND   Collections.SalesmanID=#tempsal.SalesmanID AND     Collections.PaymentModeID  >= 0 And   (IsNull(Collections.Status,0) & 64) = 0 and     (IsNull(Collections.Status,0) & 192) = 0    Drop table #tempSal
