Create Procedure spr_SalesPositionReport(
@MANUFACTURER nvarchar(255),
@FromDate DateTime,
@ToDate DateTime
)
As
--$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$--
--$ Log Information [This procedure used for Generating SPR Report                    $$--
--$ [Diff with dbo.spr_SalesPositionReport_XML.prc Procedure which is use for Uploding$$--
--$ 1. This can generated by 'Market SKU'.
--$ 2. SKU parameter removed and All 'System SKU' Validation also Removed.  
--$ 3. All Received Reports are consolidated in Market SKU Format.
--$ 4. In Received Reports Unknown item are not consolidated.
--$ 5. Two New column are handled for consolidation.
--$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$--
Declare @WDCode nVarchar(255)
Declare @WDDest nVarchar(255)
Declare @NEXT_DATE DateTime
Declare @CORRECTED_DATE DateTime
Declare @CompaniesToUploadCode nVarchar(255)
Declare @HName nVarchar(255)
Declare @LevelID int
Declare @SoldAs Int
Declare @SPRExist Int --For Consolidation
Declare @MSKU nVarchar(50)
Declare @SUBTOTAL nVarchar(50)
Declare @GRNTOTAL nVarchar(50)
Declare @Inc Int    
Declare @Count Int    
Declare @CategoryID Int  
Declare @CategoryName nVarchar(255)
Declare @BrchID nVarchar(255)
Declare @Quantity Decimal(18,6)    
Declare @Query nVarchar(4000)    
Declare @TabID Int
Declare @ConDynCol nVarchar(2000)
Declare @SqlQuery nVarchar(4000)
Declare @Delimeter as Char(1)    

Set @Delimeter=Char(15)    
  
Create Table #TempCategory (CategoryID Int, Status Int)

Create Table #TmpMfr (Mfr nVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS)
  
If @MANUFACTURER = '%'
 Insert Into #TmpMfr Select Manufacturer_Name From Manufacturer  
Else  
 Insert Into #TmpMfr Select * From DBO.sp_SplitIn2Rows(@MANUFACTURER,@Delimeter)  
  
Set @MSKU = dbo.LookupDictionaryItem(N'MarketSKU', Default)
Set @SUBTOTAL = dbo.LookupDictionaryItem(N'SubTotal:', Default)
Set @GRNTOTAL = dbo.LookupDictionaryItem(N'GrandTotal:', Default)

Select Top 1 @CompaniesToUploadCode=ForumCode From Companies_To_Upload  
Select Top 1 @WDCode = RegisteredOwner From Setup    
  
If @CompaniesToUploadCode='ITC001'  
 Set @WDDest= @WDCode  
Else  
Begin  
 Set @WDDest= @WDCode  
 Set @WDCode= @CompaniesToUploadCode  
End  

Create Table #TempConsolidate(
CategoryID NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
WDCode NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
WDDest NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
MarketSKU nVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
[Opl. SOH] Decimal(18, 6),
[Receipts + TRIN] Decimal(18, 6),
Sales Decimal(18, 6),
[D&D] Decimal(18, 6),
[Cl. SOH] Decimal(18, 6)
)

Create Table #TempTROUT(
IDS Int IDENTITY(1, 1),
CategoryID NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
WDCode NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,  
WDDest NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
CategoryName nVarChar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,    
BrchID nVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS,
Quantity Decimal(18, 6)
)

Create Table #TempExistColumn(ColumnName NVarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS)

SET @CORRECTED_DATE = CAST(DATEPART(dd, @TODATE) AS varchar) + '/'               
+ CAST(DATEPART(mm, @TODATE) as varchar) + '/'               
+ cast(DATEPART(yyyy, @TODATE) AS varchar)              

SET  @NEXT_DATE = CAST(DATEPART(dd, GETDATE()) AS varchar) + '/'               
+ CAST(DATEPART(mm, GETDATE()) as varchar) + '/'               
+ cast(DATEPART(yyyy, GETDATE()) AS varchar)  

Set @ConDynCol = ''    
Set @SqlQuery = ''
--For ITC we show item as Market SKU on 4th level category
Select @LevelID=Count(*) From ItemHierarchy
If @LevelID<>4 
GOTO EndProc

Set @LevelID=4
SELECT @HName=HierarchyName From ItemHierarchy Where HierarchyID = @LevelID
  
Exec GetLeafCategories @HName, '%'
--The below code is added specially for ITC..
--It's indented to add 4th level categories into #TempCategory table
Insert into #tempCategory 
Select CategoryID, 0 From ItemCategories Where [Level] in (@LevelID)
-----	    
--Manufacturer filter added
Select #tempCategory.CategoryID,Status into #tempCategory1 
from #tempCategory,Items,manufacturer 
Where #tempCategory.CategoryID=Items.CategoryID 
And Items.ManufacturerID=manufacturer.ManufacturerID
And Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)

Insert InTo #TempConsolidate
(CategoryID,WDCode,WDDest, MarketSKU,[Opl. SOH], [Receipts + TRIN], Sales, [D&D], [Cl. SOH])
Select 
"Category ID"= itc.CategoryID,
"WD Code"=@WDCode,"WD Dest"=@WDDest,
"Market SKU" = dbo.fn_NLevelCategory(itc.CategoryID, @LevelID),
"Opl. SOH" =
IsNull((Select Sum(IsNull(Opening_Quantity,0)) From OpeningDetails, Items, Manufacturer 
Where Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
And Items.ManufacturerID=Manufacturer.ManufacturerID 
And OpeningDetails.Product_Code = Items.Product_Code 
And Items.CategoryID = itc.CategoryID And Opening_Date = @FromDate), 0) -  

IsNull((Select Sum(IsNull(Damage_Opening_Quantity,0)) 
From OpeningDetails, Items, Manufacturer 
Where Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
And Items.ManufacturerID=Manufacturer.ManufacturerID 
And OpeningDetails.Product_Code = Items.Product_Code 
And Items.CategoryID = itc.CategoryID And Opening_Date = @FromDate), 0),
  
"Receipts + TRIN" =     
--Putchase  
ISNULL((SELECT SUM((QuantityReceived - QuantityRejected) + FreeQty)    
FROM GRNAbstract, GRNDetail, Items, Manufacturer     
WHERE GRNAbstract.GRNDate BETWEEN @FROMDATE AND @TODATE 
AND (GRNAbstract.GRNStatus & 64) = 0 And (GRNAbstract.GRNStatus & 32) = 0 
AND GRNAbstract.GRNID = GRNDetail.GRNID 
AND GRNDetail.Product_Code = Items.Product_Code 
AND Items.CategoryID = itc.CategoryID 
AND Manufacturer.Manufacturer_Name in
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
And Items.ManufacturerID=Manufacturer.ManufacturerID),0) + 
--TRIN  
IsNull((Select Sum(Quantity)     
From StockTransferInAbstract, StockTransferInDetail, Items, Manufacturer             
Where StockTransferInAbstract.DocumentDate Between @FromDate And @ToDate 
And StockTransferInAbstract.Status & 192 = 0              
And StockTransferInAbstract.DocSerial = StockTransferInDetail.DocSerial              
And StockTransferInDetail.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID
And Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
And Items.ManufacturerID=Manufacturer.ManufacturerID),0) -
--Purchase Return  
IsNull((Select Sum(Quantity)     
From AdjustmentReturnAbstract, AdjustmentReturnDetail, Items, Manufacturer              
Where AdjustmentReturnAbstract.AdjustmentDate Between @FromDate And @ToDate               
And IsNull(AdjustmentReturnAbstract.Status,0) & 192 = 0              
And AdjustmentReturnAbstract.AdjustmentID = AdjustmentReturnDetail.AdjustmentID              
And AdjustmentReturnDetail.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID
And Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
And Items.ManufacturerID=Manufacturer.ManufacturerID),0),
  
"Sales" = 
--Sales
ISNULL((SELECT SUM(Case When Quantity>0 Then Quantity Else 0 End) 
FROM InvoiceDetail, InvoiceAbstract, Items, Manufacturer
WHERE InvoiceAbstract.InvoiceDate BETWEEN @FROMDATE AND @TODATE
AND (InvoiceAbstract.Status & 128) = 0 AND (InvoiceAbstract.InvoiceType = 2) 
AND InvoiceAbstract.InvoiceID = InvoiceDetail.InvoiceID               
AND InvoiceDetail.Product_Code = Items.Product_Code 
AND Items.CategoryID = itc.CategoryID     
AND Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
AND Items.ManufacturerID=Manufacturer.ManufacturerID),0) + 
ISNULL((SELECT SUM(Quantity)               
FROM DispatchDetail, DispatchAbstract, Items, Manufacturer      
WHERE DispatchAbstract.DispatchDate BETWEEN @FROMDATE AND @TODATE 
AND Isnull(DispatchAbstract.Status, 0) & 64 = 0            
AND Isnull(DispatchAbstract.Status, 0) & 384 <> 384 
AND DispatchAbstract.DispatchID = DispatchDetail.DispatchID                
AND DispatchDetail.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID    
AND Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
AND Items.ManufacturerID=Manufacturer.ManufacturerID),0) - 
--Sales Return  (Trade Invoice Sales Return  + Retail Invoice Sales Return )
--Trade Invoice Sales Return  
(ISNULL((SELECT SUM(Quantity) FROM InvoiceDetail, InvoiceAbstract, Items, Manufacturer     
WHERE InvoiceAbstract.InvoiceDate BETWEEN @FROMDATE AND @TODATE
AND (InvoiceAbstract.InvoiceType = 4)               
AND (InvoiceAbstract.Status & 128) = 0               
AND (InvoiceAbstract.Status & 32) = 0              
AND InvoiceAbstract.InvoiceID = InvoiceDetail.InvoiceID               
AND InvoiceDetail.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID    
AND Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)  
AND Items.ManufacturerID=Manufacturer.ManufacturerID),0) + 
--Retail Invoice Sales Return  
ISNULL((SELECT SUM(Case When Quantity<0 Then Abs(Quantity) Else 0 End) 
FROM InvoiceDetail, InvoiceAbstract, Items, Manufacturer     
WHERE InvoiceAbstract.InvoiceDate BETWEEN @FROMDATE AND @TODATE
AND (InvoiceAbstract.InvoiceType = 2)               
AND (InvoiceAbstract.Status & 128) = 0               
AND InvoiceAbstract.InvoiceID = InvoiceDetail.InvoiceID     
AND InvoiceDetail.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID     
AND Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)  
AND Items.ManufacturerID=Manufacturer.ManufacturerID),0)),
    
"D&D" = 
ISNULL((SELECT SUM(Quantity) FROM InvoiceDetail, InvoiceAbstract, Items, Manufacturer       
WHERE InvoiceAbstract.InvoiceDate BETWEEN @FROMDATE AND @TODATE
AND (InvoiceAbstract.InvoiceType = 4)               
AND (InvoiceAbstract.Status & 128) = 0               
AND (InvoiceAbstract.Status & 32) <> 0              
AND InvoiceAbstract.InvoiceID = InvoiceDetail.InvoiceID               
AND InvoiceDetail.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID    
AND Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
AND Items.ManufacturerID=Manufacturer.ManufacturerID),0) + 

ISNULL((SELECT SUM(Quantity) 
FROM StockAdjustmentAbstract, StockAdjustment, Items, Manufacturer
WHERE StockAdjustmentAbstract.AdjustmentDate BETWEEN @FROMDATE AND @TODATE
AND (StockAdjustmentAbstract.AdjustmentType = 0)               
AND StockAdjustmentAbstract.AdjustmentID = StockAdjustment.SerialNo  
AND StockAdjustment.Product_Code = Items.Product_Code     
And Items.CategoryID = itc.CategoryID    
AND Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)  
AND Items.ManufacturerID=Manufacturer.ManufacturerID),0),
    
"Cl. SOH" =     
CASE 
When (@TODATE < @NEXT_DATE) THEN     
	ISNULL((Select Sum(IsNull(Opening_Quantity, 0)) 
  FROM OpeningDetails, Items, Manufacturer      
	WHERE Manufacturer.Manufacturer_Name in 
  (Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
	And Items.ManufacturerID=Manufacturer.ManufacturerID 
  And OpeningDetails.Product_Code = Items.Product_Code 
  And Items.CategoryID = itc.CategoryID 
  AND Opening_Date = DATEADD(dd, 1, @CORRECTED_DATE)), 0) -  
	
	ISNULL((Select Sum(IsNull(Damage_Opening_Quantity, 0)) 
  FROM OpeningDetails, Items, Manufacturer      
	WHERE Manufacturer.Manufacturer_Name in 
  (Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)  
	And Items.ManufacturerID=Manufacturer.ManufacturerID 
  And OpeningDetails.Product_Code = Items.Product_Code 
  And Items.CategoryID = itc.CategoryID 
  AND Opening_Date = DATEADD(dd, 1, @CORRECTED_DATE)), 0)
	
Else    
	ISNULL((SELECT SUM(Quantity) FROM Batch_Products, Items, Manufacturer      
	WHERE Manufacturer.Manufacturer_Name in 
  (Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
	And Items.ManufacturerID=Manufacturer.ManufacturerID 
  And Batch_Products.Product_Code = Items.Product_Code 
  And Items.CategoryID = itc.CategoryID And IsNull(Damage,0)=0), 0) +
	
	(SELECT ISNULL(SUM(Pending), 0) 
  FROM VanStatementDetail, VanStatementAbstract, Items, Manufacturer      
	WHERE Manufacturer.Manufacturer_Name in 
  (Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)  
	And Items.ManufacturerID=Manufacturer.ManufacturerID 
  And VanStatementAbstract.DocSerial = VanStatementDetail.DocSerial     
	AND (VanStatementAbstract.Status & 128) = 0 
  And VanStatementDetail.Product_Code = Items.Product_Code 
  And Items.CategoryID = itc.CategoryID 
  And VanStatementDetail.PurchasePrice <> 0)   +  
	
	(SELECT ISNULL(SUM(Pending), 0) 
  FROM VanStatementDetail, VanStatementAbstract, Items, Manufacturer      
	WHERE Manufacturer.Manufacturer_Name in 
  (Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)  
	And Items.ManufacturerID=Manufacturer.ManufacturerID 
  And VanStatementAbstract.DocSerial = VanStatementDetail.DocSerial               
	AND (VanStatementAbstract.Status & 128) = 0 
  And VanStatementDetail.Product_Code = Items.Product_Code 
  And	Items.CategoryID = itc.CategoryID 
  And VanStatementDetail.PurchasePrice = 0)    
End  
From ItemCategories itc
Where itc.CategoryID In (Select CategoryID From #tempCategory1)

--Add TransferOut Column dynamically
Insert InTo #TempTROUT
Select 
"CategoryID" = itc.CategoryID,
"WD Code" = @WDCode,
"WD Dest" = @WDCode,
"CategoryName" = dbo.fn_NLevelCategory(itc.CategoryID, @LevelID),
"BrchID" = 'TROUT - ' + WareHouse.ForumID,
"Quantity" = Sum(stod.Quantity) 
From StockTransferOutAbstract stoa, StockTransferOutDetail stod, ItemCategories itc,
Items, WareHouse, Manufacturer 
Where Manufacturer.Manufacturer_Name in 
(Select Mfr COLLATE SQL_Latin1_General_CP1_CI_AS From #TmpMfr)
And Items.ManufacturerID=Manufacturer.ManufacturerID 
And stoa.WareHouseID = WareHouse.WareHouseID 
And stoa.DocSerial = stod.DocSerial 
And stod.Product_Code = Items.Product_Code 
And Items.CategoryID = itc.CategoryID 
And stoa.DocumentDate Between @FromDate And @ToDate 
And stoa.Status & 192 = 0 
And itc.CategoryID In (Select CategoryID From #tempCategory1)
Group By itc.CategoryID, dbo.fn_NLevelCategory(itc.CategoryID, @LevelID), WareHouse.ForumID

Set @Inc = 1    
Select @Count = Count(*) From #TempTROUT

While @Inc <= @Count     
Begin    
	Select @CategoryID = CategoryID,
         @BrchID = BrchID, @Quantity = Quantity From #TempTROUT
	Where IDS = @Inc    
	If IsNull((Select Count(*) From #TempTROUT Where BrchID = @BrchID and ids < @Inc), 0) < 1    
	Begin    
		If Not Exists (Select * From #TempExistColumn Where ColumnName='['+@BrchID+']')
		Begin
			SET @Query = 'ALTER TABLE #TempConsolidate Add [' + @BrchID +  '] Decimal(18, 6)'    
			EXEC sp_executesql @Query    
			Insert Into #TempExistColumn (ColumnName) Values ('['+@BrchID+']') 
		End
	End
	Set @Query = 'Update #TempConsolidate Set [' + @BrchID + '] = ' + Cast(@Quantity As nVarchar) + ' Where CategoryID= ' + Cast(@CategoryID As nVarchar) 
	EXEC sp_executesql @Query
	Set @Inc = @Inc + 1
End

If (Select Count(*) From Reports Where ReportName = 'Sales Position Report' And ParameterID in   
(Select ParameterID From dbo.GetReportParametersForSPR('Sales Position Report') Where   
FromDate = dbo.StripDateFromTime(@FromDate) And ToDate = dbo.StripDateFromTime(@ToDate)) )>=1
Begin  
	set @SPRExist = 1
	Insert Into #TempConsolidate 
  (CategoryID, WDCode, WDDest, MarketSKU, [Opl. SOH], [Receipts + TRIN],
   Sales, [D&D], [Cl. SOH])  
	Select dbo.GetCategorieID(ReportAbstractReceived.Field3),"WD Code" = Field1,
  "WD Dest" = Field2,
  "MarketSKU" = Field3,
	"Opl. SOH" = Cast(Cast(Field4 as float)as Decimal(18,6)),
	"Receipts + TRIN" = Cast(Cast(Field5 as float)as Decimal(18,6)),
	"Sales" = Cast(Cast(Field6 as float)as Decimal(18,6)),
	"[D&D]" = Cast(Cast(Field7 as float)as Decimal(18,6)),
	"[Cl. SOH]" = Cast(Cast(Field8 as float)as Decimal(18,6))
	From Reports, ReportAbstractReceived
	Where Reports.ReportID in
	(Select Distinct ReportID From Reports
	Where ReportName = 'Sales Position Report'
	And ParameterID in (Select ParameterID From dbo.GetReportParametersForSPR('Sales Position Report') Where
	FromDate = dbo.StripDateFromTime(@FromDate) And ToDate = dbo.StripDateFromTime(@ToDate)))
	And ReportAbstractReceived.ReportID = Reports.ReportID
	and ReportAbstractReceived.Field9 <> 'SKU'
	and ReportAbstractReceived.Field3 <> @MSKU
	and ReportAbstractReceived.Field1 <> @SUBTOTAL
	and ReportAbstractReceived.Field1 <> @GRNTOTAL

	Insert Into #TempConsolidate 
  (CategoryID, WDCode, WDDest, MarketSKU, [Opl. SOH], [Receipts + TRIN],
   Sales, [D&D], [Cl. SOH])  
	Select ItemCategories.CategoryID, "WD Code" = Max(Field1),
  --dbo.GetCategorieID(ReportAbstractReceived.Field3)
  "WD Dest" = Max(Field2),
  "MarketSKU" = ItemCategories.Category_Name ,  --Field3,
	"Opl. SOH" = Sum( Cast(Cast(Field4 as float)as Decimal(18,6)) ),
	"Receipts + TRIN" = Sum( Cast(Cast(Field5 as float)as Decimal(18,6)) ),
	"Sales" = Sum( Cast(Cast(Field6 as float)as Decimal(18,6)) ),
	"[D&D]" = Sum( Cast(Cast(Field7 as float)as Decimal(18,6)) ),
	"[Cl. SOH]" = Sum( Cast(Cast(Field8 as float)as Decimal(18,6)) )
	From Reports, ReportAbstractReceived, Items , ItemCategories
	Where Items.Product_Code = LTrim(RTrim(ReportAbstractReceived.Field3))
  And ItemCategories.CategoryID = Items.CategoryID
  And Reports.ReportID in
	(Select Distinct ReportID From Reports
	Where ReportName = 'Sales Position Report'
	And ParameterID in (Select ParameterID From dbo.GetReportParametersForSPR('Sales Position Report') Where
	FromDate = dbo.StripDateFromTime(@FromDate) And ToDate = dbo.StripDateFromTime(@ToDate)))
	And ReportAbstractReceived.ReportID = Reports.ReportID
	and ReportAbstractReceived.Field9 = 'SKU'
	and ReportAbstractReceived.Field3 <> @MSKU
	and ReportAbstractReceived.Field1 <> @SUBTOTAL
	and ReportAbstractReceived.Field1 <> @GRNTOTAL
  Group By Reports.ReportID, ItemCategories.CategoryID,ItemCategories.Category_Name
 
End

--Add Branch Data into #TempConsolidate Table  
--Only 32 dynamic column consider  
If @SPRExist = 1
Begin  
 Declare @ReportID Int,@Sql NVarchar(255),@RPID NVarchar(255)   

 Declare   
  @Field1 NVarchar(255), @Field2 NVarchar(255), @Field3 NVarchar(255), @Field9 NVarchar(255),@Field10 NVarchar(255),@Field11 NVarchar(255)    
 ,@Field12 NVarchar(255), @Field13 NVarchar(255), @Field14 NVarchar(255), @Field15 NVarchar(255),@Field16 NVarchar(255), @Field17 NVarchar(255)  
 ,@Field18 NVarchar(255), @Field19 NVarchar(255), @Field20 NVarchar(255), @Field21 NVarchar(255)  
 ,@Field22 NVarchar(255), @Field23 NVarchar(255), @Field24 NVarchar(255), @Field25 NVarchar(255)  
 ,@Field26 NVarchar(255), @Field27 NVarchar(255), @Field28 NVarchar(255), @Field29 NVarchar(255)  
 ,@Field30 NVarchar(255), @Field31 NVarchar(255), @Field32 NVarchar(255), @Field33 NVarchar(255)  
 ,@Field34 NVarchar(255), @Field35 NVarchar(255), @Field36 NVarchar(255), @Field37 NVarchar(255)  
 ,@Field38 NVarchar(255), @Field39 NVarchar(255), @Field40 NVarchar(255), @Field41 NVarchar(255)  
 ,@Field42 NVarchar(255), @Field43 NVarchar(255), @Field44 NVarchar(255), @Field45 NVarchar(255)  
 ,@Field46 NVarchar(255), @Field47 NVarchar(255), @Field48 NVarchar(255)
  
 Declare @Column0 NVarchar(255), @Column1 NVarchar(255), @Column2 NVarchar(255), @Column3 NVarchar(255), @Column4 NVarchar(255)  
 ,@Column5 NVarchar(255), @Column6 NVarchar(255), @Column7 NVarchar(255), @Column8 NVarchar(255)  
 ,@Column9 NVarchar(255), @Column10 NVarchar(255), @Column11 NVarchar(255), @Column12 NVarchar(255)  
 ,@Column13 NVarchar(255), @Column14 NVarchar(255), @Column15 NVarchar(255), @Column16 NVarchar(255)  
 ,@Column17 NVarchar(255), @Column18 NVarchar(255), @Column19 NVarchar(255), @Column20 NVarchar(255)  
 ,@Column21 NVarchar(255), @Column22 NVarchar(255), @Column23 NVarchar(255), @Column24 NVarchar(255)  
 ,@Column25 NVarchar(255), @Column26 NVarchar(255), @Column27 NVarchar(255), @Column28 NVarchar(255)  
 ,@Column29 NVarchar(255), @Column30 NVarchar(255), @Column31 NVarchar(255), @Column32 NVarchar(255)  
  
 Declare @Column09 NVarchar(255), @Column100 NVarchar(255),@Column101 NVarchar(255), @Column102 NVarchar(255), @Column103 NVarchar(255),   
 @Column104 NVarchar(255),@Column105 NVarchar(255)  

 Declare CurReportID Cursor For Select Distinct ReportID From ReportAbstractReceived  
 Where ReportID In 
 (Select ReportID From Reports Where ReportName = 'Sales Position Report' And
 ParameterID in (Select ParameterID From dbo.GetReportParametersForSPR('Sales Position Report') Where
 FromDate = dbo.StripDateFromTime(@FromDate) And ToDate = dbo.StripDateFromTime(@ToDate)) )

 Open CurReportID  
  
 Fetch Next From CurReportID Into @ReportID  
  
 While @@Fetch_Status=0  
 Begin  
	If Cast( (Select Top 1 Field9 From ReportAbstractReceived Where ReportID=@ReportID) As nVarChar) = 'SKU'
	  Declare CurReceivedReport   
	  Cursor For Select "CatID" = ItemCategories.CategoryID ,Max(Field1),Max(Field2),ItemCategories.Category_Name
	  ,Sum(Cast(Cast(IsNull(Field13,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field14,0) as float)as Decimal(18,6))),Sum(Cast(Cast(ISNull(Field15,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field16,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field17,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field18,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field19,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field20,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field21,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field22,0) as float)as Decimal(18,6))),Sum(Cast(Cast(ISNull(Field23,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field24,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field25,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field26,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field27,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field28,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field29,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field30,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field31,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field32,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field33,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field34,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field35,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field36,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field37,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field38,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field39,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field40,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field41,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field42,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field43,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field44,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field45,0) as float)as Decimal(18,6)))
	  ,Sum(Cast(Cast(IsNull(Field46,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field47,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field48,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field49,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field50,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field51,0) as float)as Decimal(18,6))),Sum(Cast(Cast(IsNull(Field52,0) as float)as Decimal(18,6)))
	  From ReportAbstractReceived, Items,  ItemCategories
	  Where ReportID=@ReportID
    And Items.Product_Code = LTrim(RTrim(ReportAbstractReceived.Field3))
	  And ItemCategories.CategoryID = Items.CategoryID
		Group By ItemCategories.CategoryID,ItemCategories.Category_Name
	  Order By CatID	
  Else
	  Declare CurReceivedReport   
	  Cursor For Select IsNull(dbo.GetCategorieID(ReportAbstractReceived.Field3),0) "CatID",Field1,Field2,Field3  
	  ,IsNull(Field9,0),IsNull(Field10,0),IsNull(Field11,0),IsNull(Field12,0),IsNull(Field13,0),IsNull(Field14,0),ISNull(Field15,0)
	  ,IsNull(Field16,0),IsNull(Field17,0),IsNull(Field18,0),IsNull(Field19,0),IsNull(Field20,0)
	  ,IsNull(Field21,0),IsNull(Field22,0),ISNull(Field23,0),IsNull(Field24,0),IsNull(Field25,0)
	  ,IsNull(Field26,0),IsNull(Field27,0),IsNull(Field28,0),IsNull(Field29,0),IsNull(Field30,0)
	  ,IsNull(Field31,0),IsNull(Field32,0),IsNull(Field33,0),IsNull(Field34,0),IsNull(Field35,0)
	  ,IsNull(Field36,0),IsNull(Field37,0),IsNull(Field38,0),IsNull(Field39,0),IsNull(Field40,0)
	  ,IsNull(Field41,0),IsNull(Field42,0),IsNull(Field43,0),IsNull(Field44,0),IsNull(Field45,0)
	  ,IsNull(Field46,0),IsNull(Field47,0),IsNull(Field48,0)
	  From ReportAbstractReceived  
	  Where ReportID=@ReportID  
	  Order By CatID	
  
  Open CurReceivedReport  
  
  Fetch Next From CurReceivedReport Into @RPID,@Field1, @Field2, @Field3  
  , @Field9, @Field10, @Field11, @Field12, @Field13,@Field14,@Field15,@Field16,@Field17, @Field18, @Field19, @Field20  
  ,@Field21,@Field22,@Field23,@Field24,@Field25,@Field26,@Field27,@Field28,@Field29,@Field30,@Field31,@Field32,@Field33,@Field34  
  ,@Field35,@Field36,@Field37,@Field38,@Field39,@Field40,@Field41,@Field42,@Field43,@Field44,@Field45,@Field46,@Field47,@Field48
  
  While @@Fetch_Status=0  
  Begin  
  
   If @Field9 Like 'TROUT%'   
   Begin  
    Set @Column09='['+@Field9+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column09,0  
   End  
   If @Field3<>'MarketSKU' And @Field9<>'0' And Len(@Field9)>0
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column09,@Field9  
  
   If @Field10 Like 'TROUT%'   
   Begin  
    Set @Column100='['+@Field10+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column100,0  
   End  
   If @Field3<>'MarketSKU' And @Field10<>'0' And Len(@Field10)>0  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column100,@Field10  
  
   If @Field11 Like 'TROUT%'   
   Begin  
    Set @Column101='['+@Field11+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column101,0  
   End  
   If @Field3<>'MarketSKU' And @Field11<>'0' And Len(@Field11)>0   
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column101,@Field11  
  
   If @Field12 Like 'TROUT%'   
   Begin  
    Set @Column102='['+@Field12+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column102,0  
   End  
   If @Field3<>'MarketSKU' And @Field12<>'0' And Len(@Field12)>0  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column102,@Field12  
  
   If @Field13 Like 'TROUT%'   
   Begin  
    Set @Column103='['+@Field13+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column103,0  
   End  
   If @Field3<>'MarketSKU' And @Field13<>'0' And Len(@Field13)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column103,@Field13  
  
   If @Field14 Like 'TROUT%'   
   Begin  
    Set @Column104='['+@Field14+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column104,0  
   End  
   If @Field3<>'MarketSKU' And @Field14<>'0' And Len(@Field14)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column104,@Field14  
  
   If @Field15 Like 'TROUT%'   
   Begin  
    Set @Column105='['+@Field15+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column105,0  
   End  
   If @Field3<>'MarketSKU' And @Field15<>'0' And Len(@Field15)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column105,@Field15  
  
   If @Field16 Like 'TROUT%'   
   Begin  
    Set @Column0='['+@Field16+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column0,0  
   End  
   If @Field3<>'MarketSKU' And @Field16<>'0' And Len(@Field16)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column0,@Field16  
  
   If @Field17 Like 'TROUT%'   
   Begin  
    Set @Column1='['+@Field17+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column1,0  
   End  
   If @Field3<>'MarketSKU' And @Field17<>'0' And Len(@Field17)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column1,@Field17  
  
   If @Field18 Like 'TROUT%'   
   Begin  
    Set @Column2='['+@Field18+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column2,0  
   End  
   If @Field3<>'MarketSKU' And @Field18<>'0' And Len(@Field18)>0    
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column2,@Field18  
  
   If @Field19 Like 'TROUT%'   
   Begin  
    Set @Column3='['+@Field19+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column3,0  
   End  
   If @Field3<>'MarketSKU' And @Field19<>'0' And Len(@Field19)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column3,@Field19  
  
   If @Field20 Like 'TROUT%'   
   Begin  
    Set @Column4='['+@Field20+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column4,0  
   End  
   If @Field3<>'MarketSKU' And @Field20<>'0' And Len(@Field20)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column4,@Field20  
  
   If @Field21 Like 'TROUT%'   
   Begin  
    Set @Column5='['+@Field21+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column5,0  
   End  
   If @Field3<>'MarketSKU' And @Field21<>'0' And Len(@Field21)>0   
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column5,@Field21  
  
   If @Field22 Like 'TROUT%'   
   Begin  
    Set @Column6='['+@Field22+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column6,0  
   End  
   If @Field3<>'MarketSKU' And @Field22<>'0' And Len(@Field22)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column6,@Field22  
  
   If @Field23 Like 'TROUT%'   
   Begin  
    Set @Column7='['+@Field23+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column7,0  
   End  
   If @Field3<>'MarketSKU' And @Field23<>'0' And Len(@Field23)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column1,@Field17  
  
   If @Field24 Like 'TROUT%'   
   Begin  
    Set @Column8='['+@Field24+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column8,0  
   End  
   If @Field3<>'MarketSKU' And @Field24<>'0' And Len(@Field24)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column8,@Field24  
  
   If @Field25 Like 'TROUT%'   
   Begin  
    Set @Column9='['+@Field25+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column9,0  
   End  
   If @Field3<>'MarketSKU' And @Field25<>'0' And Len(@Field25)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column9,@Field25  
  
   If @Field26 Like 'TROUT%'   
   Begin  
    Set @Column10='['+@Field26+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column10,0  
   End  
   If @Field3<>'MarketSKU' And @Field26<>'0' And Len(@Field26)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column10,@Field26  
  
   If @Field27 Like 'TROUT%'   
   Begin  
    Set @Column11='['+@Field27+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column11,0  
   End  
   If @Field3<>'MarketSKU' And @Field27<>'0' And Len(@Field27)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column11,@Field27  
  
   If @Field28 Like 'TROUT%'   
   Begin  
    Set @Column12='['+@Field28+']'   
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column12,0  
   End  
   If @Field3<>'MarketSKU' And @Field28<>'0' And Len(@Field28)>0  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column12,@Field28  
  
   If @Field29 Like 'TROUT%'   
   Begin  
    Set @Column13='['+@Field29+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column13,0  
   End  
   If @Field3<>'MarketSKU' And @Field29<>'0' And Len(@Field29)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column13,@Field29  
  
   If @Field30 Like 'TROUT%'   
   Begin  
    Set @Column14='['+@Field30+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column14,0  
   End  
   If @Field3<>'MarketSKU' And @Field30<>'0'  And Len(@Field30)>0
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column14,@Field30  
  
   If @Field31 Like 'TROUT%'   
   Begin  
    Set @Column15='['+@Field31+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column15,0  
   End  
   If @Field3<>'MarketSKU' And @Field31<>'0' And Len(@Field31)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column15,@Field31  
  
   If @Field32 Like 'TROUT%'   
   Begin  
    Set @Column16='['+@Field32+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column16,0  
   End  
   If @Field3<>'MarketSKU' And @Field32<>'0' And Len(@Field32)>0  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column16,@Field32  
  
   If @Field33 Like 'TROUT%'   
   Begin  
    Set @Column17='['+@Field33+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column17,0  
   End  
   If @Field3<>'MarketSKU' And @Field33<>'0' And Len(@Field33)>0   
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column17,@Field33  
  
   If @Field34 Like 'TROUT%'   
   Begin  
    Set @Column18='['+@Field34+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column18,0  
   End  
   If @Field3<>'MarketSKU' And @Field34<>'0' And Len(@Field34)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column18,@Field34  
  
   If @Field35 Like 'TROUT%'   
   Begin  
    Set @Column19='['+@Field35+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column19,0  
   End  
   If @Field3<>'MarketSKU' And @Field35<>'0' And Len(@Field35)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column19,@Field35  
  
   If @Field36 Like 'TROUT%'   
   Begin  
    Set @Column20='['+@Field36+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column20,0  
   End  
   If @Field3<>'MarketSKU' And @Field36<>'0' And Len(@Field36)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column20,@Field36  
  
   If @Field37 Like 'TROUT%'   
   Begin  
    Set @Column21='['+@Field37+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column21,0  
   End  
   If @Field3<>'MarketSKU' And @Field37<>'0' And Len(@Field37)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column21,@Field37  
  
   If @Field38 Like 'TROUT%'   
   Begin  
    Set @Column22='['+@Field38+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column22,0  
   End  
   If @Field3<>'MarketSKU' And @Field38<>'0' And Len(@Field38)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column22,@Field38  
  
   If @Field39 Like 'TROUT%'   
   Begin  
    Set @Column23='['+@Field39+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column23,0  
   End  
   If @Field3<>'MarketSKU' And @Field39<>'0' And Len(@Field39)>0   
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column23,@Field39  
  
   If @Field40 Like 'TROUT%'   
   Begin  
    Set @Column24='['+@Field40+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column24,0  
   End  
   If @Field3<>'MarketSKU' And @Field40<>'0' And Len(@Field40)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column24,@Field40  
  
   If @Field41 Like 'TROUT%'   
   Begin  
    Set @Column25='['+@Field41+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column25,0  
   End  
   If @Field3<>'MarketSKU' And @Field41<>'0' And Len(@Field41)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column25,@Field41  
  
   If @Field42 Like 'TROUT%'   
   Begin  
    Set @Column26='['+@Field42+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column26,0  
   End  
   If @Field3<>'MarketSKU' And @Field42<>'0' And Len(@Field42)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column26,@Field42  
  
   If @Field43 Like 'TROUT%'   
   Begin  
    Set @Column27='['+@Field43+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column27,0  
   End  
   If @Field3<>'MarketSKU' And @Field43<>'0' And Len(@Field43)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column27,@Field43  
  
   If @Field44 Like 'TROUT%'   
   Begin  
    Set @Column28='['+@Field44+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column28,0  
   End  
   If @Field3<>'MarketSKU' And @Field44<>'0' And Len(@Field44)>0  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column28,@Field44  
  
   If @Field45 Like 'TROUT%'   
   Begin  
    Set @Column29='['+@Field45+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column29,0  
   End  
   If @Field3<>'MarketSKU' And @Field45<>'0' And Len(@Field45)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column29,@Field45  
  
   If @Field46 Like 'TROUT%'   
   Begin  
    Set @Column30='['+@Field46+']'  
     Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column30,0  
   End  
   If @Field3<>'MarketSKU' And @Field46<>'0'  And Len(@Field46)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column30,@Field46  
  
   If @Field47 Like 'TROUT%'   
   Begin  
    Set @Column31='['+@Field47+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column31,0  
   End  
   If @Field3<>'MarketSKU' And @Field47<>'0' And Len(@Field47)>0 
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column31,@Field47  
  
   If @Field48 Like 'TROUT%'   
   Begin  
    Set @Column32='['+@Field48+']'  
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column32,0  
   End  
   If @Field3<>'MarketSKU' And @Field48<>'0'  And Len(@Field48)>0
    Exec Sp_TempTableUpldate_SPR_ITC @RPID,@Field1,@Field2,@Field3,@Column32,@Field48  

 
  Fetch Next From CurReceivedReport Into @RPID,@Field1, @Field2, @Field3
  ,@Field9, @Field10,@Field11, @Field12, @Field13,@Field14,@Field15,@Field16,@Field17, @Field18, @Field19, @Field20
  ,@Field21,@Field22,@Field23,@Field24,@Field25,@Field26,@Field27,@Field28,@Field29,@Field30,@Field31,@Field32,@Field33,@Field34
  ,@Field35,@Field36,@Field37,@Field38,@Field39,@Field40,@Field41,@Field42,@Field43,@Field44,@Field45,@Field46,@Field47,@Field48
  End  
    
  Close CurReceivedReport  
  Deallocate CurReceivedReport  

  Fetch Next From CurReportID Into @ReportID  
 End  
 Close CurReportID  
 Deallocate CurReportID  
End  


--To Add received dynamic column into select statement
Declare @Col NVarchar(255)
Declare DColumn Cursor For Select * From #TempExistColumn
Open DColumn
Fetch next from DColumn Into @Col
while @@Fetch_Status=0
Begin
	Set @ConDynCol=@ConDynCol+',"'+Replace(Replace(@Col,'[',''),']','')+'"=Sum('+@Col+')'
	Fetch next from DColumn Into @Col
End
Close DColumn
Deallocate DColumn
Drop Table #TempCategory1
EndProc:
Set @SqlQuery='Select WDCode, WDCode, WDDest, MarketSKU, "Opl. SOH"=Sum([Opl. SOH]),"Receipts + TRIN"=Sum([Receipts + TRIN]),"Sales"=Sum(Sales),"D&D"=Sum([D&D]),"Cl. SOH"=Sum([Cl. SOH])'+ @ConDynCol + ' From #TempConsolidate Group By WDCode, WDDest, MarketSKU Order By MarketSKU'
Exec (@SqlQuery)

Drop Table #TempCategory
Drop Table #TempConsolidate
Drop Table #TempTROUT
Drop Table #TempExistColumn
Drop Table #TmpMfr
