CREATE PROCEDURE spr_list_Item_RecStocReq_BranchDet
(@PCODE nvarchar(40),@FROMDATE DATETIME,@TODATE DATETIME)    
AS  
SELECT "Branch Id"=WAREHOUSE.WAREHOUSEID,"Branch Id"=WAREHOUSE.WAREHOUSEID,"Branch Name"=WAREHOUSE_NAME,
"Received Stock Request Number"=SRABSTRACTRECEIVED.ORIGINALSTOCKREQUEST,"Requested Quantity"=SUM(QUANTITY),
"Pending Quantity"=SUM(PENDING) FROM SRABSTRACTRECEIVED, STOCK_REQUEST_DETAIL_RECEIVED,WAREHOUSE
WHERE SRABSTRACTRECEIVED.STOCKREQUESTNO = STOCK_REQUEST_DETAIL_RECEIVED.STK_REQ_NUMBER AND
STOCK_REQUEST_DETAIL_RECEIVED.PRODUCT_CODE = @PCODE
AND WAREHOUSE.WAREHOUSEID = SRABSTRACTRECEIVED.WAREHOUSEID
AND SRABSTRACTRECEIVED.DOCUMENTDATE BETWEEN  @FROMDATE  AND  @TODATE
GROUP BY ORIGINALSTOCKREQUEST, WAREHOUSE.WAREHOUSEID,WAREHOUSE_NAME

