IF EXISTS(SELECT Top 1 1 FROM sys.objects WHERE Name = N'ARC_Product_Mappings_Update')
BEGIN
	DROP PROC ARC_Product_Mappings_Update
END
GO
CREATE procedure [dbo].ARC_Product_Mappings_Update (@Product_Code NVARCHAR(255), @ProductName NVARCHAR(255), @CategoryGroup NVARCHAR(255), @Category NVARCHAR(255), @ItemFamily NVARCHAR(255), @ItemSubFamily NVARCHAR(255), @ItemGroup NVARCHAR(255))
As
Begin
	Declare @CategoryGroupId INT
	Declare @CategoryId INT
	Declare @ItemFamilyId INT
	Declare @ItemSubFamilyId INT
	Declare @ItemGroupId INT

	Select @CategoryGroupId = ISNULL(CategoryGroupId, 0) From CategoryGroups With (NOLOCK) WHERE CategoryGroupName = @CategoryGroup
	Select @CategoryId = ISNULL(CategoryId, 0) From Category With (NOLOCK) WHERE CategoryName = @Category
	Select @ItemFamilyId = ISNULL(ItemFamilyId, 0) From ItemFamily With (NOLOCK) WHERE ItemFamilyName = @ItemFamily
	Select @ItemSubFamilyId = ISNULL(ItemSubFamilyId, 0) From ItemSubFamily With (NOLOCK) WHERE ItemSubFamilyName = @ItemSubFamily
	Select @ItemGroupId = ISNULL(ItemGroupId, 0) From ItemGroup With (NOLOCK) WHERE ItemGroupName = @ItemGroup

	IF NOT EXISTS(SELECT TOP 1 1 FROM Product_Mappings WITH (NOLOCK) WHERE Product_Code = @Product_Code)
	BEGIN
		Insert Into Product_Mappings(Product_Code, ProductName, CategoryGroup, Category, ItemFamily, ItemSubFamily, ItemGroup)
		Select @Product_Code, @ProductName, @CategoryGroupId, @CategoryId, @ItemFamilyId, @ItemSubFamilyId, @ItemGroupId
	END
	ELSE
	BEGIN
		Update P
		SET 
			P.ProductName = @ProductName,
			P.CategoryGroup = @CategoryGroupId,
			P.Category = @CategoryId,
			P.ItemFamily = @ItemFamilyId,
			P.ItemSubFamily = @ItemSubFamilyId,
			P.ItemGroup = @ItemGroupId
		FROM Product_Mappings P WITH (NOLOCK) WHERE P.Product_Code = @Product_Code
	END
	IF EXISTS(SELECT TOP 1 1 FROM TransactionByDay WITH (NOLOCK) WHERE Product_Code = @Product_Code)
	BEGIN
		Update P
		SET 		
			P.CategoryGroup = dbo.fn_Arc_GetCategoryGroup(@CategoryGroupId), 
			P.Category = dbo.fn_Arc_GetCategory(@CategoryId), 
			P.ItemFamily = dbo.fn_Arc_GetItemFamily(@ItemFamilyId), 
			P.ItemSubFamily = dbo.fn_Arc_GetItemSubFamily(@ItemSubFamilyId), 
			P.ItemGroup = dbo.fn_Arc_GetItemGroup(@ItemGroupId)
		FROM TransactionByDay P WITH (NOLOCK) WHERE P.Product_Code = @Product_Code
	END
END
GO
Exec ARC_Product_Mappings_Update '43','Cl Refresh Taste10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '46','Cl Refresh Taste20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '51','Cl Fine TL sl 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '299','B&H SPL FTK MD 20HL','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '300','B&H Gold Blue 20HL','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '311','Gold Flake SLK 16CP','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '327','CL VERVE  16CP','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '991','INDIA KINGS RH 20RC','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '997','GOLD FLAKE FT 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1000','NAVYCUT FT','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1003','Gold Flake FT','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1046','SILKCUT VIRGINIA','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1182','GOLD FLAKE CREST','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1504','Classic Double Burst 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1506','SCISSORS FT 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1539','Wave Fruit Mint','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1581','Cl Balanced T Firm 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1593','Cl Rich T Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1594','Cl Refined T Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1636','GFK Red Mint Switch 10RC','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1637','GFK Blue Menthol Switch 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1646','GFK Red Firm 20RC','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1647','GFK Red Firm 10RC','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1648','GFK Blue Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1649','GFK Blue Firm 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1650','Cl Fine Low Smell 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1651','Classic Ice Burst 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1653','Cl Balanced 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1675','Cl Double Burst 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1695','GFT Blue Fresh Mint 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1716','Cl Ice Burst 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1719','GFK Neo Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1720','GFK Neo Firm 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1725','GFK SLK L smell 16CP','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1728','Navy Cut Dlx FT 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1740','Flk Mint Capsul 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1786','Wave Cool Mint 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '1789','Wave Fruit Mint 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3016','GOLD FLAKE SPL 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3023','SCISSORS SPL FT 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3043','Cl Ice Burst 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3044','Cl Ice Burst 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3046','Cl Double Burst 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3048','Cl Fine T L S 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3049','Cl BT Firm 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3051','Cl BT NB 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3053','Cl Refr Taste 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3056','Cl Rich T Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3058','Cl Refn T Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3062','GFK Red Firm 10RC','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3063','GFK Red Firm 20RC','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3064','GFK Blue Firm 10BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '3065','GFK Blue Firm 20BE','GR4','CG','CIG','CIGARETTE ',''
Exec ARC_Product_Mappings_Update '9754','AIM WAX 35s','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9829','CHEETAFIGHT 35s','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9859','CHEETAFIT WX 35St 6s','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9876','CHEETAFIGHT WX 30Sts','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9885','SHIP WAX LONGS 35S','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9952','HOMELITES RS 2 50 ST','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9954','HOMELITES RS 2 50 ST','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '9976','HM LITES LARGE','GR2','MT','PCP','MATCHES',''
Exec ARC_Product_Mappings_Update '11008','MD 84 Sandal','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11009','MD Sambrani','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11012','MD 84 Bouquet','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11016','MD 84 Treya','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11017','MD 84 FOT','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11077','MD 84 JATHIMALLIGAI','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11092','MD 30 SANDAL','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11111','MD 85 5 IN 1','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11124','MD 70 Flora','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11176','MD 20 Temple Silver','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11249','MD 14 Bouquet - Fragrance Plus','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11254','MD Rs 20 Pushpanjali','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11256','MD Rs 50 Pushpanjali','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11259','MD Rs.80 Popular Combo 4 pack_11259','GR2','TS','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11263','MD 14 Treya-New pack with outer_11263','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11477','MD 84 Lavend(ULOCKED','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11484','MD 14 F Sandal Tradi','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11485','MD 35 FOT Sandal Tradition','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11621','MD 14 BOUQUET NP (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11622','MD 14 Sandal NP UNLOCK','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11623','MD 14 ROSE NP (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11624','MD 14 MOGRA NP (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11625','MD 14 FOT (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11626','MD 14 Lavender (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11627','MD 14 Treya NP(UNLOCKED','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11632','MD14 Jathimalligai NP (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11743','MD DEETYAA COMBO 123 (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11758','MD Sadhvi 100 (UNLOCKED)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11783','MD 14 TREYA - NP (VISIBILITY)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11784','MD 14 DEETYAA COMBO123 (VISIBILITY)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11786','MD 14 LAVENDER - (VISIBILITY)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11791','MD 14 SANDAL - FREE SAMPLE POUCH','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11824','MD FOT Gold Yagna','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11825','MD FOT Silver Diya Rs.20(Unlocked)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11827','MD FOT Gold Yagna Rs.50(Unlocked)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11828','MD FOT Silver Diya Rs.50(Unlocked)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11954','MD 80 Treya -New (Extra 20%)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11955','MD 80 Treya -New','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11974','Mangaldeep 14 Sandal','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11985','Mangaldeep 14 Lavender','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11986','MD 14 Treya-New(Extra 20%)','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11987','Mangaldeep 14 Rose','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11988','Mangadeep 14 Mogra','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11989','Mangaldeep 14 Temple','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11990','Mangaldeep 14 Bouquet','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11992','MD Rs.10 Marigold','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11993','Mangaldeep 35 Sandal','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11994','Mangaldeep 84 Sandal','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11995','Mangaldeep 84 Lavender','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11997','Mangaldeep 84 Temple','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '11998','Mangaldeep 84 Bouquet','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update '12000','MD Rs. 50 Marigold','GR2','AG','PCP','AGARPATTI',''
Exec ARC_Product_Mappings_Update 'F11589Q','GULABJAMUN 200G','GR1','RT','FOOD ','READY TO EAT',''
Exec ARC_Product_Mappings_Update 'FA020029','SALT - 1KG','GR1','SA','FOOD ','SALT',''
Exec ARC_Product_Mappings_Update 'FA020031','SALT - 1KG','GR1','SA','FOOD ','SALT',''
Exec ARC_Product_Mappings_Update 'FA2116','ATTA 0.5KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2116T','ATTA 0.5KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2116TN','ATTA 0.5KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2132','ATTA M GRAINS - 5KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2132C','AASHIRVAAD ATTA MULTIGRAINS - 5KG_FA2132C','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2133','ATTA M GRAINS - 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2133C','ATTA M GRAINS - 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA2135','ATTA MGS - 2 KG BOX','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA3401B','SUNFEAST NICE 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FA3402B','SUNFEAST NICE 150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FA4086GG','JELIMALS 36G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA4087','JELLS JELIMALS 30G ','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA4088','JELLS JELIMALS 30G ','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA4095','JELLY BITES 10G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FA4264','CM TADKA 520+80G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA4272','CM CRUN P NUT 640G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA4425P','CM CHOCO DCLR 380G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA4720K','CM COFITINO 810G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FA600100','SUGAR REL ATTA 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA600100A','SUGAR REL ATTA 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA700100','RAGI FLOUR 1 KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA700500','RAGI FLOUR 0.5 KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA800100','AASHIRVAAD NSF MULTI MILLET MIX1KG_FA800100','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA800500',' MULTI MILLETMIX500G','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA900100','GLUTEN FR FLOUR 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA900500','GLUTEN FR FLOUR500G','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FA9681AN','TM TOMATO - RS.5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9682AN','TM TOMATO - RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9851Q','MAD AN ACHAARI RS.5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9852O','MAD AN ACHAARI RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9853P','MAD AN ACHAARI RS.20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9871CP','MAD AN MASALA RS.5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9872R','MAD AN MASALA RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9873R','MAD AN MASALA RS.20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9881Q','MAD AN TOMOTO RS.5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9882Q','MAD AN TOMOTO RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9884Q','MAD AN TOMOTO RS.20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9898A','MA PERI PERI RS.5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9898B','MA PERI PERI RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FA9898C','MA PERI PERI RS.20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB101005','DF CHOCO FILLS 20G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB101123','DF CHOCO FILLS 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB101210','DF C FILLS LUXRA 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB102112','DF COF FILLS 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB104402','DF VANNILA 100G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB105001','DF CH MELTZ 50G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB105001A','DF CH MELTZ 50G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB152813','DF YFS WPIE VEG 414G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB152814','DF YFS WPIE 414G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB152815','DF YFS WPIE VEG 138G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB152816','DF YFS WPIE VEG 235G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB207101','DF BOURBON 90G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB207200','DF BOURBON 120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB207300','DF BOURBON 150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB207400','DF BOURBON 600G(3+1)','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB2115','ATTA 2KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FB2115T','ATTA 2KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FB2115TN','ATTA 2KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FB212111','BDC CH VANILLA 60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB212211','BDC CH VANILLA 120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB213111','BDC STR VANILLA 60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB213211','BDC STR VANILLA120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB214111','BDC BTRCH ZING 60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB214211','BDC BTRCH ZING 120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB251112','SF OATS & RAISINS75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB251211','SF OATS&RAISINS150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB252112','SF OATS & ALMOND 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB253211','SF OT CHOCOLATE 150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB255210','SF DIG ALL GOOD100G ','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB257211','SF DIG 5 GRAIN 1 KG ','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB257211A','SF DIG 5 GRAIN 1 KG ','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB259210','SF ACT P POWER 150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB301122','BNC CHOCO TWIST34+7G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB301230','BNC CHOCO TWIST 82G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB302123','BNC EL DELIGHT 34+7G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB302224','BNC EL DELIGHT 82G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB302225','BNC EL DELIGHT 82G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB303122','BNC TAN ORANGE 34+7G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB304122','BNC PAPPLE ZING34+7G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB304225','BNC P APPLE ZING 82G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB308101','BNC S BERRY MINIS25G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB310101','BNC CH CREME CAKE25G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB310301','BNC B SCH CR CAKE25G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB451215A','SFMM RICHBUTTER38.5G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB451215E','SFMM RICHBUTTER 44G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB451224','SFMM RICHBUTTER 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB451412','SFMM RICHBUTTER150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB452123T','SFMM CASHEW&ALMDS60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB452210B','SFMM CASHEW&ALMDS33G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB452210C','SFMM CASHEW&ALMDS33G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB452418T','SFMM CAS&ALM 100+50G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB452526T','SFMM CAS&ALM 200G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB452601','SFMM CAS&ALM 100G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB453700','SFMM FRUIT&MILK 60.8G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB453701','SFMM FRUIT&MILK 60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB453800','SFMM FRUIT&MILK 100G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB453900','SFMM FRUIT&MILK 200G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB454101','SFMM NUT BISCOTTI60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB454101A','SFMM NUTBISCOTTI 60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB454201','SFMM NUTS&RAISIN60G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB454300','SFMM CHOCO CHIPS100G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB454600','SFMM CHOCO CHIPS120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB454800','SFMM CHOCO CHIPS 46.4G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB501121','SF HI BTR COOKIES36G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB502120','SF HI BTR COOKIES36G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB502122','SFHIC COOKIES 36+4.5G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB601211','SF GLUC BISCUITS 32G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701128','SF MLT RCH TST38+14G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701238M','SF MLT RCH TST70+30G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701314','SF MLT RCH TST 120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701425','SF MLT RCH TST 200G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701426','SFMLT R TST200G 20PR','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701546','SF MLT RCH TST 300G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701550','SF MLT RCH TST 250G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701600','SF MLT RCH TST250GX5','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701701','SF MLIGHT VITA75+15G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701702','SFM LIGHT VITA 150G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB701800','SFM LIGHT VEDA 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB702114','SFM LIGHT OATS 120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB702212','SFM LIGHT OATS 200G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB702402','SFM LIGHT OATS 75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB703113','SFM LIGHT ORANGE120G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB703202','SFM LIGHT ORANGE75G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB801125','SF A2 COWMILK81+19G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB801127','SF A2 COWMILK40+10G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB801129','SF A2 COWMILK100G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB902313','SF SA CR BISC 50+12G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB903014P','SF SWT N SALT30G+10G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB903115P','SF SWT N SALT60G+10G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB903214P','SF SWT N SLT120G+30G','GR1','BI','FOOD ','BISCUIT ',''
Exec ARC_Product_Mappings_Update 'FB9245C','BI OR STY CHILLIRS10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9246C','BI OR STY CHILLIRS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9246D','BINGO! ORIGINAL STYLE RS.20 CHILLI_FB9246D','GR1','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9255C','BI OR STY SALT RS10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9256C','BI OR STY SALT RS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9621LN','TM MASALA RS.5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9622BN','TM MASALA RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FB9625F','TM MASALA RS.20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FC4249A','CM FRUITEE FUN 280G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4253A','CM FRUITEE FUN 840G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4259A','CM FR FUN 3472+168G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4270A','CM FRUITY DELITE646G ','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4271','CM FR DELITE3040G JJ','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4410','CM CHOCO DOUBLE380G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4410A','CM CH ECLARS418G+38G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4410G','CM CH ECLARS418G+57G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4410I','CM CHOCO ECLAIRS 407G+37GFR VO PB_FC4410I','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4421A','CM ECLAIRS 50P 270G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4422A','CM 50P ECLAIRS 945G PJ_FC4422A','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4422N','CM ECLAIRS 50P 840G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4423O','CM EC 50P 3752+168G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4426L','CM CHOCO ECLAIRS760G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4427M','CM CH ECLAR3667+228G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4441','CM MILK ECLAR418+57G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4441A','CM MILK ECLAR418+38G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4651A','MINT FR AT2450G+350G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4652A','MINT FR EUCA560G+70G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4660','CM CL CNDY 429+58.5G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4671','CM FANTASTIK 360G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4672A','CM FANTASTIK 250G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4812J','CM CREME LACTO 900G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4812L','CM CREME LACTO 880G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4813I','CM CREME LACTO 3690G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4813J','CM CREME LACTO 3608G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4815A','CM CREMELACTO495+45G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4815B','CM CREMELACTO484+44G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4831A','CM T STRAWBERRY 270G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4832A','CM T STRAWBERRY 810G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4838','CM DUOCHO SBY440+60G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4838A','CM DUOCHO SBY440+40G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC4930A','MI GOL RE1 AST 700G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FC6103G','GN ASORTED SB+SM675G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FD2113','ATTA 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FD2113TN','ATTA 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FD2113TT','ATTA 1KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FD2125N','ATTA SELECT 1KG ','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FD2126N','ATTA SELECT 5KG ','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FD2126NC','ATTA SELECT5KG CLEAN','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FDB100205','WRM FRTnMILK MGO200M','GR1','DB','FOOD ','WONDERS',''
Exec ARC_Product_Mappings_Update 'FDB100300','WRM VENILA MKSHK200M','GR1','DB','FOOD ','WONDERS',''
Exec ARC_Product_Mappings_Update 'FDB100400','WRM KESAR BDM NS200M','GR1','DB','FOOD ','WONDERS',''
Exec ARC_Product_Mappings_Update 'FDF100052','COW GHEE 50ML PCH','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF100054','COW GHEE 50ML PCH','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF100102','COW GHEE 100ML PCH','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF100104','COW GHEE 100ML PCH','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF101202','COW GHEE 200ML PET','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF101204','COW GHEE 200ML PET','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF101502B','COW GHEE 500 ML ','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF101503','COW GHEE 500ML PET','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF101505','COW GHEE 500ML PET','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF111004','COW GHEE 1LIT PET','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FDF111007','COW GHEE 1LIT PET','GR1','DF','FOOD ','GHEE',''
Exec ARC_Product_Mappings_Update 'FH2112','ATTA 5 KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FH2112LL','ATTA 5 KG+SALT FREE','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FH2112T','ATTA 5 KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FH2112TN','ATTA 5 KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FJ0101107','BNTRL APPLE 200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0101207','BNTRL APPLE 1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0206105','BNTRL MGO MAGIC200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0206107','BNTRL MGO MAGIC200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0206207','BNTRL MGO MAGI1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0207107','BNT MIX FRU MRY200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0207207','BNT MIX FRU MR1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0208105','BNT ORA OOMPH200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0208107','BNT ORA OOMPH200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0210107','BNT GUAVA GUSH200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0210207','BNT GUAVA GUSH1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0211205','BNT PGRTE100%1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0212107','BNT LITCHI LUSC200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0212207','BN LITCHI LUSC1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0223101','BN HIMALAYAN MX300ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0223201','BN HIMALAYAN MX750ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0226101','BN RATNAGIR ALP300ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0226201','BN RATNAGIR ALP750ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0230101','BN DAKPINKGUAVA300ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0230201','BN DAKPINKGUAVA750ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0231102','BN WATMLON 200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0231201','BN WATMLON 1000ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FJ0299104','BN WATMLON LIT200ML','GR1','JU','FOOD ','JUICES',''
Exec ARC_Product_Mappings_Update 'FL2111','ATTA 10KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FL2111TN','ATTA 10KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FL2111TT','ATTA 10KG','GR1','AT','FOOD ','ATTA',''
Exec ARC_Product_Mappings_Update 'FN1145','YI MA NOODLES 280G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1205GA','YI MA NOODLES 32.5G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1205GP','YI MAS ND STR 32.5G ','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1212','YI MAS NOODLES 70G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1223','YI MGC MSL NOODL140G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1240PE','MA MOOD MAS BOX 840G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1245','YI MASNOODLES 280G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1245D','YI MASNOODLES 280G ','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1245F','YI MASNOODLES 280G ','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1245MP','YI MASND COAST280G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1267','YI MGCMSL NOODLE420G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1267D','YI MGCMSL NOODLE420G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1267F','YI MGCMSL NOODLE420G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1267GP','YI MGC MSL ND420G+MM','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1267KP','YI MGC MSL ND420G+MM','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1415','SF YI POW UP NOOD70G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1415A','SF YI POW UP NOOD70G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1515','YI MMAS NOODLES70G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1515G','YI MMAS NOO70G20%OFF','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FN1555','YI MMAS NOODLES 280G','GR1','ND','FOOD ','NOODLES',''
Exec ARC_Product_Mappings_Update 'FP1115HP','YI TRC PST COR35+15G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP1125BP','YI TRC PST COR70+21G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP1225BP','YI TRC PST MAS70+21G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP2125','YI PASTA CHEESE 70G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP2126','YI PASTA CHEESE 65G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP2225','YI PASTA MASALA 70G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP2226','YI PASTA MASALA 65G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP2325','PA CREAM ONION 70G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FP2425','PA TOMATO CHEESE 70G','GR1','SN','FOOD ','PASTA',''
Exec ARC_Product_Mappings_Update 'FR020031','SALT 1 KG','GR1','SA','FOOD ','SALT',''
Exec ARC_Product_Mappings_Update 'FR4410A','CM CH ECLAIR418G+38G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FR4426L','CM CH ECLAIRS760G','GR1','CF','FOOD ','CONFECTIONARY',''
Exec ARC_Product_Mappings_Update 'FS200604K','MA CHICCHETTINAD 20G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200610','MA CHICCHETTINAD 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200704K','MA MDS MILA RAS 20G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200710','MA MDS MILA RAS 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200810','MA  MADI KBU MILA50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200814','MA  MADI KBU MILA12G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200904K','MA THANR SAMBAR 20G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS200910','MA THANR SAMBAR 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS201220','MA CHIC65MASALA RS10','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS201250','MA CHIC65MASALA 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS201320','MA MUT CHU MSLA RS10','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS201350','MA MUT CHU MSLA 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS201420','MA FISH FR MAS RS10','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS201450','MA FISH FR MAS 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS300050','MA CHILLI POWDER50G ','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS300100','MA CHILLI POWDER100G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS400050','MA CORIR PWR 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS400100','MA CORIR PWR 100G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS600050','MA TURM POWDER 50G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FS600100','MA TURM PWR 100G','GR1','SI','FOOD ','SPICES',''
Exec ARC_Product_Mappings_Update 'FXC100010','BI ST MINICHIP RS10 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC100020','BI ST MINICHIP RS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC10005B','BI CHIPS SALT RS.5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC10011','BI CHIPS SALT RS.10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC10020','BI CHIPS SALT RS.20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC110010','BI ST CHPA CHIP RS10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC110020','BI ST CHPA CHIP RS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC20005B','BI CHI CRM&ON RS 5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC20011','BI CHI CRM&ON RS10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC20020','BI CHI CRM&ON RS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC30005B','BI CHI TOMATO RS 5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC30011','BI CHI TOMATO RS 10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC30020','BI CHI TOMATO RS 20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC40005B','BI CHI MASALA RS 5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC40011','BI CHI MASALA RS 10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC40020','BI CHI MASALA RS 20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC50005B','BI CHI TOMA&CHIL RS5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC60005B','BI CHI CHILLI RS5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC80010','BI ST MASA CHIP RS10','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC80020','BI ST MASA CHIP RS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXC90020','BI ST PEPPER CH RS20','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXN100013','NORZ CHE FR TOYRS.5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXN200009','NORZ TOM FR TOYRS.5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXN200013','NORZ TOM FR TOYRS.5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXN300013','NORZ MAS FR TOYRS.5 ','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXN400006','BINRZ MAS CU 20%ERS5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'FXN500006','BINRZ CHES CU20%ERS5','GR3','SX','FOOD ','SNACKS ',''
Exec ARC_Product_Mappings_Update 'NFR808S','En Lamant Him75ml NF','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'NFR809S','En Lamant Her75ml NF','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0177','En Blush Deo150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0178','En Spell Deo150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0179','En Tease Deo150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0180','En Rush Deo150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0182','En Urge Deo 150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0183','En Frost Deo150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0184','En Drizz Deo150ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0255','En Blush Deo165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0256','En Spell Deo165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0257','En Tease Deo165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0258','En  DrizzL Deo165ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0259','En Rush Deo 165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0260','En Mate Deo 165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0261','En Urge Deo 165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0262','En Frost Deo165ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0263','En  SpCl HimDeo165ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0264','En  SpCl HerDeo165ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0265','En Spt F HimDeo165ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0266','En Spt F HerDeo165ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0287','En Intri HimDeo150ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0288','En Intri HerDeo150ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0289','En Spir HimDeo150ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENDO0290','En For Deo 150ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0042','En AsorPack Flip18ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0049','En ON ManAssor18.4ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0050','En ON WManAsso18.4ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0083','En ONManDual Ass28ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0084','En Woman Duasort28ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0112','En  ON Man Assor17m','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0113','En ON Woman Ass17ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0122','En Man Ltn SM Pkt 18ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPK0123','En ON Wom LEdnRB18ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0015','En M1 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0016','En M2 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0017','En M3 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0018','En M4 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0019','En W1 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0020','En W2 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0021','En W3 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0022','En W4 Perfum120ml-NC','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0053','En LamanFor Him 75ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PENPS0054','En LamanFor Her 75ml','GR2','DT','PCP','DEO',''
Exec ARC_Product_Mappings_Update 'PFDHW0001','Fi Hand Wash Ha400ml','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PFDHW0002','Fi Hand Wash FR400ml','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PFDHW0003','Fi Hand Was RLX400ml','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PFDHW0004','Fi Hand Wa Ha350ml P','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PFDHW0005','Fi Hand Wa FR350ml P','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PFDHW0006','Fi Hand WaRLX350ml P','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PFDSG0206','FI SGP&A MD100ml+LoF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0209','FI MSG250ml+100mlSG','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0211','FIAMA B&B(ED)100ml+L','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0212','FIAMA L&Jo(CS100ml+L','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0214','Fiama MD100ml pr off','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0215','Fiama ED100ml prioff','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0224','Fiama L&J (CS) 500ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0225','Fiama P&A (MD) 500ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0226','FIAMA B&B (ED) 500ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0229','Fi AG&AC Gel+Cr200ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0230','Fi BK&AC Gel+Cr200ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0278','Fi L&J250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0279','Fi P&A250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0280','Fi P&B250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0281','Fi P&M250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0282','Fi RP 250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0283','Fi QW 250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0284','Fi CB 250ml+185ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0285','Fi L&J500ml+400ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0286','Fi P&A500ml+400ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0287','Fi B&B500ml+400ml PF','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0299','Fi Scents M&N 250ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0300','Fi J&GmlON 250ml','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0311','Fi Sce SGM&N100ml+Lo','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0312','Fi Sce SGJ&G100ml+Lo','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSG0322','Fi SceL&J250ml+185ML','GR2','SG','PCP','SHOWER GEL',''
Exec ARC_Product_Mappings_Update 'PFDSO0336','FI GBB S&Lg(CS)125g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0337','FI GBB P&A(MD)125g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0338','FI GBB B&B(ED)125g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0339','FI GBB P&M(LF) 125g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0342','FI Men GBB ES 125g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0343','FI Men GBB RP 125g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0344','FI GBB S&Lg CS125gx3','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0345','FI GBB P&A MD125gx3','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0346','FI GBB B&B ED125gx3','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0366','FI GBB 100gx6 MV33%E','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0367','FI MenGBB ES125gx3+1','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0368','FI GBB RP 125gX3+1','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0405','FI GBB+(G+C)125gx5C','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0407','FI MD+GelCr125gx3+1','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0418','FI FP&AC100g 75g+25g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0438','Fi P&A125gX3+RW150ml','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PFDSO0439','Fi B&B 125G+RHW150ml','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PNMFC0035','Ni  FlrClnrHerb475ml','GR2','FC','PCP','FLOOR CLEANER',''
Exec ARC_Product_Mappings_Update 'PNMFC0036','Ni  FlrClnrHerb1ltr','GR2','FC','PCP','FLOOR CLEANER',''
Exec ARC_Product_Mappings_Update 'PNMFC0052','Nimyl FC Herbal200ml','GR2','FC','PCP','FLOOR CLEANER',''
Exec ARC_Product_Mappings_Update 'PSVAL0008','SaDisinfntLqd 50ml','GR2','AL','PCP','ANTI SEPTIC LIQUID',''
Exec ARC_Product_Mappings_Update 'PSVAL0009','Sa DisinfectLqd100ml','GR2','AL','PCP','ANTI SEPTIC LIQUID',''
Exec ARC_Product_Mappings_Update 'PSVAL0010','Sa DisinfeLqd1000ml','GR2','AL','PCP','ANTI SEPTIC LIQUID',''
Exec ARC_Product_Mappings_Update 'PSVAL0011','Sa DisinfeLqd500ml','GR2','AL','PCP','ANTI SEPTIC LIQUID',''
Exec ARC_Product_Mappings_Update 'PSVAL0012','Sa DisinfeLqd200ml','GR2','AL','PCP','ANTI SEPTIC LIQUID',''
Exec ARC_Product_Mappings_Update 'PSVHS0006','Sa HndSaTy555ml-Tray','GR2','HS','PCP','HAND SANITIZER',''
Exec ARC_Product_Mappings_Update 'PSVHW0075','Sa HS200ml+185mlCo24','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0076','Sa MS200ml+185mlCo24','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0096','Sa D Cl 200ml+185ml','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0108','Sa Sen l Pch POP-NC','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0109','Sa Shl0ml Pch POP-NC','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0152','Sa Moist SHLD 80ml ','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0177','Sa CleaPOPON POP','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0178','Sa ml-n HS 200ml-POP','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0179','Sa ml-n MS 200ml-POP','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVHW0221','Savlon Deep Clean 725ml Pch-POP_PSVHW0221','GR2','HW','PCP','HAND WASH',''
Exec ARC_Product_Mappings_Update 'PSVSO0045','Sa ProgON 45g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PSVTA0022','ST Cool +Eng 18.4ml Fr','GR2','TA','PCP','TALCUM POWDER ',''
Exec ARC_Product_Mappings_Update 'PVVSO0368','Vi Vera GmsON 100Gms','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0626','Vi Oil GmsON 51Gms','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0629','Vi Oil GmsON 100Gms','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0712','Vivel Cool Mint 51g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0715','Vivel Cool Mint 100g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0759','Vivel Cool Mint 48g','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0795','Vi AloeVera 100g+So','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0796','Vi LotusOil100g+So','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0797','Vi coolmint 100g+S','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0814','Vi Aloe Vera 100g NP','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0815','Vi LOTUS OIL 100g NP','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0816','Vi COOL MINT100g NP','GR2','TS','PCP','TOILET SOAP',''
Exec ARC_Product_Mappings_Update 'PVVSO0819','Vivel CoolMint 100gX3+1(New Price)_PVVSO0819','GR2','TS','PCP','TOILET SOAP',''
GO
