IF NOT EXISTS(SELECT * FROM WDSKUList WHERE CATEGORYGROUP = 'GR4')
BEGIN
	INSERT INTO WDSKUList
	SELECT TOP 1 ID,EFFECTIVEFROMDATE,'GR4' CATEGORYGROUP,ZMAX,ZMIN,FORM,Active,AlertStatus,getdate() CreationDate,getdate() modifiedDate,MonthFlag FROM WDSKUList
END
GO
